import type { Preferences } from '../../shared/types'
import { colorKeys, colorLabels, defaultAppearance, fontIds, fonts } from '../../shared/appearance'
import { themes } from '../../shared/themes'
import { applyAppearance } from './appearance'
export function AppearanceEditor({value,onChange}:{value:Preferences;onChange:(p:Preferences)=>void}){
  const a=value.appearance??defaultAppearance,t=themes.find(t=>t.id===value.theme)??themes[0]
  const fallback={background:t.background,panel:t.surface,accent:t.accent,text:'#f0edf2',muted:'#b2b8c4'}
  return <fieldset className="appearance-editor"><legend>Customize this theme</legend><p className="muted">Overrides apply to your selected theme and both player windows. Reset returns to the original palette and fonts.</p><div className="appearance-colors">{colorKeys.map(key=><label key={key}>{colorLabels[key]}<input type="color" aria-label={colorLabels[key]+' color'} value={a.colors[key]??fallback[key]} onChange={e=>onChange({...value,appearance:{...a,colors:{...a.colors,[key]:e.target.value}}})}/><code>{a.colors[key]??fallback[key]}</code><button type="button" className="text-button" disabled={!a.colors[key]} onClick={()=>{const colors={...a.colors};delete colors[key];onChange({...value,appearance:{...a,colors}})}}>Default</button></label>)}</div><div className="appearance-fonts">{(['bodyFont','headingFont','lyricsFont'] as const).map((key,i)=><label className="field" key={key}>{['Interface font','Heading font','Lyrics font'][i]}<select aria-label={['Interface font','Heading font','Lyrics font'][i]} value={a[key]} onChange={e=>onChange({...value,appearance:{...a,[key]:e.target.value}})}>{fontIds.map(id=><option key={id} value={id}>{fonts[id].name}</option>)}</select></label>)}</div><div className="appearance-preview" style={{background:a.colors.background??fallback.background,color:a.colors.text??fallback.text,fontFamily:fonts[a.bodyFont].css,borderColor:a.colors.accent??fallback.accent}}><h3 style={{fontFamily:fonts[a.headingFont].css}}>Your own frequency.</h3><p>Albums, stories, and the songs you return to.</p><span style={{color:a.colors.accent??fallback.accent,fontFamily:fonts[a.lyricsFont].css}}>A little time for yourself.</span></div><button className="secondary" type="button" onClick={()=>applyAppearance(value)}>Preview in app</button> <button className="text-button" type="button" onClick={()=>{const p={...value,appearance:defaultAppearance};onChange(p);applyAppearance(p)}}>Reset customization</button><p className="muted">Save preferences below to keep changes. Preview lasts until you leave Settings.</p></fieldset>
}
