import {PersonalActions,openPerson} from './PersonalLibrary'
import {PlaylistDesigner} from './PlaylistDesigner'
import {progressKey} from '../../shared/timeline'
import {useEffect,useState,useRef} from 'react'
import {api,Modal,ListenActions} from './actions'
import {TrackArtwork} from './Artwork'
import type {QueueItem} from '../../shared/types'
import {defaultExperience,defaultShortcuts,shortcutActions,type Experience,type SearchGroup} from '../../shared/experience'
import {message} from './ui'
export function useExperience(){const [prefs,setPrefs]=useState(defaultExperience),saved=useRef('');useEffect(()=>{const receive=(p:Experience)=>{const json=JSON.stringify(p);if(saved.current!==json){const previous=saved.current?JSON.parse(saved.current) as Experience:null;const navigationOnly=previous&&JSON.stringify({...previous,navigation:p.navigation})===json;saved.current=json;setPrefs(draft=>navigationOnly?{...draft,navigation:p.navigation}:p)}};void api.experience().then(receive).catch(()=>{});return api.onExperience(receive)},[]);return [prefs,setPrefs] as const}
export async function toggleFavorite(item:QueueItem){const d=await api.mediaDetails(item),t=item.target;if(t.kind==='music-track')await api.musicFavorite({serverId:t.serverId,kind:'song',id:t.trackId,favorite:!d.favorite});else if(t.kind==='local-file')await api.localFavorite({rootId:t.rootId,fileId:t.fileId,favorite:!d.favorite})}
export function shortcutName(e:KeyboardEvent){const key=e.key===' '?'Space':e.key.replace('Arrow','');return [...(e.ctrlKey?['Ctrl']:[]),...(e.altKey?['Alt']:[]),...(e.shiftKey?['Shift']:[]),...(e.metaKey?['Meta']:[]),key.length===1?key.toUpperCase():key].join('+')}
export function ExperienceSettings({error,prefs,setPrefs,section}:{section:'preferences'|'data';error:(s:string)=>void;prefs:Experience;setPrefs:(p:Experience)=>void}){
 const [status,setStatus]=useState(''),[busy,setBusy]=useState(false)
 const save=async()=>{setBusy(true);try{await api.saveExperience(prefs);setStatus('Daily-use preferences saved.')}catch(e){error(message(e))}finally{setBusy(false)}}
 const reset=async(scope:'cache'|'personal'|'all')=>{setBusy(true);try{if(await api.resetData(scope)){if(scope!=='all')location.reload()}}catch(e){error(message(e))}finally{setBusy(false)}}
 return <>{section==='preferences'&&<section className="settings-panel listening-preferences">
  <h2>Daily-use preferences</h2>
  <div className="settings-toggle-grid">
   <label className="check-field"><input type="checkbox" checked={prefs.autoplay} onChange={e=>setPrefs({...prefs,autoplay:e.target.checked})}/><span>Continue with more music when the queue ends<small>Music from the same source. Books and podcasts stop at the end of their queue.</small></span></label>
   <label className="check-field"><input type="checkbox" checked={prefs.watchLocal} onChange={e=>setPrefs({...prefs,watchLocal:e.target.checked})}/><span>Watch local folders for changes<small>Update new and moved files automatically. Favorites follow files moved within the same source.</small></span></label>
  </div>
  <div className="settings-subsection"><h3>Keyboard shortcuts</h3><p className="muted">Click a field and press a key combination. Backspace clears it. Shortcuts work while the app has focus.</p>
   <div className="shortcut-grid">{shortcutActions.map(action=><label className="field" key={action}><span className="shortcut-label">{{search:'Search collections',queue:'Open queue',favorite:'Toggle favorite',mini:'Mini player',lyrics:'Show lyrics',toggle:'Play / pause',next:'Next track',previous:'Previous track'}[action]}</span><input aria-label={`${action} shortcut`} value={prefs.shortcuts[action]??''} readOnly onKeyDown={e=>{if(e.key==='Tab')return;e.preventDefault();e.stopPropagation();if(['Control','Shift','Alt','Meta'].includes(e.key))return;setPrefs({...prefs,shortcuts:{...prefs.shortcuts,[action]:e.key==='Backspace'?'':shortcutName(e.nativeEvent)}})}}/></label>)}</div>
  </div>
  <div className="settings-actions"><button className="primary" disabled={busy} onClick={()=>void save()}>Save daily-use preferences</button><button className="text-button" onClick={()=>setPrefs({...prefs,shortcuts:defaultShortcuts})}>Reset shortcuts</button></div>{status&&<p role="status">{status}</p>}
 </section>}{section==='data'&&<section className="settings-panel listening-reset"><h2>Remove app data</h2><p className="muted">Review what will be removed before confirming. Original music files and data on your servers are kept.</p>
  <div className="reset-choices">{([
   ['cache','Clear cached data','Artwork, metadata and local indexes can be rebuilt.'],
   ['personal','Remove personal listening data','History, stats, notes, queues, local playlists, favorites, lyric matches, shelves, offline plans, custom metadata/artwork, show preferences and list views.'],
   ['all','Reset application','Also removes accounts, keys, settings and downloaded copies, then restarts.']
  ] as const).map(([scope,label,description])=><div className="reset-choice" key={scope}><div><strong>{scope==='cache'?'Cached files':scope==='personal'?'Personal library':'Start fresh'}</strong><small>{description}</small></div><button className={`secondary${scope==='cache'?'':' danger'}`} disabled={busy} onClick={()=>void reset(scope)}>{label}</button></div>)}</div>
 </section>}</>
}
export function GlobalSearch({close,error}:{close:()=>void;error:(s:string)=>void}){const [query,setQuery]=useState(''),[groups,setGroups]=useState<SearchGroup[]>([]),[warnings,setWarnings]=useState<string[]>([]),[busy,setBusy]=useState(false);useEffect(()=>{let live=true;setGroups([]);setWarnings([]);if(query.trim().length<2){setBusy(false);return}setBusy(true);const timer=setTimeout(()=>void api.unifiedSearch(query).then(r=>{if(live){setGroups(r.groups);setWarnings(r.warnings)}}).catch(e=>{if(live)error(message(e))}).finally(()=>{if(live)setBusy(false)}),350);return()=>{live=false;clearTimeout(timer)}},[query]);return <Modal title="Search all collections" close={close}><label className="field">Song, artist, book or episode<input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search across your sources…"/></label>{busy&&<p role="status">Searching collections…</p>}{warnings.map(w=><p key={w} role="status">{w}</p>)}{groups.map(g=><section key={g.name}><h3>{g.name} <small>({g.items.length})</small></h3>{g.items.map((item,i)=><div className="unified-result" key={i}><TrackArtwork item={item}/><div><strong>{item.title}</strong><small>{item.subtitle}</small></div><ListenActions items={[item]} error={error} compact disabled={g.unavailable?.includes(progressKey(item.target))}/></div>)}</section>)}{!busy&&query.length>1&&groups.length>0&&!groups.some(g=>g.items.length)&&<p>No matches.</p>}<p className="muted">Results are limited per source. Podcast search includes the episodes available through your inbox.</p></Modal>}
export function TrackMenu({error}:{error:(s:string)=>void}){
 const [design,setDesign]=useState(false)
 const request=useRef(0)
 const [item,setItem]=useState<QueueItem>(),[details,setDetails]=useState<Awaited<ReturnType<typeof api.mediaDetails>>>(),[lists,setLists]=useState<{id:string;title:string}[]>([]),[chosen,setChosen]=useState(''),[status,setStatus]=useState(''),[prefs]=useExperience()
 useEffect(()=>{const show=(e:Event)=>{const q=(e as CustomEvent<QueueItem>).detail,id=++request.current;setItem(q);setDesign(false);setDetails(undefined);setLists([]);setChosen('');setStatus('');void api.mediaDetails(q).then(d=>{if(request.current===id)setDetails(d)}).catch(e=>{if(request.current===id)setStatus(message(e))});void api.mediaPlaylists(q).then(d=>{if(request.current===id)setLists(d)}).catch(e=>{if(request.current===id)setStatus(message(e))})};window.addEventListener('track-menu',show);return()=>window.removeEventListener('track-menu',show)},[])
 if(!item)return null;const music=['music-track','local-file'].includes(item.target.kind)
 const run=async(fn:()=>Promise<unknown>)=>{try{await fn();setStatus('Saved.')}catch(e){setStatus(message(e))}}
 return <Modal title={item.title} close={()=>setItem(undefined)}><div className="track-menu-layout"><p className="muted">{item.subtitle}</p><div className="track-menu-section track-menu-playback"><ListenActions items={[item]} error={setStatus} primaryActions={music?<><button className="secondary" disabled={!details} onClick={()=>void run(async()=>{await toggleFavorite(item);setDetails(await api.mediaDetails(item))})}>{details?.favorite?'Remove favorite':'Add favorite'}</button>{music&&item.subtitle&&<button className="secondary" onClick={()=>{openPerson(item.subtitle,'artist');setItem(undefined)}}>Explore artist</button>}</>:undefined}/></div><div className="track-menu-section"><PersonalActions refs={[{kind:'playable',item}]} after={()=>setItem(undefined)}/></div>{music&&<div className="track-menu-section"><label className="field">Playlist<select value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Choose a playlist</option>{lists.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><div className="control-actions"><button className="secondary" disabled={!chosen} onClick={()=>void run(()=>api.mediaAddPlaylist({item,id:chosen}))}>Add to playlist</button><button className="text-button" disabled={!chosen} onClick={()=>void run(async()=>{const t=item.target,source=t.kind==='local-file'?t.rootId:t.serverId,kind=t.kind==='local-file'?'local' as const:'music' as const;const pins=prefs.pins.filter(p=>!(p.kind===kind&&p.source===source&&p.id===chosen));await api.saveExperience({...prefs,pins:[...pins,{kind,source,id:chosen,title:lists.find(p=>p.id===chosen)!.title}]})})}>Pin playlist to Home</button><button className="secondary" disabled={!chosen} onClick={()=>setDesign(true)}>Design playlist cover</button></div></div>}{design&&chosen&&<PlaylistDesigner source={item.target.kind==='local-file'?item.target.rootId:item.target.serverId} id={chosen} name={lists.find(p=>p.id===chosen)?.title??'Playlist'} close={()=>setDesign(false)}/>}<details><summary>Track details</summary><dl className="track-details">{Object.entries(details?.details??{}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></details><p role="status">{status}</p></div></Modal>
}
