import {useState} from 'react'
import {api,Modal} from './actions'
import {useExperience} from './Experience'
import {TrackArtwork} from './Artwork'
import type {QueueItem} from '../../shared/types'
import type {HomeMix} from '../../shared/daily'
import {message} from './ui'
export function MixPreview({mix,close,error}:{mix:HomeMix;close:()=>void;error:(s:string)=>void}){const [name,setName]=useState(mix.title),[excluded,setExcluded]=useState<string[]>([]),[limit,setLimit]=useState(mix.items.length),[pool,setPool]=useState(mix.items),[notice,setNotice]=useState('');const artists=[...new Set(mix.items.map(q=>q.subtitle))].sort(),items=pool.filter(q=>!excluded.includes(q.subtitle)).slice(0,limit);const shuffle=()=>{const next=[...pool];for(let i=next.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[next[i],next[j]]=[next[j],next[i]]}setPool(next)};return <Modal title="Make this mix yours" close={close}><label className="field">Mix name<input value={name} maxLength={200} onChange={e=>setName(e.target.value)}/></label><label className="field">Length: {items.length} tracks<input type="range" min={1} max={mix.items.length} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><details><summary>Exclude artists</summary>{artists.map(a=><label key={a} className="check-field"><input type="checkbox" checked={excluded.includes(a)} onChange={e=>setExcluded(e.target.checked?[...excluded,a]:excluded.filter(v=>v!==a))}/>{a}</label>)}</details><div className="mix-preview-actions"><button className="secondary" onClick={shuffle}>Regenerate order</button><button className="primary" disabled={!items.length} onClick={()=>void api.play({queue:items,index:0}).catch(e=>error(message(e)))}>Play mix</button><button className="secondary" disabled={!items.length||!name.trim()} onClick={()=>void api.saveMix({name,items}).then(setNotice).catch(e=>error(message(e)))}>Save as playlist</button></div><p className="muted">Mixes spanning multiple sources are saved as named queues.</p><p role="status">{notice}</p>{items.map((q,i)=><div className="unified-result" key={i}><TrackArtwork item={q}/><div><strong>{q.title}</strong><small>{q.subtitle}</small></div></div>)}</Modal>}
export function HomeEditor({mixes,close,error}:{mixes:HomeMix[];close:()=>void;error:(s:string)=>void}){const [prefs,setPrefs]=useExperience();return <Modal title="Customize Home" close={close}><p>Choose what appears and move sections into your preferred order.</p>{prefs.homeOrder.map((id,i)=><div className="home-editor-row" key={id}><label className="check-field"><input type="checkbox" checked={!prefs.hiddenSections.includes(id)} onChange={e=>setPrefs({...prefs,hiddenSections:e.target.checked?prefs.hiddenSections.filter(v=>v!==id):[...prefs.hiddenSections,id]})}/>{({hero:'Welcome & stats',pins:'Pinned playlists',mixes:'Your mixes',continue:'Continue listening',albums:'Recent albums',episodes:'Fresh episodes',later:'Listen later'})[id]}</label>{[-1,1].map(d=><button className="icon-button" key={d} aria-label={`Move ${id} ${d===-1?'up':'down'}`} disabled={i+d<0||i+d>=prefs.homeOrder.length} onClick={()=>{const order=[...prefs.homeOrder];[order[i],order[i+d]]=[order[i+d],order[i]];setPrefs({...prefs,homeOrder:order})}}>{d===-1?'↑':'↓'}</button>)}</div>)}<h3>Mixes</h3><div className="dialog-toggle-grid">{mixes.map(m=><label className="check-field" key={m.id}><input type="checkbox" checked={!prefs.hiddenMixes.includes(m.id)} onChange={e=>setPrefs({...prefs,hiddenMixes:e.target.checked?prefs.hiddenMixes.filter(id=>id!==m.id):[...prefs.hiddenMixes,m.id]})}/>{m.title}</label>)}</div><h3>Pinned playlists</h3><p className="muted">Right-click a track, choose a playlist and select Pin playlist to Home.</p>{prefs.pins.map((p,i)=><div className="home-editor-row" key={i}><span>{p.title}</span><button className="text-button" onClick={()=>setPrefs({...prefs,pins:prefs.pins.filter((_,j)=>i!==j)})}>Unpin</button></div>)}<div className="settings-actions"><button className="primary" onClick={()=>void api.saveExperience(prefs).then(close).catch(e=>error(message(e)))}>Save Home layout</button></div></Modal>}
