import {PageState} from './PageState'
import {useExperience} from './Experience'
import {HomeEditor,MixPreview} from './HomeEditor'
import type {HomeMix} from '../../shared/daily'
import {useEffect,useRef,useState,type ReactNode} from 'react'
import {ArrowLeft,ArrowRight,Play,RefreshCw,Headphones,Music2,Sparkles} from 'lucide-react'
import type {HomeData,ListeningStats} from '../../shared/daily'
import type {ListenLater,QueueItem} from '../../shared/types'
import {api,songQueue} from './actions'
import {Art,duration,message} from './ui'
import {QueueArt} from './ListeningSpace'
import {CardActions} from './CardActions'
import {listeningDays} from '../../shared/listening-days'

function Shelf({title,subtitle,children,empty}:{title:string;subtitle:string;children:ReactNode[];empty:string}){
 const scroll=useRef<HTMLDivElement>(null),[edges,setEdges]=useState({start:true,end:true})
 useEffect(()=>{const el=scroll.current;if(!el)return;const update=()=>setEdges({start:el.scrollLeft<=2,end:el.scrollLeft+el.clientWidth>=el.scrollWidth-2});const observer=new ResizeObserver(update);observer.observe(el);el.addEventListener('scroll',update,{passive:true});update();return()=>{observer.disconnect();el.removeEventListener('scroll',update)}},[children.length])
 const move=(direction:number)=>scroll.current?.scrollBy({left:direction*scroll.current.clientWidth*.85,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})
 return <section className="home-shelf"><header><div><h2>{title}</h2><p>{subtitle}</p></div><div className="shelf-buttons"><button className="icon-button" aria-label={`Previous ${title}`} disabled={edges.start} onClick={()=>move(-1)}><ArrowLeft size={18}/></button><button className="icon-button" aria-label={`Next ${title}`} disabled={edges.end} onClick={()=>move(1)}><ArrowRight size={18}/></button></div></header>{children.length?<div className="home-shelf-track" ref={scroll} aria-label={title} tabIndex={0}>{children}</div>:<p className="home-empty">{empty}</p>}</section>
}
export function HomePage({error}:{error:(s:string)=>void}){
 const [prefs]=useExperience(),[editing,setEditing]=useState(false),[preview,setPreview]=useState<HomeMix>(),[pins,setPins]=useState<Awaited<ReturnType<typeof api.pinnedMusic>>>([])
 useEffect(()=>{void api.pinnedMusic().then(setPins).catch(e=>error(message(e)))},[prefs.pins])
 const [loadError,setLoadError]=useState('')
 const [data,setData]=useState<HomeData>(),[plans,setPlans]=useState<ListenLater[]>([]),[stats,setStats]=useState<ListeningStats>(),[goal,setGoal]=useState(30),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0)
 useEffect(()=>{let live=true;setBusy(true);setLoadError('');void Promise.all([api.home(revision>0),api.laterList()]).then(([d,p])=>{if(live){setData(d);setPlans(p.filter(x=>!x.done).slice(0,12))}}).catch(e=>{if(live)setLoadError(message(e))}).finally(()=>{if(live)setBusy(false)});return()=>{live=false}},[revision])
 useEffect(()=>{let live=true,inFlight=false;const refresh=async()=>{if(inFlight)return;inFlight=true;try{const [s,g]=await Promise.all([api.listeningStats(),api.dailySettings()]);if(live){setStats(s);setGoal(g.dailyGoalMinutes)}}catch(e){if(live)error(message(e))}finally{inFlight=false}};void refresh();const timer=setInterval(()=>void refresh(),15000);window.addEventListener('focus',refresh);return()=>{live=false;clearInterval(timer);window.removeEventListener('focus',refresh)}},[revision])
 const work=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn()}catch(e){error(message(e))}finally{setBusy(false)}}
 const play=(items:QueueItem[],shuffle=false)=>void work(async()=>{const queue=[...items];if(shuffle)for(let i=queue.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[queue[i],queue[j]]=[queue[j],queue[i]]}await api.play({queue,index:0})})
 const days=listeningDays(stats?.days??[]).slice(-7),today=days.at(-1)?.seconds??0,week=days.reduce((sum,d)=>sum+d.seconds,0),max=Math.max(60,...days.map(d=>d.seconds)),fraction=goal>0?Math.min(1,today/(goal*60)):0
 const first=data?.continuing[0]?.item,mixes=data?.mixes??[]
 return <div className="home-redesign">
 <header className="home-greeting"><div><p className="eyebrow">YOUR DAILY SOUNDTRACK</p><h1>Welcome home.</h1><p className="muted">A little music. A good story. Time for you.</p></div><div className="home-header-actions"><button className="secondary" onClick={()=>setEditing(true)}>Customize Home</button><button className="secondary" disabled={busy} onClick={()=>setRevision(n=>n+1)}><RefreshCw size={16}/>Refresh Home</button></div></header>
 {busy&&!data&&<PageState kind="loading" title="Gathering your listening" description="Loading your recent activity and collections."/>}{loadError&&<PageState kind="error" title="Home couldn’t finish refreshing" description={loadError} action={()=>setRevision(n=>n+1)} label="Retry Home"/>}{data?.warnings.map((w,i)=><p className="muted" role="status" key={i}>{w}</p>)}
 <div className="home-section" hidden={prefs.hiddenSections.includes('hero')} style={{order:prefs.homeOrder.indexOf('hero')}}><div className="home-hero-grid"><section className="home-feature"><div className="home-feature-glow" aria-hidden="true"/><div className="home-feature-copy"><span className="eyebrow"><Headphones size={15}/> PICK UP THE MOMENT</span><h2>{first?.title??'Find your next favorite.'}</h2><p>{first?.subtitle??'Your music, books and podcasts come together here. Start listening to shape your daily space.'}</p>{first?<button className="primary" disabled={busy} onClick={()=>play([first])}><Play size={18}/>Continue listening</button>:mixes[0]?<button className="primary" disabled={busy} onClick={()=>play(mixes[0].items,true)}><Play size={18}/>Play your mix</button>:<span className="muted">Choose something from your collections to begin.</span>}</div>{first?<QueueArt item={first}/>:<div className="home-feature-symbol" aria-hidden="true"><Music2 size={70}/></div>}</section>
 <section className="home-stats" aria-label="Current listening stats"><header><span className="eyebrow">YOUR LISTENING RHYTHM</span><small>This device · updates every 15s</small></header><div className="home-stats-main"><div className="home-goal-ring"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="43"/><circle cx="50" cy="50" r="43" strokeDasharray={`${fraction*270.18} 270.18`}/></svg><strong>{Math.floor(today/60)}<small>min today</small></strong></div><div><strong>{duration(week)}</strong><span>listened this week</span><small>{goal?`${Math.round(fraction*100)}% of your ${goal} min daily goal`:'Daily goal is off'}</small></div></div><div className="home-week-bars" aria-label="Listening over the last seven days">{days.map(d=><div key={d.day} title={`${d.day}: ${duration(d.seconds)}`}><span style={{height:`${Math.max(3,d.seconds/max*100)}%`}}/><small>{new Date(`${d.day}T12:00:00`).toLocaleDateString(undefined,{weekday:'narrow'})}</small></div>)}</div><footer><span>{stats?.finishedBooks??0} books finished</span><span>{stats?.finishedEpisodes??0} episodes finished</span></footer></section></div></div>
 <div className="home-section" hidden={prefs.hiddenSections.includes('pins')||!pins.length} style={{order:prefs.homeOrder.indexOf('pins')}}><Shelf title="Pinned playlists" subtitle="Your favorites, one click away." empty="Pin a playlist from a track menu.">{pins.map(({pin,items})=><article className="daily-card home-resume" key={`${pin.kind}:${pin.source}:${pin.id}`}><h3>{pin.title}</h3><p>{items.length?`${items.length} tracks`:'Playlist unavailable'}</p><button className="icon-button card-play" aria-label={`Play pinned ${pin.title}`} disabled={!items.length} onClick={()=>play(items)}><Play size={19}/></button></article>)}</Shelf></div>
 <div className="home-section" hidden={prefs.hiddenSections.includes('mixes')} style={{order:prefs.homeOrder.indexOf('mixes')}}> <Shelf title="Your mixes" subtitle="Built from your actual collection and listening. Shuffle a mix to change the order." empty="Star a few songs or play music to start building your mixes.">{mixes.filter(m=>!prefs.hiddenMixes.includes(m.id)).map((mix,i)=><article className={`home-mix mix-${i%3}`} key={mix.id}><Sparkles size={24}/><div className="mix-artwork" aria-hidden="true">{mix.items.slice(0,4).map((item,j)=><QueueArt key={j} item={item}/>)}</div><span className="eyebrow">{mix.items.length} TRACKS</span><h3>{mix.title}</h3><p>{mix.subtitle}</p><button className="text-button mix-preview-open" onClick={()=>setPreview(mix)}>Preview & edit</button><button className="icon-button" aria-label={`Play mix ${mix.title}`} disabled={busy} onClick={()=>play(mix.items,true)}><Play size={23}/></button></article>)}</Shelf></div>
 <div className="home-section" hidden={prefs.hiddenSections.includes('continue')} style={{order:prefs.homeOrder.indexOf('continue')}}> <Shelf title="Continue listening" subtitle="Your latest audiobook and podcast positions." empty="Start a book or episode and it will appear here.">{(data?.continuing??[]).slice(0,24).map(c=><article className="daily-card resume-card home-resume" key={JSON.stringify(c.item.target)}><span className="daily-status">In progress · {Math.round(c.progress.fraction*100)}%</span><h3 title={c.item.title}>{c.item.title}</h3><p>{c.item.subtitle}</p><div className="daily-meter"><span style={{width:`${c.progress.fraction*100}%`}}/></div><CardActions item={c.item} error={error}/></article>)}</Shelf></div>
 <div className="home-section" hidden={prefs.hiddenSections.includes('albums')} style={{order:prefs.homeOrder.indexOf('albums')}}> <Shelf title="Recently played albums" subtitle="Back to the records you love." empty="Albums you play on Navidrome will appear here.">{(data?.albums??[]).map(a=><article className="daily-card home-album-card" key={`${a.serverId}:${a.id}`}><Art item={a}/><h3 title={a.title}>{a.title}</h3><p>{a.subtitle}</p><button className="icon-button card-play" aria-label={`Play album ${a.title}`} disabled={busy} onClick={()=>void work(async()=>{const d=await api.musicDetail({serverId:a.serverId,id:a.id,kind:'album'});await api.play({queue:songQueue(d.tracks,d.title),index:0})})}><Play size={19}/></button></article>)}</Shelf></div>
 <div className="home-section" hidden={prefs.hiddenSections.includes('episodes')} style={{order:prefs.homeOrder.indexOf('episodes')}}> <Shelf title="Fresh episodes" subtitle="The latest from your shows." empty="New podcast episodes will appear when your shows have something new.">{(data?.episodes??[]).map(e=><article className="daily-card resume-card home-resume" key={JSON.stringify(e.item.target)}><span className="eyebrow">{e.episode.publishedAt?new Date(e.episode.publishedAt).toLocaleDateString():'PODCAST'}</span><h3 title={e.item.title}>{e.item.title}</h3><p>{e.showTitle}</p><small>{duration(e.item.duration??0)}</small>{e.episode.downloaded?<CardActions item={e.item} error={error}/>:<small>Not downloaded on server</small>}</article>)}</Shelf></div>
 <div className="home-section" hidden={prefs.hiddenSections.includes('later')} style={{order:prefs.homeOrder.indexOf('later')}}> <Shelf title="A little time, set aside" subtitle="The listening you saved for later." empty="Choose Listen later beside an item to make a plan.">{plans.map(p=><article className="daily-card resume-card home-resume" key={p.id}><span className="eyebrow">{p.due}</span><h3>{p.item.title}</h3><p>{p.note||p.item.subtitle}</p><CardActions item={p.item} error={error}/></article>)}</Shelf></div>
 {editing&&<HomeEditor mixes={mixes} close={()=>setEditing(false)} error={error}/>} {preview&&<MixPreview mix={preview} close={()=>setPreview(undefined)} error={error}/>}
 </div>
}
