import {useState,type ReactNode} from 'react'
import {columns,type Column} from '../../shared/personal-library'
import {usePersonal,move} from './PersonalLibrary'
import {api,Modal} from './actions'
import {message} from './ui'
import {ArrowUp,ArrowDown} from 'lucide-react'
export const defaultColumns:Column[]=['format','duration','favorite','rating']
export function ColumnControls(){const prefs=usePersonal(),[open,setOpen]=useState(false),[name,setName]=useState(''),[draft,setDraft]=useState<Column[]>(defaultColumns),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const active=prefs.views.find(v=>v.id===prefs.activeView);return <div className="column-controls"><label>List view<select aria-label="Saved list view" value={prefs.activeView} onChange={e=>void api.personalChange({action:'view-select',id:e.target.value}).catch(e=>setNotice(message(e)))}><option value="default">Default</option>{prefs.views.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><button className="secondary" onClick={()=>{setName(active?.name??'My view');setDraft(active?.columns??defaultColumns);setOpen(true)}}>Customize columns</button>{notice&&<span role="status">{notice}</span>}{open&&<Modal title="Your list, your way" close={()=>setOpen(false)}><p className="muted">Title and cover stay visible. Choose and reorder the other columns for music and local track lists. Narrow windows wrap cells without hiding controls.</p><label className="field">View name<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label>{[...draft,...columns.filter(c=>!draft.includes(c))].map(c=><div className="column-choice" key={c}><label className="check-field"><input type="checkbox" checked={draft.includes(c)} onChange={e=>setDraft(e.target.checked?[...draft,c]:draft.filter(v=>v!==c))}/>{c[0].toUpperCase()+c.slice(1)}</label><button className="icon-button" disabled={!draft.includes(c)||draft.indexOf(c)===0} aria-label={`Move ${c} left`} onClick={()=>setDraft(move(draft,draft.indexOf(c),-1))}><ArrowUp size={16}/></button><button className="icon-button" disabled={!draft.includes(c)||draft.indexOf(c)===draft.length-1} aria-label={`Move ${c} right`} onClick={()=>setDraft(move(draft,draft.indexOf(c),1))}><ArrowDown size={16}/></button></div>)}<div className="control-actions"><button className="primary" disabled={busy||!name.trim()} onClick={()=>{setBusy(true);void api.personalChange({action:'view-save',view:{id:active?.name===name?active.id:crypto.randomUUID(),name:name.trim(),columns:draft}}).then(()=>setOpen(false)).catch(e=>setNotice(message(e))).finally(()=>setBusy(false))}}>Save view</button>{active&&<button className="text-button" onClick={()=>void api.personalChange({action:'view-delete',id:active.id}).then(()=>setOpen(false)).catch(e=>setNotice(message(e)))}>Delete saved view</button>}</div></Modal>}</div>}
export function TrackColumns({values}:{values:Partial<Record<Column,ReactNode>>}){const prefs=usePersonal(),selected=prefs.views.find(v=>v.id===prefs.activeView)?.columns??defaultColumns;return <div className="track-columns">{selected.filter(c=>values[c]!==undefined).map(c=><div className={`track-column column-${c}`} key={c}><span className="column-caption">{c}</span>{values[c]}</div>)}</div>}
