import { useState } from 'react'
import { Download, Sparkles } from 'lucide-react'
import type { ListeningRecap as Recap } from '../../shared/recap'
import { api } from './actions'
import { message } from './ui'
import { renderRecap, recapStyles, type RecapStyle } from './recap-art'
const date=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
export function ListeningRecap() {
  const now=new Date(),before=new Date();before.setDate(now.getDate()-29)
  const [start,setStart]=useState(date(before)),[end,setEnd]=useState(date(now)),[style,setStyle]=useState<RecapStyle>('aurora')
  const [recap,setRecap]=useState<Recap>(),[png,setPng]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  const generate=async()=>{setBusy(true);setNotice('');setPng('');setRecap(undefined);try{const result=await api.listeningRecap({start,end});setRecap(result);if(!result.totalSeconds){setNotice('No listening was recorded on this device in this date range. Try a different range.');return}await document.fonts.ready;setPng(renderRecap(result,style))}catch(e){setNotice(message(e))}finally{setBusy(false)}}
  const save=async()=>{if(!recap||!png)return;setBusy(true);setNotice('');try{const saved=await api.exportRecap({range:{start:recap.start,end:recap.end},png});setNotice(saved?'Your recap image was saved.':'Save cancelled.')}catch(e){setNotice(message(e))}finally{setBusy(false)}}
  return <section className="recap-section"><div className="recap-heading"><Sparkles size={24}/><div><h2>Your listening, wrapped.</h2><p>Turn a week, a year, or any dates you choose into a picture worth keeping.</p></div></div><div className="recap-layout"><div className="recap-controls"><label className="field">Start date<input aria-label="Recap start date" type="date" value={start} disabled={busy} onChange={e=>{setStart(e.target.value);setPng('')}}/></label><label className="field">End date<input aria-label="Recap end date" type="date" value={end} disabled={busy} onChange={e=>{setEnd(e.target.value);setPng('')}}/></label><label className="field">Picture style<select value={style} disabled={busy} onChange={e=>{const next=e.target.value as RecapStyle;setStyle(next);if(recap&&png)setPng(renderRecap(recap,next))}}>{Object.entries(recapStyles).map(([id,s])=><option key={id} value={id}>{s.name}</option>)}</select></label><button className="primary" disabled={busy||!start||!end} onClick={()=>void generate()}><Sparkles size={16}/>{busy?'Working…':'Create my recap'}</button><button className="secondary" disabled={busy||!png} onClick={()=>void save()}><Download size={16}/>Save PNG image</button><p className="recap-note">1080 × 1440 pixels. Includes music, books, podcasts, local audio, and radio recorded by this app. Dates include both endpoints and use the local calendar at the time of listening. No server history is imported.</p>{notice&&<p role="status" className="recap-notice">{notice}</p>}</div><div className="recap-preview">{png?<><img src={png} alt={`Listening recap from ${recap?.start} to ${recap?.end}: ${Math.round((recap?.totalSeconds??0)/60)} minutes across ${recap?.activeDays} active days. Top listen: ${recap?.top[0]?.title}.`}/><p className="sr-only">{recap?.top.map(t=>`${t.title} by ${t.subtitle}`).join('; ')}</p></>:<div className="recap-placeholder"><Sparkles size={40}/><strong>A snapshot of your sound.</strong><p>Choose your dates and create a recap to preview it here.</p></div>}</div></div></section>
}
