import { AppearanceEditor } from './AppearanceEditor'
import { applyAppearance } from './appearance'
import {ImmersivePlayer} from './ImmersivePlayer'
import { LyricsPanel } from './LyricsPanel'
import { ThemePicker } from './ThemePicker'
import { useEffect, useState } from 'react'
import { ArrowDown, ArrowUp, Folder, FolderPlus, Play, Trash2, X } from 'lucide-react'
import { defaultPreferences, type HistoryItem, type ListenLater, type LocalFile, type LocalFolder, type LocalRoot, type PlaybackState, type QueueItem } from '../../shared/types'
import { Art, duration, message } from './ui'
import { SavedQueues } from './DailySpace'
import { api, ListenActions } from './actions'
export function QueueArt({ item }: { item?: QueueItem }) {
  const [cover, setCover] = useState<string | null>(null), target = item?.target
  useEffect(() => { setCover(null); let live = true; if (target?.kind === 'local-file') void api.localCover({ rootId: target.rootId, fileId: target.fileId }).then(c => { if (live) setCover(c) }).catch(() => {}); return () => { live = false } }, [JSON.stringify(target)])
  if (!item) return <div className="art idle-art">♫</div>
  if (target?.kind === 'local-file') return cover ? <div className="art"><img src={cover} alt=""/></div> : <div className="art idle-art">♫</div>
  return <Art item={{ id: item.cover ?? (target?.kind === 'audiobook' ? target.bookId : target?.kind === 'podcast-episode' ? target.showId : ''), title: item.title, subtitle: item.subtitle, serverId: item.target.serverId, kind: item.target.kind, cover: item.cover }}/>
}
export function QueuePage({ player, error, expanded = false, close }: { player: PlaybackState; error: (s: string) => void; expanded?: boolean; close?: () => void }) {
  const [drag,setDrag]=useState<number|null>(null),[over,setOver]=useState<number|null>(null),[page,setPage]=useState(0)
  const [panel,setPanel]=useState<'queue'|'lyrics'>('queue')
  const [immersive,setImmersive]=useState(false)
  const item = player.queue[player.queueIndex]
  const canLyrics=item?.target.kind==='music-track'||item?.target.kind==='local-file'
  useEffect(()=>{if(!canLyrics)setPanel('queue')},[canLyrics])
  useEffect(()=>setPage(Math.floor(player.queueIndex/100)),[player.queueIndex])
  const edit = (input: Parameters<typeof api.queueEdit>[0]) => void api.queueEdit(input).catch(e => error(message(e)))
  if(expanded&&immersive)return <ImmersivePlayer player={player} close={()=>setImmersive(false)}/>
  return <div className={`queue-page ${expanded ? 'expanded-player' : ''}`}>
    {expanded && <section className="expanded-art"><button className="icon-button collapse-player" aria-label="Close now playing" onClick={close}><X/></button><QueueArt item={item}/><p className="eyebrow">{item?.context ?? 'NOW PLAYING'}</p><h1>{player.title}</h1><p>{player.subtitle}</p><p className="muted">{player.codec?.toUpperCase() ?? 'MPV'}{player.sampleRate ? ` · ${player.sampleRate / 1000} kHz` : ''}{player.buffering ? ' · Buffering…' : ''}</p>{item && <ListenActions items={[item]} error={error}/>}</section>}
    <div className="now-content">{expanded&&<div className="now-tabs" role="group" aria-label="Now playing view"><button className="secondary" aria-pressed={panel==='queue'} onClick={()=>setPanel('queue')}>Queue</button><button className="secondary" disabled={!canLyrics} aria-pressed={panel==='lyrics'} onClick={()=>setPanel('lyrics')}>Lyrics</button><button className="secondary" onClick={()=>setImmersive(true)}>Immersive view</button></div>}{expanded&&panel==='lyrics'?<LyricsPanel player={player}/>:<section className="queue-content"><p className="eyebrow">{expanded ? 'UP NEXT' : 'YOUR LISTENING SPACE'}</p><div className="section-title"><h2>{item?.context ?? 'Play queue'}</h2><span>{player.queue.length} items</span></div><div className="listen-actions"><button className="secondary" disabled={!player.queue.length} onClick={() => edit({ action: 'clear-upcoming' })}>Clear upcoming</button><button className="text-button" disabled={!player.queue.length} onClick={() => edit({ action: 'clear' })}>Stop & clear</button>{player.chapters.length > 0 && <label className="check-field"><input type="checkbox" checked={!!player.sleepChapter} onChange={e => edit({ action: 'sleep-chapter', enabled: e.target.checked })}/>Sleep at chapter end</label>}</div>
      <SavedQueues player={player} error={error}/>{player.queue.length>100&&<div className="pagination"><button className="secondary" disabled={!page} onClick={()=>setPage(n=>n-1)}>Previous queue page</button><span>Page {page+1} of {Math.ceil(player.queue.length/100)}</span><button className="secondary" disabled={(page+1)*100>=player.queue.length} onClick={()=>setPage(n=>n+1)}>Next queue page</button></div>}
      {player.status === 'idle' && !!player.queue.length && <p className="muted">Your queue is saved. Choose an item to resume playback.</p>}
      {player.queue.slice(page*100,(page+1)*100).map((q,offset) => { const i=page*100+offset; return <div key={i} draggable onDragStart={e=>{setDrag(i);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(i))}} onDragOver={e=>{e.preventDefault();setOver(i)}} onDragEnd={()=>{setDrag(null);setOver(null)}} onDrop={e=>{e.preventDefault();if(drag!==null&&drag!==i)edit({action:'move',from:drag,to:i});setDrag(null);setOver(null)}} className={`queue-row editable ${i === player.queueIndex ? 'current' : ''} ${over===i?'drag-over':''}`}><button className="icon-button" aria-label={`Play ${q.title}`} onClick={() => edit({ action: 'jump', index: i })}><Play size={15}/></button><div className="queue-copy"><strong>{q.title}</strong><small>{q.subtitle}</small></div><span>{q.duration ? duration(q.duration) : ''}</span><div className="row-tools"><button className="icon-button" aria-label={`Move queue item ${i+1} up`} disabled={!i} onClick={() => edit({ action: 'move', from: i, to: i-1 })}><ArrowUp size={15}/></button><button className="icon-button" aria-label={`Move queue item ${i+1} down`} disabled={i === player.queue.length-1} onClick={() => edit({ action: 'move', from: i, to: i+1 })}><ArrowDown size={15}/></button><button className="icon-button" aria-label={`Remove queue item ${i+1}`} disabled={i === player.queueIndex && player.status !== 'idle'} onClick={() => edit({ action: 'remove', index: i })}><Trash2 size={15}/></button></div></div>})}
      {!player.queue.length && <p className="empty-state">Add music, books, episodes, or local files to begin.</p>}
      {!!player.chapters.length && <details className="files-detail"><summary>Current book chapters</summary>{player.chapters.map(c => <button key={c.id} className="file-row" onClick={() => void api.command({ action: 'seek', value: c.start }).catch(e => error(message(e)))}><span>{c.title}</span><span>{duration(c.start)}</span></button>)}</details>}
    </section>}</div>
  </div>
}
export function LocalPage({ error }: { error: (s: string) => void }) {
  const [roots, setRoots] = useState<LocalRoot[]>([]), [rootId, setRootId] = useState(''), [folder, setFolder] = useState(''), [data, setData] = useState<LocalFolder | null>(null), [search, setSearch] = useState(''), [sort, setSort] = useState('name'), [busy, setBusy] = useState(false), [revision, setRevision] = useState(0)
  useEffect(() => { void api.localRoots().then(setRoots).catch(e => error(message(e))) }, [revision])
  const root = roots.find(r => r.id === rootId) ?? roots[0]
  useEffect(() => { if (!root) { setData(null); return }; let live = true; setBusy(true); setData(null); void api.localBrowse({ rootId: root.id, folder }).then(r => { if (live) setData(r) }).catch(e => { if (live) error(message(e)) }).finally(() => { if (live) setBusy(false) }); return () => { live = false } }, [root?.id, folder, revision])
  const files = (data?.files ?? []).filter(f => `${f.name} ${f.title} ${f.artist} ${f.album}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b) => sort === 'duration' ? a.duration-b.duration : sort === 'modified' ? b.modified-a.modified : sort === 'trackNumber' ? (a.trackNumber ?? 0)-(b.trackNumber ?? 0) : String(a[sort as keyof LocalFile] ?? '').localeCompare(String(b[sort as keyof LocalFile] ?? ''),undefined,{numeric:true}))
  const queue = (f: LocalFile): QueueItem => ({ target: { kind: 'local-file', serverId: 'local', rootId: root!.id, fileId: f.id }, title: f.title, subtitle: f.artist || f.name, duration: f.duration, context: folder || root?.name })
  const parts = folder.split(/[\\/]/).filter(Boolean)
  return <div className="local-page"><p className="eyebrow">RIGHT WHERE YOU LEFT IT</p><div className="section-title"><h1>Local files.</h1><button className="primary" onClick={() => void api.localAdd().then(r => { if (r) { setRootId(r.id); setFolder(''); setRevision(n => n+1) } }).catch(e => error(message(e)))}><FolderPlus size={16}/>Add folder</button></div><p className="page-intro">Your folders, in their original structure. Audio tags appear when available.</p>{roots.length > 0 && <div className="library-toolbar"><select aria-label="Local root folder" value={root?.id ?? ''} onChange={e => { setRootId(e.target.value); setFolder('') }}>{roots.map(r => <option value={r.id} key={r.id}>{r.name} · {r.path}</option>)}</select><button className="text-button" onClick={() => setRevision(n => n+1)}>Refresh folder</button><button className="text-button" onClick={() => void api.localRemove(root!.id).then(() => { setRootId(''); setFolder(''); setRevision(n => n+1) }).catch(e => error(message(e)))}>Remove source</button></div>}
    {root && <><nav className="folder-breadcrumb" aria-label="Folder path"><button onClick={() => setFolder('')}>{root.name}</button>{parts.map((p,i) => <span key={i}> / <button onClick={() => setFolder(parts.slice(0,i+1).join('\\'))}>{p}</button></span>)}</nav><div className="library-toolbar"><input aria-label="Search local folder" placeholder="Search this folder…" value={search} onChange={e => setSearch(e.target.value)}/><select aria-label="Local file sort" value={sort} onChange={e => setSort(e.target.value)}>{[['name','Filename'],['title','Title'],['artist','Artist'],['album','Album'],['trackNumber','Track number'],['duration','Duration'],['modified','Recently modified']].map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></div></>}
    {busy && <p role="status">Reading audio metadata…</p>}{data && <><div className="folder-grid">{data.folders.map(f => <button key={f.id} className="folder-card" onClick={() => { setFolder(f.id); setSearch('') }}><Folder size={24}/>{f.name}</button>)}</div><div className="section-title"><h2>{files.length} audio {files.length === 1 ? 'file' : 'files'}</h2><ListenActions items={files.map(queue)} error={error}/></div>{files.map((f,i) => <div className="local-file-row" key={f.id}><button className="song-title" onClick={() => void api.play({ queue: files.map(queue), index: i }).catch(e => error(message(e)))}><Play size={16}/><div><strong>{f.title}</strong><small>{f.artist || f.name}{f.album ? ` · ${f.album}` : ''}</small></div></button><span className="format">{f.codec?.toUpperCase() ?? f.name.split('.').at(-1)?.toUpperCase()}{f.sampleRate ? ` · ${f.sampleRate/1000} kHz` : ''}{f.bitDepth ? ` / ${f.bitDepth} bit` : ''}<small>{(f.size/1024/1024).toFixed(1)} MB{f.error ? ' · Tags unavailable' : ''}</small></span><span>{duration(f.duration)}</span><ListenActions items={[queue(f)]} error={error} compact/></div>)}{data.warnings.length > 0 && <details><summary>{data.warnings.length} files or folders could not be read</summary>{data.warnings.map((w,i) => <p key={i}>{w}</p>)}</details>}</>}
    {!root && <p className="empty-state">Choose a folder containing audio. Removing a source never deletes your files.</p>}
  </div>
}
export function LaterPage({ error, history = false }: { error: (s: string) => void; history?: boolean }) {
  const [plans, setPlans] = useState<ListenLater[]>([]), [recent, setRecent] = useState<HistoryItem[]>([]), [revision, setRevision] = useState(0), [showDone, setShowDone] = useState(false)
  useEffect(() => { void (history ? api.history().then(setRecent) : api.laterList().then(setPlans)).catch(e => error(message(e))) }, [history, revision])
  return <div className="later-page"><p className="eyebrow">YOUR LISTENING SPACE</p><div className="section-title"><h1>{history ? 'Recently listened.' : 'A little time, set aside.'}</h1>{!history && <label className="check-field"><input type="checkbox" checked={showDone} onChange={e => setShowDone(e.target.checked)}/>Show completed plans</label>}</div><p className="page-intro">{history ? 'Recent listening on this device. Audiobookshelf resumes from its latest server position.' : 'A personal listening list across your music, books, podcasts, and local files.'}</p>
    {history ? recent.map(h => <article className="plan-card history-card" key={h.id}><div><h3>{h.item.title}</h3><p>{h.item.subtitle}</p><small>{new Date(h.playedAt).toLocaleString()} · {duration(h.position)} / {duration(h.duration)}</small></div><ListenActions items={[h.item]} error={error} compact/></article>) : plans.filter(p => showDone || !p.done).map(p => <article className={`plan-card ${p.done ? 'done' : ''}`} key={p.id}><div><p className="eyebrow">{new Date(`${p.due}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</p><h3>{p.item.title}</h3><p>{p.item.subtitle}</p>{p.note && <p className="plan-note">{p.note}</p>}<label className="field compact-field">Reschedule<input type="date" value={p.due} onChange={e => { if (e.target.value) void api.laterSave({ id: p.id, item: p.item, note: p.note, done: p.done, due: e.target.value }).then(() => setRevision(n => n+1)).catch(e => error(message(e))) }}/></label></div><div><ListenActions items={[p.item]} error={error}/><div className="listen-actions"><button className="text-button" onClick={() => void api.laterSave({ id: p.id, item: p.item, note: p.note, due: p.due, done: !p.done }).then(() => setRevision(n => n+1)).catch(e => error(message(e)))}>{p.done ? 'Reopen plan' : 'Mark done'}</button><button className="icon-button" aria-label={`Remove plan ${p.item.title}`} onClick={() => void api.laterDelete(p.id).then(() => setRevision(n => n+1)).catch(e => error(message(e)))}><Trash2 size={15}/></button></div></div></article>)}
    {!(history ? recent.length : plans.filter(p => showDone || !p.done).length) && <p className="empty-state">{history ? 'Your listening history will appear here.' : 'Use Listen later beside any playable item to make a plan.'}</p>}
  </div>
}
export function AudioPreferences({ error }: { error: (s: string) => void }) {
  const [prefs, setPrefs] = useState(defaultPreferences), [saved, setSaved] = useState(false)
  useEffect(() => { void api.preferences().then(setPrefs).catch(e => error(message(e)));return()=>{void api.preferences().then(applyAppearance).catch(()=>{})} }, [])
  return <section className="settings-panel audio-preferences"><h2>Make it sound like yours</h2><p className="muted">ReplayGain and equalization are optional. Leave both off for unprocessed audio.</p><label className="field">ReplayGain<select value={prefs.replayGain} onChange={e => setPrefs({ ...prefs, replayGain: e.target.value as typeof prefs.replayGain })}><option value="no">Off</option><option value="track">Track gain</option><option value="album">Album gain</option></select></label><label className="check-field"><input type="checkbox" checked={prefs.preventClipping} onChange={e => setPrefs({ ...prefs, preventClipping: e.target.checked })}/>Prevent ReplayGain clipping</label><div className="equalizer">{['31','62','125','250','500','1k','2k','4k','8k','16k'].map((b,i) => <label key={b}><span>{prefs.equalizer[i]} dB</span><input aria-label={`Equalizer ${b} Hz`} type="range" min={-12} max={12} step={1} value={prefs.equalizer[i]} onChange={e => setPrefs({ ...prefs, equalizer: prefs.equalizer.map((v,j) => j === i ? Number(e.target.value) : v) })}/><small>{b}</small></label>)}</div><button className="text-button" onClick={() => setPrefs({ ...prefs, equalizer: Array(10).fill(0) })}>Reset equalizer</button><label className="check-field"><input type="checkbox" checked={prefs.scrobble} onChange={e => setPrefs({ ...prefs, scrobble: e.target.checked })}/>Send now playing and listening history to Navidrome</label><label className="check-field"><input type="checkbox" checked={prefs.closeToTray} onChange={e => setPrefs({ ...prefs, closeToTray: e.target.checked })}/>Keep playing in the system tray when the window closes</label><ThemePicker value={prefs.theme} onChange={theme=>setPrefs({...prefs,theme})}/><AppearanceEditor value={prefs} onChange={p=>{setPrefs(p);setSaved(false)}}/><button className="primary" onClick={() => void api.savePreferences(prefs).then(() => { applyAppearance(prefs); setSaved(true) }).catch(e => error(message(e)))}>Save audio preferences</button>{saved && <span className="action-notice" role="status">Saved</span>}</section>
}
