import {ColumnControls,TrackColumns} from './ListViews'
import {PersonalActions,usePersonal} from './PersonalLibrary'
import {PageState} from './PageState'
import {CollectionHeader} from './CollectionHeader'
import {PlaylistCover,PlaylistDesigner} from './PlaylistDesigner'
import {LocalPlaylistEditor} from './LocalPlaylistEditor'
import {TrackArtwork} from './Artwork'
import {useEffect,useMemo,useState} from 'react'
import {FolderPlus,RefreshCw,Search,Heart,ArrowLeft,Play,Trash2} from 'lucide-react'
import type {LocalRoot,QueueItem} from '../../shared/types'
import type {LocalQuery,LocalPageData,LocalIndexedTrack} from '../../shared/local-library'
import {LocalFolders,QueueArt} from './ListeningSpace'
import {api,ListenActions,Modal} from './actions'
import {duration,message} from './ui'
const tabs=[['albums','Albums'],['songs','Songs'],['artists','Artists'],['genres','Genres'],['favorites','Favorites'],['newest','Recently added'],['recent','Recently played'],['playlists','Playlists'],['folders','Folders']] as const
export function LocalPage({error}:{error:(s:string)=>void}){
 const [loadError,setLoadError]=useState('')
 const [design,setDesign]=useState(false)
 const [roots,setRoots]=useState<LocalRoot[]>([]),[rootId,setRootId]=useState(''),[view,setView]=useState<LocalQuery['view']>('albums'),[search,setSearch]=useState(''),[sort,setSort]=useState<LocalQuery['sort']>('title'),[group,setGroup]=useState<{id:string;title:string}>(),[page,setPage]=useState(0),[data,setData]=useState<LocalPageData>(),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[selected,setSelected]=useState<string[]>([]),[name,setName]=useState<string|null>(null)
 const [editPlaylist,setEditPlaylist]=useState<string>()
 const personal=usePersonal(),metadataRevision=useMemo(()=>JSON.stringify(personal.metadata),[personal.metadata])
 useEffect(()=>setRevision(n=>n+1),[metadataRevision])
 useEffect(()=>api.onExperience(()=>setRevision(n=>n+1)),[])
 const root=roots.find(r=>r.id===rootId)??roots[0]
 useEffect(()=>{void api.localRoots().then(setRoots).catch(e=>error(message(e)))},[revision,view])
 useEffect(()=>{if(!root||view==='folders')return;let live=true;setBusy(true);setLoadError('');setSelected([]);const timer=setTimeout(()=>void api.localLibrary({rootId:root.id,view,page,search,sort,group:group?.id}).then(d=>{if(live)setData(d)}).catch(e=>{if(live)setLoadError(message(e))}).finally(()=>{if(live)setBusy(false)}),200);return()=>{live=false;clearTimeout(timer)}},[root?.id,view,page,search,sort,group?.id,revision])
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();setRevision(n=>n+1)}catch(e){error(message(e))}finally{setBusy(false)}}
 const target=(id:string)=>({kind:'local-file' as const,serverId:'local' as const,rootId:root!.id,fileId:id})
 const queue=(f:LocalIndexedTrack):QueueItem=>({target:target(f.id),title:f.title,subtitle:f.artist||f.name,duration:f.duration,context:f.album||root?.name})
 const reset=()=>{setPage(0);setGroup(undefined);setSearch('');setData(undefined);setSelected([])}
 return <div className="local-library customizable-table"><p className="eyebrow">YOUR COLLECTION · ON THIS COMPUTER</p><div className="section-title"><div><h1>Local music.</h1><p className="muted">{data?.trackCount??0} indexed tracks · original audio, played through MPV</p></div>{view!=='folders'&&<button className="primary" disabled={busy} onClick={()=>void run(async()=>{const r=await api.localAdd();if(r){setRootId(r.id);reset()}})}><FolderPlus size={16}/>Add folder</button>}</div>
 <div className="browse-tabs" role="tablist" aria-label="Local music views">{tabs.map(([id,label])=><button role="tab" aria-selected={view===id} key={id} className={`filter ${view===id?'active':''}`} onClick={()=>{setView(id);reset()}}>{label}</button>)}</div>
 {view==='folders'?<LocalFolders error={error}/>:<>
 {!!roots.length&&<div className="library-toolbar"><button className="secondary" disabled={busy} onClick={()=>void run(()=>api.localPlaylistFile({rootId:root!.id,action:'import'}))}>Import M3U playlist</button><select aria-label="Local music source" value={root?.id} onChange={e=>{setRootId(e.target.value);reset()}}>{roots.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><label className="search"><Search size={16}/><input aria-label="Search local library" placeholder="Search titles, albums, artists or genres…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label>{(['songs','favorites'].includes(view)||(group&&['artists','genres'].includes(view)))&&<select aria-label="Local library sort" value={sort} onChange={e=>{setSort(e.target.value as typeof sort);setPage(0)}}><option value="title">Title</option><option value="artist">Artist</option><option value="year">Year</option><option value="duration">Duration</option></select>}<button className="secondary" disabled={busy} onClick={()=>void run(async()=>setData(await api.localLibrary({rootId:root!.id,view,page,search,sort,group:group?.id,refresh:true})))}><RefreshCw size={16}/>Rescan library</button><button className="text-button" disabled={busy} onClick={()=>void run(async()=>{await api.localRemove(root!.id);setRootId('');reset()})}>Remove source</button></div>}
 {group&&<><button className="text-button back" onClick={()=>{setGroup(undefined);setPage(0);setSelected([])}}><ArrowLeft size={16}/>Back to {tabs.find(t=>t[0]===view)?.[1]}</button><CollectionHeader className="local-detail-hero"><PlaylistCover source={root!.id} id={view==='playlists'?group.id:undefined}><QueueArt item={data?.tracks[0]?queue(data.tracks[0]):undefined}/></PlaylistCover><div className="detail-heading"><p className="eyebrow">{view==='playlists'?'Playlist':view==='albums'?'Album':view==='artists'?'Artist':'Genre'}</p><h2>{group.title}</h2><p>{data?.total??0} tracks · {root?.name}</p><ListenActions items={data?.tracks.map(queue)??[]} error={error} disabled={busy}/><small className="muted">Playback uses this page (up to 100 tracks).</small><div className="local-playlist-management">{view==='playlists'&&<><button className="secondary" onClick={()=>setDesign(true)}>Design playlist cover</button>{design&&<PlaylistDesigner source={root!.id} id={group.id} name={group.title} close={()=>setDesign(false)}/>}<button className="secondary" onClick={()=>setEditPlaylist(group.id)}>Edit playlist</button><button className="secondary" onClick={()=>void run(()=>api.localPlaylistFile({rootId:root!.id,action:'export',id:group.id}))}>Export M3U</button></>}{view==='playlists'&&<button className="secondary danger" disabled={busy} onClick={()=>void run(async()=>{await api.localPlaylist({action:'delete',rootId:root!.id,id:group.id});setGroup(undefined)})}><Trash2 size={16}/>Delete playlist</button>}</div></div></CollectionHeader></>}

 {busy&&<PageState kind="loading" title="Reading your local library" description="The first scan reads tags in every subfolder. Large collections can take a moment."/>}{loadError&&<PageState kind="error" title="Couldn’t read this folder" description={loadError} action={()=>setRevision(n=>n+1)} label="Retry scan"/>}
 {root&&data&&!busy&&!loadError&&<>
 <div className="local-collection-grid">{data.groups.map(g=><article className="local-collection-card" key={g.id}><button className="local-group-open" aria-label={`Open ${g.title}`} onClick={()=>{setGroup({id:g.id,title:g.title});setPage(0)}}><PlaylistCover source={root!.id} id={view==='playlists'?g.id:undefined}>{g.fileId&&<QueueArt item={{target:target(g.fileId),title:g.title,subtitle:g.subtitle}}/>}</PlaylistCover><strong>{g.title}</strong><small>{g.subtitle} · {g.count} tracks</small></button></article>)}</div>
 {!!data.tracks.length&&<><div className="local-selection"><label className="check-field"><input type="checkbox" checked={selected.length===data.tracks.length} onChange={e=>setSelected(e.target.checked?data.tracks.map(f=>f.id):[])}/>Select this page</label><button className="secondary" disabled={!selected.length} onClick={()=>setName('')}>Create playlist ({selected.length})</button>{!group&&<><ListenActions items={data.tracks.map(queue)} error={error}/><small>Playback actions use this page (up to 100 tracks).</small></>}</div>
 <ColumnControls/><PersonalActions refs={data.tracks.filter(f=>!selected.length||selected.includes(f.id)).map(f=>({kind:'playable' as const,item:queue(f)}))}/>{data.tracks.map((f,i)=><div className="local-library-track" key={`${i}:${f.id}`}><input type="checkbox" aria-label={`Select ${f.title}`} checked={selected.includes(f.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,f.id]:ids.filter(id=>id!==f.id))}/><button className="song-title" onClick={()=>void api.play({queue:data.tracks.map(queue),index:i}).catch(e=>error(message(e)))}><TrackArtwork item={queue(f)}/><span><strong>{f.title}</strong><small>{f.artist||'Unknown artist'} · {f.album||f.name}</small></span></button><TrackColumns values={{artist:f.artist,album:f.album,year:f.year??'—',genre:f.genre??'—',format:(<span className="format">{f.codec??f.name.split('.').at(-1)}{f.sampleRate?` · ${f.sampleRate/1000} kHz`:''}</span>),duration:(<span>{duration(f.duration)}</span>),favorite:(<button className="icon-button" aria-label={`${f.favorite?'Unfavorite':'Favorite'} ${f.title}`} aria-pressed={f.favorite} onClick={()=>void run(()=>api.localFavorite({rootId:root.id,fileId:f.id,favorite:!f.favorite}))}><Heart size={17} fill={f.favorite?'currentColor':'none'}/></button>)}}/><ListenActions items={[queue(f)]} error={error} compact/></div>)}</>}
 {!data.total&&<div className="empty-state">{view==='playlists'?'Select songs in the Songs tab to create your first local playlist.':'No matches in this view. Add audio, change your search, or rescan your source.'}</div>}
 {data.total>100&&<div className="pagination"><button className="secondary" disabled={!page} onClick={()=>setPage(n=>n-1)}>Previous</button><span>{data.total} results · Page {page+1}</span><button className="secondary" disabled={(page+1)*100>=data.total} onClick={()=>setPage(n=>n+1)}>Next</button></div>}
 {data.warnings.map((w,i)=><p key={i} role="status" className="muted">{w}</p>)}<p className="muted local-index-note">Indexed {new Date(data.updatedAt).toLocaleString()}. Folder watching updates changes automatically when enabled in Settings. Recently added uses file modification dates.</p>
 </>}{!root&&<PageState kind="empty" title="Your local library starts here" description="Add a music folder. Your files stay in their original location." action={()=>void run(async()=>{const r=await api.localAdd();if(r){setRootId(r.id);reset()}})} label="Choose music folder"/>}
 </>}
 {editPlaylist&&root&&<LocalPlaylistEditor rootId={root.id} id={editPlaylist} error={error} close={()=>{setEditPlaylist(undefined);setRevision(n=>n+1)}}/>}
 {name!==null&&<Modal title="Create local playlist" close={()=>setName(null)}><label className="field">Playlist name<input aria-label="Local playlist name" value={name} maxLength={200} onChange={e=>setName(e.target.value)}/></label><p>{selected.length} selected songs from this page</p><button className="primary" disabled={!name.trim()||busy} onClick={()=>void run(async()=>{await api.localPlaylist({action:'create',rootId:root!.id,name,files:selected});setName(null)})}>Save local playlist</button></Modal>}
 </div>
}
