import React from 'react'
import { createRoot } from 'react-dom/client'
import { App } from './App'
import { MiniPlayer } from './MiniPlayer'
import './style.css'
import './features.css'
import './readability.css'
import './modern.css'
import './themes.css'
import './recap.css'
import './playing-screen.css'
import './customization.css'
import './polish.css'
import './lyrics-style.css'
import './home-library.css'
import './refinement.css'
import './studio.css'
import './collection-headers.css'
import './release-polish.css'
createRoot(document.getElementById('root')!).render(<React.StrictMode>{new URLSearchParams(location.search).get('mini') === '1' ? <MiniPlayer/> : <App/>}</React.StrictMode>)
