import { useEffect, useState } from 'react'
import { Expand, Pin, PinOff, X, Play, Pause, SkipBack, SkipForward } from 'lucide-react'
import { emptyPlayback, type PlayerCommand } from '../../shared/types'
import { api } from './actions'
import { QueueArt } from './ListeningSpace'
import { duration, message } from './ui'
export function MiniPlayer() {
  const [player,setPlayer]=useState(emptyPlayback),[pinned,setPinned]=useState(true),[error,setError]=useState('')
  useEffect(()=>{void api.playback().then(setPlayer).catch(e=>setError(message(e)));void api.preferences().then(p=>{document.documentElement.dataset.theme=p.theme});return api.onPlayback(setPlayer)},[])
  const command=(c:PlayerCommand)=>void api.command(c).catch(e=>setError(message(e)))
  return <div className="mini-player"><header className="mini-drag"><span>media<span className="brand-light">center</span></span><div className="row-tools"><button className="icon-button" aria-label={pinned?'Unpin mini player':'Keep mini player on top'} onClick={()=>void api.miniPlayer({action:'pin',pinned:!pinned}).then(()=>setPinned(!pinned))}>{pinned?<Pin size={15}/>:<PinOff size={15}/>}</button><button className="icon-button" aria-label="Open main window" onClick={()=>void api.miniPlayer({action:'main'})}><Expand size={15}/></button><button className="icon-button" aria-label="Close mini player" onClick={()=>void api.miniPlayer({action:'close'})}><X size={15}/></button></div></header><div className="mini-body"><QueueArt item={player.queue[player.queueIndex]}/><div className="mini-copy"><strong>{player.title}</strong><small>{player.subtitle}</small><div className="mini-controls"><button className="icon-button" aria-label="Previous" disabled={!player.queue.length} onClick={()=>command({action:'previous'})}><SkipBack size={18}/></button><button className="play-main" aria-label={player.status==='playing'?'Pause':'Play'} disabled={!player.queue.length} onClick={()=>command({action:'toggle'})}>{player.status==='playing'?<Pause size={20}/>:<Play size={20}/>}</button><button className="icon-button" aria-label="Next" disabled={!player.queue.length} onClick={()=>command({action:'next'})}><SkipForward size={18}/></button><span>{player.status==='loading'?'Loading…':duration(player.position)}</span></div></div></div><input className="mini-seek" aria-label="Playback position" type="range" min={0} max={player.duration||1} step={1} value={Math.min(player.position,player.duration||1)} disabled={!player.duration||player.status==='loading'} onChange={e=>command({action:'seek',value:Number(e.target.value)})}/>{(error||player.error) && <p className="mini-error" role="alert">{error||player.error}</p>}</div>
}
