import {useEffect,useState} from 'react'
import {Plus,Trash2,Sparkles,RefreshCw} from 'lucide-react'
import {mixDefinitionSchema,sourceKey,textFields,numberFields,type MixDefinition,type MixCondition,type MixPreview,type MixSource} from '../../shared/mixes'
import {api,Modal,ListenActions} from './actions'
import {duration,message} from './ui'
import {TrackArtwork} from './Artwork'
import {usePersonal} from './PersonalLibrary'

export function openMixBuilder(mix?:MixDefinition){window.dispatchEvent(new CustomEvent('open-mix-builder',{detail:mix}))}
const labels:Record<string,string>={title:'Title',artist:'Artist',album:'Album',genre:'Genre',format:'Format',year:'Release year',duration:'Duration (seconds)',rating:'Rating (Navidrome)',playCount:'Play count (Navidrome)',favorite:'Favorite'}
function initial():MixDefinition{return {id:crypto.randomUUID(),name:'My new mix',description:'',sources:[],groups:[],match:'all',sort:'random',descending:false,limit:50,artistLimit:0}}
export function MixLauncher(){
  const [edit,setEdit]=useState<MixDefinition>()
  useEffect(()=>{const open=(e:Event)=>setEdit((e as CustomEvent<MixDefinition>).detail??initial());window.addEventListener('open-mix-builder',open);return()=>window.removeEventListener('open-mix-builder',open)},[])
  return edit?<MixEditor key={edit.id} value={edit} close={()=>setEdit(undefined)}/>:null
}
export function MixLibrary({error}:{error:(s:string)=>void}){
  const personal=usePersonal()
  return <section className="mix-library"><div className="section-title"><div><h2>Your custom mixes</h2><p className="muted">Save a recipe. Preview fresh matches whenever you want to listen.</p></div><button className="primary" onClick={()=>openMixBuilder()}><Plus size={16}/>Create mix</button></div>
    {!personal.mixes.length&&<div className="empty-state"><Sparkles/><h3>Start with a sound you love.</h3><p>Combine artists, genres, years and favorites from your music sources.</p></div>}
    <div className="custom-mix-grid">{personal.mixes.map(m=><article className="custom-mix-card" key={m.id}><Sparkles size={25}/><span className="eyebrow">{m.sources.length} SOURCES · UP TO {m.limit} TRACKS</span><h3>{m.name}</h3><p>{m.description||`${m.groups.length} rule groups · ${m.sort==='random'?'Shuffled':`Sorted by ${m.sort}`}`}</p><div className="control-actions"><button className="secondary" onClick={()=>openMixBuilder(m)}>Open mix</button><button className="text-button" onClick={()=>openMixBuilder({...m,id:crypto.randomUUID(),name:m.name+' copy'})}>Duplicate</button><button className="icon-button" aria-label={`Delete mix ${m.name}`} onClick={()=>void api.personalChange({action:'mix-delete',id:m.id}).catch(e=>error(message(e)))}><Trash2 size={16}/></button></div></article>)}</div>
  </section>
}
function MixEditor({value,close}:{value:MixDefinition;close:()=>void}){
  const [facets,setFacets]=useState<{artists:string[];genres:string[]}>({artists:[],genres:[]}),[draft,setDraft]=useState(value),[sources,setSources]=useState<{source:MixSource;name:string}[]>([]),[result,setResult]=useState<MixPreview>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[page,setPage]=useState(0)
  useEffect(()=>{let live=true;void api.mixSources().then(s=>{if(live){setSources(s);if(!value.sources.length&&s[0])setDraft(d=>({...d,sources:[s[0].source]}))}}).catch(e=>{if(live)setError(message(e))});return()=>{live=false}},[])
  const change=(next:MixDefinition)=>{setDraft(next);setResult(undefined);setNotice('');setPage(0)}
  const condition=(g:number,i:number,next:MixCondition)=>change({...draft,groups:draft.groups.map((group,n)=>n===g?{...group,conditions:group.conditions.map((c,j)=>j===i?next:c)}:group)})
  const parsed=()=>{const p=mixDefinitionSchema.safeParse(draft);if(!p.success){setError(p.error.issues[0]?.message??'Check the mix rules.');return}setError('');return p.data}
  const preview=async(refresh=false)=>{const mix=parsed();if(!mix)return;setBusy(true);setNotice('');try{const next=await api.mixPreview({mix,refresh});setResult(next);setFacets(next);setPage(0)}catch(e){setError(message(e))}finally{setBusy(false)}}
  const save=async()=>{const mix=parsed();if(!mix)return;setBusy(true);try{await api.personalChange({action:'mix-save',mix});setNotice('Mix saved. Find it on Home and in Library tools → Custom mixes.')}catch(e){setError(message(e))}finally{setBusy(false)}}
  return <Modal title="Create your mix" close={close}><div className="mix-builder"><p className="muted">Build from real music in your collection. Rules stay on this device; audio and server metadata stay untouched.</p>
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <fieldset disabled={busy} className="mix-definition"><legend className="sr-only">Mix recipe</legend>
      <div className="mix-basics"><label className="field">Mix name<input value={draft.name} maxLength={100} onChange={e=>change({...draft,name:e.target.value})}/></label><label className="field">Description<input value={draft.description} maxLength={1000} onChange={e=>change({...draft,description:e.target.value})}/></label></div>
      <section className="mix-source-panel"><h3>Music sources</h3><p className="muted">Choose Navidrome servers or local folders. Audiobooks and podcasts are excluded.</p><div className="mix-sources">{sources.map(s=><label className="check-field" key={sourceKey(s.source)}><input type="checkbox" checked={draft.sources.some(x=>sourceKey(x)===sourceKey(s.source))} onChange={e=>change({...draft,sources:e.target.checked?[...draft.sources,s.source]:draft.sources.filter(x=>sourceKey(x)!==sourceKey(s.source))})}/>{s.name}</label>)}</div>{!sources.length&&<p>Connect a music server or add a local folder to create a mix.</p>}{draft.sources.some(s=>!sources.some(x=>sourceKey(x.source)===sourceKey(s)))&&<p role="alert">A saved source is disconnected. Remove it below or reconnect it.</p>}{draft.sources.filter(s=>!sources.some(x=>sourceKey(x.source)===sourceKey(s))).map(s=><button className="text-button" key={sourceKey(s)} onClick={()=>change({...draft,sources:draft.sources.filter(x=>sourceKey(x)!==sourceKey(s))})}>Remove unavailable source</button>)}</section>
      <div className="mix-rules-heading"><h3>Rules</h3><label>Match <select aria-label="Match rule groups" value={draft.match} onChange={e=>change({...draft,match:e.target.value as 'all'|'any'})}><option value="all">all groups</option><option value="any">any group</option></select></label></div>
      {!draft.groups.length&&<p className="muted">No rules yet: all music in the selected sources can match.</p>}
      {draft.groups.map((g,gi)=><section className="mix-rule-group" key={gi}><header><strong>Group {gi+1}</strong><select aria-label={`Group ${gi+1} match`} value={g.match} onChange={e=>change({...draft,groups:draft.groups.map((v,i)=>i===gi?{...v,match:e.target.value as typeof g.match}:v)})}><option value="all">All conditions (AND)</option><option value="any">Any condition (OR)</option><option value="none">No conditions (NOT)</option></select><button className="icon-button" aria-label={`Remove group ${gi+1}`} onClick={()=>change({...draft,groups:draft.groups.filter((_,i)=>i!==gi)})}><Trash2 size={16}/></button></header>
        {g.conditions.map((c,ci)=><div className="mix-condition" key={ci}><select aria-label={`Rule ${gi+1}.${ci+1} field`} value={c.type==='favorite'?'favorite':c.field} onChange={e=>{const field=e.target.value;condition(gi,ci,field==='favorite'?{type:'favorite',value:true}:textFields.includes(field as typeof textFields[number])?{type:'text',field:field as typeof textFields[number],operator:'contains',value:''}:{type:'number',field:field as typeof numberFields[number],operator:'atLeast',value:0})}}>{[...textFields,...numberFields,'favorite'].map(f=><option key={f} value={f}>{labels[f]}</option>)}</select>
          {c.type==='favorite'?<select aria-label={`Rule ${gi+1}.${ci+1} value`} value={String(c.value)} onChange={e=>condition(gi,ci,{...c,value:e.target.value==='true'})}><option value="true">is a favorite</option><option value="false">is not a favorite</option></select>:<><select aria-label={`Rule ${gi+1}.${ci+1} operator`} value={c.operator} onChange={e=>condition(gi,ci,{...c,operator:e.target.value} as MixCondition)}>{(c.type==='text'?[['contains','contains'],['equals','is exactly'],['excludes','does not contain']]:[['atLeast','at least'],['atMost','at most'],['equals','equals']]).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input aria-label={`Rule ${gi+1}.${ci+1} value`} type={c.type==='number'?'number':'text'} min={0} max={1000000} maxLength={300} list={c.type==='text'&&['artist','genre'].includes(c.field)?'mix-'+c.field:undefined} value={c.value} onChange={e=>condition(gi,ci,c.type==='number'?{...c,value:Number(e.target.value)}:{...c,value:e.target.value})}/></>}
          <button className="icon-button" disabled={g.conditions.length===1} aria-label={`Remove rule ${gi+1}.${ci+1}`} onClick={()=>change({...draft,groups:draft.groups.map((v,i)=>i===gi?{...v,conditions:v.conditions.filter((_,j)=>j!==ci)}:v)})}><Trash2 size={15}/></button></div>)}
        <button className="text-button" disabled={g.conditions.length>=12} onClick={()=>change({...draft,groups:draft.groups.map((v,i)=>i===gi?{...v,conditions:[...v.conditions,{type:'text',field:'artist',operator:'contains',value:''}]}:v)})}><Plus size={15}/>Add condition</button>
      </section>)}
      <button className="secondary" disabled={draft.groups.length>=8} onClick={()=>change({...draft,groups:[...draft.groups,{match:'all',conditions:[{type:'text',field:'genre',operator:'equals',value:''}]}]})}><Plus size={16}/>Add rule group</button>
      <div className="mix-output"><label className="field">Order<select value={draft.sort} onChange={e=>change({...draft,sort:e.target.value as MixDefinition['sort']})}>{['random','title','artist','album','year','duration','playCount'].map(v=><option key={v} value={v}>{v==='random'?'Shuffle':labels[v]}</option>)}</select></label><label className="field">Track limit<input type="number" min={1} max={1000} value={draft.limit} onChange={e=>change({...draft,limit:Number(e.target.value)})}/></label><label className="field">Maximum per artist (0 = no limit)<input type="number" min={0} max={100} value={draft.artistLimit} onChange={e=>change({...draft,artistLimit:Number(e.target.value)})}/></label>{draft.sort!=='random'&&<label className="check-field"><input type="checkbox" checked={draft.descending} onChange={e=>change({...draft,descending:e.target.checked})}/>Descending order</label>}</div>
    </fieldset>
    <div className="mix-builder-actions"><button className="secondary" disabled={busy} onClick={()=>void preview()}><Sparkles size={16}/>{busy?'Building mix…':'Preview mix'}</button><button className="text-button" disabled={busy} onClick={()=>void preview(true)}><RefreshCw size={15}/>Refresh sources</button><button className="primary" disabled={busy} onClick={()=>void save()}>Save mix</button></div>
    {result&&<section className="mix-preview"><div className="section-title"><div><h3>{result.items.length} tracks · {duration(result.items.reduce((s,t)=>s+(t.duration??0),0))}</h3><p className="muted">{result.matched} matches from {result.scanned} scanned songs</p></div><ListenActions items={result.items} error={setError} disabled={busy||!result.items.length}/></div>{result.warnings.map(w=><p role="alert" key={w}>{w}</p>)}{!result.items.length&&<p>No songs matched. Try fewer conditions or a different source.</p>}{result.items.slice(page*50,(page+1)*50).map((q,i)=><div className="mix-preview-track" key={JSON.stringify(q.target)}><span>{page*50+i+1}</span><TrackArtwork item={q}/><div><strong>{q.title}</strong><small>{q.subtitle} · {q.context}</small></div><span>{duration(q.duration??0)}</span></div>)}{result.items.length>50&&<div className="pagination"><button className="secondary" disabled={!page} onClick={()=>setPage(n=>n-1)}>Previous preview page</button><span>{page+1} / {Math.ceil(result.items.length/50)}</span><button className="secondary" disabled={(page+1)*50>=result.items.length} onClick={()=>setPage(n=>n+1)}>Next preview page</button></div>}</section>}
    <datalist id="mix-artist">{facets.artists.map(a=><option value={a} key={a}/>)}</datalist><datalist id="mix-genre">{facets.genres.map(g=><option value={g} key={g}/>)}</datalist>
    <p className="muted">Preview first to load artist and genre suggestions. Ratings and play counts use Navidrome metadata; missing values do not satisfy numeric rules. Cached catalogs refresh after two minutes, or when you choose Refresh sources.</p>
  </div></Modal>
}
