import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowDown, ArrowUp, Heart, Plus, Search, Trash2 } from 'lucide-react'
import type { Library, MusicDetail, MusicEntity, MusicPage, MusicPlaylist, MusicTrack, MusicView } from '../../shared/types'
import { Art, duration, message, usePageScroll } from './ui'
import { api, ListenActions, Modal, songQueue } from './actions'
const views: [MusicView, string][] = [['albums','Albums'],['newest','Recently added'],['recent','Recently played'],['frequent','Most played'],['songs','Songs'],['artists','Artists'],['playlists','Playlists'],['favorites','Favorites'],['genres','Genres'],['radio','Radio'],['random','Rediscover']]
export function MusicBrowser({ libraries, error, revision }: { libraries: Library[]; error: (s: string) => void; revision: number }) {
  const [libraryId, setLibraryId] = useState(''), [view, setView] = useState<MusicView>('albums'), [search, setSearch] = useState(''), [query, setQuery] = useState(''), [page, setPage] = useState(0), [sort, setSort] = useState('alphabeticalByName'), [genre, setGenre] = useState('')
  const [data, setData] = useState<MusicPage>({ items: [], page: 0, hasMore: false }), [detail, setDetail] = useState<MusicDetail | null>(null), [trail, setTrail] = useState<MusicDetail[]>([]), [busy, setBusy] = useState(false), [refresh, setRefresh] = useState(0), [editing, setEditing] = useState<MusicPlaylist | 'new' | null>(null), [deleting, setDeleting] = useState(false)
  const library = libraries.find(l => `${l.serverId}:${l.id}` === libraryId) ?? libraries[0]
  const request = useRef(0)
  usePageScroll(`${library?.serverId}:${library?.id}:${detail?.kind}:${detail?.album?.id ?? detail?.artist?.id ?? detail?.playlist?.id ?? ''}:${view}:${page}:${query}`)
  useEffect(() => () => { request.current++ }, [library?.serverId, library?.id, view, page, query, sort, genre])
  useEffect(() => { const timer = setTimeout(() => { setQuery(search); setPage(0) }, 300); return () => clearTimeout(timer) }, [search])
  useEffect(() => {
    if (!library) return; let live = true; setBusy(true)
    void api.musicBrowse({ serverId: library.serverId, libraryId: library.id, view, page, search: query, sort, genre: genre || undefined }).then(r => { if (live) setData(r) }).catch(e => { if (live) error(message(e)) }).finally(() => { if (live) setBusy(false) })
    return () => { live = false }
  }, [library?.id, library?.serverId, view, page, query, sort, genre, refresh, revision])
  async function open(item: MusicEntity) {
    if (!library) return
    if (item.kind === 'genre') { setGenre(item.title); setView('albums'); setPage(0); return }
    if (!['album','artist','playlist'].includes(item.kind)) return
    const ticket = ++request.current; setBusy(true); try { const d = await api.musicDetail({ serverId: library.serverId, id: item.id, kind: item.kind as 'album' | 'artist' | 'playlist' }); if (ticket !== request.current) return; if (detail) setTrail(t => [...t, detail]); setDetail(d) } catch (e) { if (ticket === request.current) error(message(e)) } finally { if (ticket === request.current) setBusy(false) }
  }
  async function favorite(item: MusicEntity) {
    if (!library || !['album','artist','music-track'].includes(item.kind)) return
    try { await api.musicFavorite({ serverId: library.serverId, id: item.id, kind: item.kind === 'music-track' ? 'song' : item.kind as 'album' | 'artist', favorite: !('starred' in item && item.starred) }); setRefresh(n => n + 1); if (detail) setDetail({ ...detail, ...(detail.album ? { album: { ...detail.album, starred: !detail.album.starred } } : {}), ...(detail.artist ? { artist: { ...detail.artist, starred: !detail.artist.starred } } : {}) }) } catch (e) { error(message(e)) }
  }
  if (!library) return <div className="empty-state"><h2>Your music belongs here.</h2><p>Connect Navidrome in Settings to browse albums, songs, artists, playlists, and favorites.</p></div>
  return <div className="music-browser"><p className="eyebrow">YOUR OWN FREQUENCY</p><div className="section-title"><h1>{detail ? 'Your music' : 'Your music. All of it.'}</h1><select aria-label="Music library" value={`${library.serverId}:${library.id}`} onChange={e => { setLibraryId(e.target.value); setDetail(null); setTrail([]); setPage(0) }}>{libraries.map(l => <option key={`${l.serverId}:${l.id}`} value={`${l.serverId}:${l.id}`}>{l.name}</option>)}</select></div>
    {!detail && <><div className="browse-tabs">{views.map(([key, label]) => <button key={key} className={`filter ${view === key ? 'active' : ''}`} onClick={() => { setView(key); setPage(0); setGenre('') }}>{label}</button>)}</div><div className="library-toolbar"><label className="search"><Search size={16}/><input aria-label="Search music" value={search} onChange={e => setSearch(e.target.value)} placeholder={`Search ${views.find(v => v[0] === view)?.[1].toLowerCase()}…`}/></label>{view === 'albums' && <select aria-label="Album sort" value={sort} onChange={e => { setSort(e.target.value); setPage(0) }}><option value="alphabeticalByName">Album title</option><option value="alphabeticalByArtist">Album artist</option><option value="byYear">Release year</option><option value="highest">Highest rated</option></select>}{genre && <button className="filter active" onClick={() => setGenre('')}>{genre} ×</button>}{view === 'playlists' && <button className="secondary" onClick={()=>void api.importPlaylist({serverId:library.serverId}).then(()=>{setPage(0);setRefresh(n=>n+1)}).catch(e=>error(message(e)))}>Import playlist</button>}{view === 'playlists' && <button className="primary" onClick={() => setEditing('new')}><Plus size={15}/>New playlist</button>}</div></>}
    {busy && <p role="status" className="muted">Loading your collection…</p>}
    {detail ? <><button className="text-button back" onClick={() => { request.current++; setBusy(false); setDetail(trail.at(-1) ?? null); setTrail(t => t.slice(0,-1)) }}><ArrowLeft size={16}/>Back</button><section className="detail-hero"><Art item={{ id: detail.cover ?? detail.title, serverId: library.serverId, title: detail.title, subtitle: detail.subtitle, kind: detail.kind, cover: detail.cover }}/><div><p className="eyebrow">{detail.kind}</p><h2>{detail.title}</h2><p>{detail.subtitle}</p>{detail.playlist?.comment && <p>{detail.playlist.comment}</p>}<ListenActions items={songQueue(detail.tracks, detail.title)} error={error}/><div className="collection-management">{(detail.album || detail.artist) && <button className="secondary" onClick={() => void favorite((detail.album ?? detail.artist)!)}><Heart size={16} fill={(detail.album?.starred || detail.artist?.starred) ? 'currentColor' : 'none'}/>{detail.album?.starred || detail.artist?.starred ? 'Favorited' : 'Favorite'}</button>}{detail.playlist && <button className="secondary" onClick={()=>void api.exportPlaylist({serverId:library.serverId,id:detail.playlist!.id}).catch(e=>error(message(e)))}>Export playlist</button>}{detail.playlist && !detail.playlist.readonly && <><button className="secondary" onClick={() => setEditing(detail.playlist!)}>Edit playlist</button><button className="secondary danger" onClick={() => setDeleting(true)}>Delete playlist</button></>}</div></div></section>
      {!!detail.albums.length && <div className="media-grid">{detail.albums.map(a => <button className="media-card" key={a.id} onClick={() => void open(a)}><Art item={a}/><div className="card-copy"><strong>{a.title}</strong><span>{a.year} · {a.trackCount} tracks</span></div></button>)}</div>}
      <Tracks key={`${detail.kind}:${detail.title}`} tracks={detail.tracks} serverId={library.serverId} context={detail.title} playlist={detail.playlist?.readonly ? undefined : detail.playlist} error={error} changed={tracks => setDetail(d => d ? { ...d, tracks } : d)}/>
    </> : <>{data.items.some(i => i.kind === 'music-track') && <Tracks tracks={data.items.filter((i): i is MusicTrack => i.kind === 'music-track')} serverId={library.serverId} context={view === 'favorites' ? 'Favorite songs' : query ? `Search: ${query}` : 'Songs'} error={error}/>}
      <div className="media-grid">{data.items.filter(i => i.kind !== 'music-track').map(item => <article className="music-card" key={`${item.kind}:${item.id}`}>
        {item.kind === 'radio' ? <><div className="station-art">◉</div><h3>{item.title}</h3><ListenActions items={[{ target: { kind: 'radio', serverId: library.serverId, stationId: item.id }, title: item.title, subtitle: 'Internet radio' }]} error={error}/></> : <><button className="media-card" onClick={() => void open(item)}>{item.kind !== 'genre' && <Art item={{ ...item, serverId: library.serverId, subtitle: 'subtitle' in item ? item.subtitle : '' }}/>}<div className="card-copy"><strong>{item.title}</strong><span>{item.kind === 'album' ? `${item.subtitle} · ${item.trackCount} tracks` : item.kind === 'artist' ? `${item.albumCount} albums` : item.kind === 'playlist' ? `${item.songCount} tracks · ${duration(item.duration)}` : `${item.albumCount} albums · ${item.songCount} songs`}</span></div></button>{(item.kind === 'album' || item.kind === 'artist') && <button className={`card-favorite icon-button ${item.starred ? 'active' : ''}`} aria-label={`${item.starred ? 'Unfavorite' : 'Favorite'} ${item.title}`} onClick={() => void favorite(item)}><Heart size={17} fill={item.starred ? 'currentColor' : 'none'}/></button>}</>}
      </article>)}</div>{!busy && !data.items.length && <p className="empty-state">No items found in this view.</p>}<div className="pagination"><button className="secondary" disabled={!page || busy} onClick={() => setPage(p => p - 1)}>Previous</button><span>Page {page + 1}{data.total != null ? ` · ${data.total} items` : ''}</span><button className="secondary" disabled={!data.hasMore || busy} onClick={() => setPage(p => p + 1)}>Next</button></div></>}
    {editing && <PlaylistEditor serverId={library.serverId} playlist={editing === 'new' ? undefined : editing} close={() => setEditing(null)} error={error} saved={p => { setEditing(null); setRefresh(r => r + 1); if (detail?.playlist?.id === p.id) setDetail({ ...detail, title: p.title, playlist: p }) }}/>} 
    {deleting && detail?.playlist && <Modal title="Delete playlist?" close={() => setDeleting(false)}><p>This removes “{detail.title}” from Navidrome. The music files remain in your library.</p><button className="primary" onClick={() => void api.playlistDelete({ serverId: library.serverId, id: detail.playlist!.id }).then(() => { setDeleting(false); setDetail(null); setRefresh(r => r + 1) }).catch(e => error(message(e)))}>Delete playlist</button></Modal>}
  </div>
}
function PlaylistEditor({ serverId, playlist, close, saved, error }: { serverId: string; playlist?: MusicPlaylist; close: () => void; saved: (p: MusicPlaylist) => void; error: (s: string) => void }) {
  const [name, setName] = useState(playlist?.title ?? ''), [comment, setComment] = useState(playlist?.comment ?? ''), [isPublic, setPublic] = useState(playlist?.public ?? false), [busy, setBusy] = useState(false)
  return <Modal title={playlist ? 'Edit playlist' : 'New playlist'} close={close}><form onSubmit={e => { e.preventDefault(); setBusy(true); void api.playlistSave({ serverId, id: playlist?.id, name, comment, public: isPublic }).then(saved).catch(e => error(message(e))).finally(() => setBusy(false)) }}><label className="field">Name<input autoFocus required value={name} onChange={e => setName(e.target.value)}/></label><label className="field">Description<textarea value={comment} onChange={e => setComment(e.target.value)}/></label><label className="check-field"><input type="checkbox" checked={isPublic} onChange={e => setPublic(e.target.checked)}/>Public on your server</label><button className="primary" disabled={busy || !name.trim()}>Save playlist</button></form></Modal>
}
export function Tracks({ tracks, serverId, context, playlist, error, changed }: { tracks: MusicTrack[]; serverId: string; context: string; playlist?: MusicPlaylist; error: (s: string) => void; changed?: (tracks: MusicTrack[]) => void }) {
  const [selected, setSelected] = useState<number[]>([]), [list, setList] = useState(tracks), [add, setAdd] = useState(false), [playlists, setPlaylists] = useState<MusicPlaylist[]>([]), [busy, setBusy] = useState(false), [trackPage,setTrackPage]=useState(0)
  useEffect(() => { setList(tracks); setSelected([]) }, [tracks])
  async function update(next: MusicTrack[]) { if (!playlist) return; setBusy(true); try { await api.playlistSave({ serverId, id: playlist.id, name: playlist.title, comment: playlist.comment, public: playlist.public, songIds: next.map(t => t.id) }); setList(next); changed?.(next); setSelected([]) } catch (e) { error(message(e)) } finally { setBusy(false) } }
  async function choosePlaylist() { try { const all: MusicPlaylist[] = []; let page = 0; while (true) { const result = await api.musicBrowse({ serverId, libraryId: 'all', view: 'playlists', page: page++, search: '' }); all.push(...result.items.filter((i): i is MusicPlaylist => i.kind === 'playlist' && !i.readonly)); if (!result.hasMore) break }; setPlaylists(all); setAdd(true) } catch (e) { error(message(e)) } }
  if (!list.length) return null
  const chosen = selected.length ? selected.map(i => list[i]).filter(Boolean) : list
  return <section className="song-section"><div className="section-title"><h2>{playlist ? 'Playlist tracks' : 'Tracks'}</h2><span>{list.length} tracks · {duration(list.reduce((n,t) => n + t.duration,0))}</span></div><div className="selection-bar"><label><input type="checkbox" aria-label="Select all tracks" checked={selected.length === list.length} onChange={e => setSelected(e.target.checked ? list.map((_,i) => i) : [])}/> {selected.length ? `${selected.length} selected` : 'All tracks in this collection'}</label><ListenActions items={songQueue(chosen, context)} error={error} compact/><button className="secondary" onClick={() => void choosePlaylist()}>Add to playlist</button>{playlist && selected.length > 0 && <button disabled={busy} className="text-button danger" onClick={() => void update(list.filter((_,i) => !selected.includes(i)))}>Remove selected</button>}</div>
    <div className="song-table">{list.slice(trackPage*100,(trackPage+1)*100).map((t, offset) => { const i=trackPage*100+offset; return <div className="song-row" key={`${i}:${t.id}`}><input type="checkbox" aria-label={`Select ${t.title}`} checked={selected.includes(i)} onChange={e => setSelected(s => e.target.checked ? [...s,i] : s.filter(n => n !== i))}/><button className="song-title" title="Play from here" onClick={() => void api.play({ queue: songQueue(list, context), index: i }).catch(e => error(message(e)))}><span className="row-number">{String(i + 1).padStart(2,'0')}</span><div><strong>{t.title}</strong><small>{t.artist} · {t.album}</small></div></button><span className="format">{t.codec?.toUpperCase()}{t.sampleRate ? ` · ${t.sampleRate / 1000} kHz` : ''}{t.bitDepth ? ` / ${t.bitDepth}` : ''}</span><span>{duration(t.duration)}</span><button aria-label={`${t.starred ? 'Unfavorite' : 'Favorite'} ${t.title}`} className={`icon-button ${t.starred ? 'active' : ''}`} onClick={() => void api.musicFavorite({ serverId, kind: 'song', id: t.id, favorite: !t.starred }).then(() => setList(l => l.map(x => x.id === t.id ? { ...x, starred: !t.starred } : x))).catch(e => error(message(e)))}><Heart size={16} fill={t.starred ? 'currentColor' : 'none'}/></button><select aria-label={`Rating for ${t.title}`} className="rating" value={t.rating ?? 0} onChange={e => { const rating = Number(e.target.value); void api.musicRate({ serverId, id: t.id, rating }).then(() => setList(l => l.map(x => x.id === t.id ? { ...x, rating } : x))).catch(e => error(message(e))) }}>{[0,1,2,3,4,5].map(n => <option key={n} value={n}>{n ? `${n} ★` : '☆'}</option>)}</select>{playlist && <div className="row-tools"><button className="icon-button" aria-label={`Move ${t.title} up`} disabled={!i || busy} onClick={() => { const n = [...list]; [n[i],n[i-1]] = [n[i-1],n[i]]; void update(n) }}><ArrowUp size={14}/></button><button className="icon-button" aria-label={`Move ${t.title} down`} disabled={i === list.length - 1 || busy} onClick={() => { const n = [...list]; [n[i],n[i+1]] = [n[i+1],n[i]]; void update(n) }}><ArrowDown size={14}/></button><button className="icon-button" aria-label={`Remove ${t.title}`} disabled={busy} onClick={() => void update(list.filter((_,j) => i !== j))}><Trash2 size={14}/></button></div>}</div>})}</div>{list.length>100&&<div className="pagination"><button className="secondary" disabled={!trackPage} onClick={()=>setTrackPage(n=>n-1)}>Previous tracks</button><span>Page {trackPage+1}</span><button className="secondary" disabled={(trackPage+1)*100>=list.length} onClick={()=>setTrackPage(n=>n+1)}>Next tracks</button></div>}
    {add && <Modal title={`Add ${chosen.length} tracks to a playlist`} close={() => setAdd(false)}>{playlists.map(p => <button className="playlist-choice" disabled={busy} key={p.id} onClick={() => { setBusy(true); void api.musicDetail({ serverId, kind: 'playlist', id: p.id }).then(d => api.playlistSave({ serverId, id: p.id, name: p.title, comment: p.comment, public: p.public, songIds: [...d.tracks.map(t => t.id), ...chosen.map(t => t.id)] })).then(() => setAdd(false)).catch(e => error(message(e))).finally(() => setBusy(false)) }}>{p.title}<small>{p.songCount} tracks</small></button>)}{!playlists.length && <p>Create a playlist from the Playlists tab first.</p>}</Modal>}
  </section>
}
