import { CardActions } from './CardActions'
import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, BookmarkPlus, Check, RotateCcw, Play, Search, Trash2 } from 'lucide-react'
import type { Bookmark, ContinueItem, Library, LibraryItem, Page, PlaybackState, PodcastEpisode, Progress, QueueItem, SpokenBrowseInput, SpokenTarget, Audiobook, PodcastShow } from '../../shared/types'
import { bookSorts, podcastSorts, episodeSorts, statuses, filterEpisodes } from '../../shared/catalog'
import { Art, duration, hours, message, plain, usePageScroll } from './ui'
import { api, ListenActions, Modal } from './actions'
const episodeQueue = (e: PodcastEpisode, show: PodcastShow): QueueItem => ({ target: { kind: 'podcast-episode', serverId: e.serverId, showId: e.showId, episodeId: e.id }, title: e.title, subtitle: show.title, cover: show.id, context: show.title, duration: e.duration })
export function ProgressBadge({ progress }: { progress?: Progress }) { return <span className={`progress-badge ${progress?.status ?? 'unplayed'}`}>{progress?.status === 'finished' ? 'Finished' : progress?.status === 'in-progress' ? `In progress · ${Math.round(progress.fraction * 100)}% · ${duration(progress.position)}` : 'Not started'}</span> }
export function SpokenBrowser({ libraries, player, error, revision }: { libraries: Library[]; player: PlaybackState; error: (s: string) => void; revision: number }) {
  const [libraryId, setLibraryId] = useState(''), [search, setSearch] = useState(''), [query, setQuery] = useState(''), [page, setPage] = useState(0), [sort, setSort] = useState('media.metadata.title'), [descending, setDescending] = useState(false), [status, setStatus] = useState<SpokenBrowseInput['status']>('all'), [data, setData] = useState<Page>({ items: [], page: 0, total: 0, hasMore: false }), [detail, setDetail] = useState<Audiobook | PodcastShow | null>(null), [continuing, setContinuing] = useState<ContinueItem[]>([]), [refresh, setRefresh] = useState(0), [busy, setBusy] = useState(false)
  const library = libraries.find(l => `${l.serverId}:${l.id}` === libraryId) ?? libraries[0]
  const request = useRef(0)
  usePageScroll(`${library?.serverId}:${library?.id}:${detail?.id ?? ''}:${page}:${query}`)
  useEffect(() => () => { request.current++ }, [library?.serverId, library?.id, page, query, sort, descending, status])
  useEffect(() => { const timer = setTimeout(() => { setQuery(search); setPage(0) }, 300); return () => clearTimeout(timer) }, [search])
  useEffect(() => {
    if (!library) return; let live = true; setBusy(true)
    void api.spokenBrowse({ library, page, search: query, sort, descending, status }).then(r => { if (live) setData(r) }).catch(e => { if (live) error(message(e)) }).finally(() => { if (live) setBusy(false) })
    void api.spokenContinue({ serverId: library.serverId, libraryId: library.id }).then(r => { if (live) setContinuing(r) }).catch(e => { if (live) error(message(e)) })
    return () => { live = false }
  }, [library?.id, library?.serverId, page, query, sort, descending, status, refresh, revision])
  async function open(item: LibraryItem) { const ticket = ++request.current; setBusy(true); try { const d = await api.detail({ serverId: item.serverId, itemId: item.id }); if (ticket === request.current && d.kind !== 'album') setDetail(d.item) } catch (e) { if (ticket === request.current) error(message(e)) } finally { if (ticket === request.current) setBusy(false) } }
  if (!library) return <div className="empty-state"><h2>A home for every story.</h2><p>Connect Audiobookshelf in Settings. Books and podcast libraries will appear separately.</p></div>
  if (detail) return <SpokenDetail key={detail.id} item={detail} player={player} error={error} refresh={() => void open(detail)} back={() => { request.current++; setDetail(null); setRefresh(n => n + 1) }}/>
  return <div className="spoken-browser"><p className="eyebrow">{library.kind === 'audiobooks' ? 'ONE MORE CHAPTER' : 'STAY CURIOUS'}</p><div className="section-title"><h1>{library.kind === 'audiobooks' ? 'Your bookshelf.' : 'Your shows.'}</h1><select aria-label="Select library" value={`${library.serverId}:${library.id}`} onChange={e => { setLibraryId(e.target.value); setPage(0) }}>{libraries.map(l => <option key={`${l.serverId}:${l.id}`} value={`${l.serverId}:${l.id}`}>{l.name}</option>)}</select></div>
    {!!continuing.length && <section className="continue-section"><div className="section-title"><h2>Continue listening</h2><button className="text-button" onClick={() => setRefresh(n => n + 1)}>Refresh progress</button></div><div className="continue-grid">{continuing.map(c => <article className="resume-card" key={JSON.stringify(c.item.target)}><ProgressBadge progress={c.progress}/><h3 title={c.item.title}>{c.item.title}</h3><p title={c.item.subtitle}>{c.item.subtitle}</p><progress max={1} value={c.progress.fraction}/><CardActions item={c.item} error={error}/></article>)}</div></section>}
    <div className="library-toolbar"><label className="search"><Search size={16}/><input aria-label="Search library" value={search} onChange={e => setSearch(e.target.value)} placeholder={library.kind === 'audiobooks' ? 'Search books or authors…' : 'Search shows…'}/></label><select aria-label="Library sort" disabled={!!query} value={sort} onChange={e => { setSort(e.target.value); setPage(0) }}>{(library.kind === 'audiobooks' ? bookSorts : podcastSorts).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select><button className="filter" disabled={!!query} onClick={() => { setDescending(v => !v); setPage(0) }}>{descending ? 'Descending ↓' : 'Ascending ↑'}</button>{library.kind === 'audiobooks' && <select aria-label="Book status" value={status} onChange={e => { setStatus(e.target.value as typeof status); setPage(0) }}>{statuses.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select>}</div>
    {query && <p className="muted">Search results use Audiobookshelf relevance order, up to 100 matches. Clear search to browse and sort the full library.</p>}
    {busy ? <p role="status">Loading your library…</p> : <div className="media-grid">{data.items.map(item => <button className="media-card" key={item.id} onClick={() => void open(item)}><Art item={item}/><div className="card-copy"><strong>{item.title}</strong><span>{item.subtitle}</span><small>{item.kind === 'audiobook' ? hours(item.duration) : item.kind === 'podcast-show' ? `${item.episodeCount} episodes` : ''}</small>{item.kind === 'audiobook' && <ProgressBadge progress={item.progress}/>}</div></button>)}</div>}
    {!busy && !data.items.length && <p className="empty-state">No items match these filters.</p>}<div className="pagination"><button className="secondary" disabled={!page || busy} onClick={() => setPage(p => p - 1)}>Previous</button><span>Page {page + 1} · {data.total} items</span><button className="secondary" disabled={!data.hasMore || busy} onClick={() => setPage(p => p + 1)}>Next</button></div>
  </div>
}
function StatusControl({ target, progress, error, changed }: { target: SpokenTarget; progress?: Progress; error: (s: string) => void; changed: () => void }) {
  const [busy, setBusy] = useState(false), [reset, setReset] = useState(false)
  async function change(action: 'finished' | 'unfinished' | 'reset') { setBusy(true); try { await api.spokenProgress({ target, action }); setReset(false); changed() } catch (e) { error(message(e)) } finally { setBusy(false) } }
  return <><div className="status-control"><ProgressBadge progress={progress}/><button className="secondary" disabled={busy} onClick={() => void change(progress?.status === 'finished' ? 'unfinished' : 'finished')}><Check size={16}/>{progress?.status === 'finished' ? 'Mark unfinished' : 'Mark finished'}</button><button className="secondary" disabled={busy} onClick={() => setReset(true)}><RotateCcw size={16}/>Reset progress</button></div>{reset && <Modal title="Reset listening progress?" close={() => setReset(false)}><p>This resets this {target.kind === 'audiobook' ? 'book' : 'episode'} to the beginning on Audiobookshelf. Active playback of this item will stop before the update.</p><button className="primary" disabled={busy} onClick={() => void change('reset')}>Reset to beginning</button></Modal>}</>
}
function SpokenDetail({ item, player, error, back, refresh }: { item: Audiobook | PodcastShow; player: PlaybackState; error: (s: string) => void; back: () => void; refresh: () => void }) {
  const [search, setSearch] = useState(''), [status, setStatus] = useState('all'), [sort, setSort] = useState('publishedAt'), [descending, setDescending] = useState(true), [downloaded, setDownloaded] = useState(false), [bookmarks, setBookmarks] = useState<Bookmark[]>([]), [bookmark, setBookmark] = useState(false), [title, setTitle] = useState(''), [time, setTime] = useState(0), [editingBookmark,setEditingBookmark]=useState(false),[episodePage,setEpisodePage]=useState(0)
  const queue: QueueItem[] = item.kind === 'audiobook' ? [{ target: { kind: 'audiobook', serverId: item.serverId, bookId: item.id }, title: item.title, subtitle: item.subtitle, cover: item.id, duration: item.duration }] : []
  const episodes = item.kind === 'podcast-show' ? filterEpisodes(item.episodes, search, status, sort, descending, downloaded) : []
  useEffect(() => { if (item.kind === 'audiobook') void api.spokenBookmarks({ serverId: item.serverId, bookId: item.id }).then(setBookmarks).catch(e => error(message(e))) }, [item])
  useEffect(()=>setEpisodePage(0),[search,status,sort,descending,downloaded,item.id])
  const playAt = (position: number) => void api.play({ queue, index: 0, position }).catch(e => error(message(e)))
  return <div className="detail-page"><button className="text-button back" onClick={back}><ArrowLeft size={16}/>Back to library</button><section className="detail-hero"><Art item={item}/><div><p className="eyebrow">{item.kind === 'audiobook' ? 'AUDIOBOOK' : 'PODCAST SHOW'}</p><h1>{item.title}</h1><p>{item.subtitle}</p>{item.kind === 'audiobook' ? <><p className="muted">Narrated by {item.narrators.join(', ') || 'Unknown narrator'} · {hours(item.duration)}</p><ListenActions items={queue} error={error} disabled={!item.tracks.length}/><StatusControl target={queue[0].target as SpokenTarget} progress={item.progress} error={error} changed={refresh}/></> : <p className="muted">{item.episodeCount} episodes · Independent progress for every episode</p>}</div></section>{item.description && <details className="description"><summary>About {item.kind === 'audiobook' ? 'this book' : 'this show'}</summary><p>{plain(item.description)}</p></details>}
    {item.kind === 'audiobook' ? <><section><div className="section-title"><h2>Chapters</h2><span>{item.chapters.length} chapters · {item.tracks.length} audio files</span></div>{item.chapters.map((c,i) => <button className="chapter-row" key={c.id} onClick={() => playAt(c.start)}><span className="row-number">{String(i+1).padStart(2,'0')}</span><div><strong>{c.title}</strong><small>Starts at {duration(c.start)}</small></div><span>{duration(c.end-c.start)}</span><Play size={15}/></button>)}{!item.chapters.length && <p className="muted">No chapter markers are available for this book.</p>}<details className="files-detail"><summary>Audio files</summary>{item.tracks.map(t => <button className="file-row" key={t.index} onClick={() => playAt(t.startOffset)}><span>{t.title}</span><span>{duration(t.startOffset)} – {duration(t.startOffset+t.duration)}</span></button>)}</details></section>
      <section><div className="section-title"><h2>Bookmarks</h2><button className="secondary" onClick={() => { const target = player.queue[player.queueIndex]?.target; setTime(target?.kind === 'audiobook' && target.bookId === item.id && target.serverId === item.serverId ? Math.floor(player.position) : Math.floor(item.progress?.position ?? 0)); setTitle(''); setEditingBookmark(false); setBookmark(true) }}><BookmarkPlus size={16}/>Add bookmark</button></div>{bookmarks.map(b => <div className="bookmark-row" key={b.time}><button className="text-button" onClick={() => playAt(b.time)}>{duration(b.time)} · {b.title}</button><button className="text-button" onClick={()=>{setTime(b.time);setTitle(b.title);setEditingBookmark(true);setBookmark(true)}}>Edit</button><button className="icon-button" aria-label={`Delete bookmark ${b.title}`} onClick={() => void api.spokenBookmarkDelete({ serverId: item.serverId, bookId: item.id, time: b.time }).then(refresh).catch(e => error(message(e)))}><Trash2 size={15}/></button></div>)}{!bookmarks.length && <p className="muted">Bookmarks are saved to Audiobookshelf and available on your other clients.</p>}</section>
      {bookmark && <Modal title="Bookmark this moment" close={() => setBookmark(false)}><label className="field">Title<input autoFocus value={title} onChange={e => setTitle(e.target.value)}/></label><label className="field">Position in seconds<input type="number" disabled={editingBookmark} min={0} max={item.duration} value={time} onChange={e => setTime(Number(e.target.value))}/></label><button className="primary" disabled={!title.trim() || time < 0 || time > item.duration} onClick={() => void api.spokenBookmarkSave({ serverId: item.serverId, bookId: item.id, time, title, update: editingBookmark }).then(() => { setBookmark(false); refresh() }).catch(e => error(message(e)))}>Save bookmark</button></Modal>}
    </> : <section><div className="section-title"><h2>Episodes</h2><button className="text-button" onClick={refresh}>Refresh progress</button></div><div className="library-toolbar"><label className="search"><Search size={16}/><input aria-label="Search episodes" placeholder="Search episode titles and descriptions…" value={search} onChange={e => setSearch(e.target.value)}/></label><select aria-label="Episode status" value={status} onChange={e => setStatus(e.target.value)}>{statuses.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select><select aria-label="Episode sort" value={sort} onChange={e => setSort(e.target.value)}>{episodeSorts.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select><button className="filter" onClick={() => setDescending(v => !v)}>{descending ? 'Descending ↓' : 'Ascending ↑'}</button><label className="check-field"><input type="checkbox" checked={downloaded} onChange={e => setDownloaded(e.target.checked)}/>Downloaded</label></div><div className="selection-bar"><span>{episodes.length} episodes match · {episodes.filter(e => e.downloaded).length} playable</span><ListenActions items={episodes.filter(e => e.downloaded).map(e => episodeQueue(e,item))} error={error}/></div>
      {episodes.slice(episodePage*60,(episodePage+1)*60).map(ep => <article key={ep.id} className="episode-card"><div className="episode-copy"><p className="eyebrow">{ep.publishedAt ? new Date(ep.publishedAt).toLocaleDateString() : 'Undated'}{ep.season ? ` · Season ${ep.season}` : ''}{ep.episode ? ` · Episode ${ep.episode}` : ''}</p><h3>{ep.title}</h3><p>{plain(ep.description)}</p><span>{duration(ep.duration)} · {ep.downloaded ? 'Ready to play' : 'Not downloaded on server'}</span></div><div className="episode-bottom"><StatusControl target={episodeQueue(ep,item).target as SpokenTarget} progress={ep.progress} error={error} changed={refresh}/><ListenActions items={[episodeQueue(ep,item)]} error={error} disabled={!ep.downloaded}/></div>{ep.progress?.status === 'in-progress' && <progress max={1} value={ep.progress.fraction}/>}</article>)}{episodes.length>60&&<div className="pagination"><button className="secondary" disabled={!episodePage} onClick={()=>setEpisodePage(n=>n-1)}>Previous episodes</button><span>Page {episodePage+1}</span><button className="secondary" disabled={(episodePage+1)*60>=episodes.length} onClick={()=>setEpisodePage(n=>n+1)}>Next episodes</button></div>}{!episodes.length && <p className="empty-state">No episodes match these filters.</p>}
    </section>}
  </div>
}
