import {describe,it,expect,vi} from 'vitest'
vi.mock('electron',()=>({safeStorage:{}}))
import {Store} from '../src/main/store'
import {exportExtra,restoreExtra,personalExtraSchema} from '../src/main/personal-backup'
import {LyricsClient} from '../src/main/lyrics'
import {progressKey} from '../src/shared/timeline'
import {experienceSchema} from '../src/shared/experience'
import type {QueueItem} from '../src/shared/types'
describe('personal data ownership',()=>{
 it('round-trips stats, local lists and lyric matches with new source IDs',()=>{const store=new Store(':memory:'),restored=new Store(':memory:');try{const item:QueueItem={target:{kind:'local-file',serverId:'local',rootId:'old',fileId:'song.wav'},title:'Song',subtitle:'Artist'};store.set('localRoots',[{id:'old',name:'Music',path:'C:/Music'}]);store.set('local-favorites:old',['song.wav']);store.set('local-playlists:old',[{id:'p',name:'Favorites',files:['song.wav','song.wav']}]);store.record(item,10,60);store.recordListening(item,30);new LyricsClient(store).save(progressKey(item.target),{id:42,title:'Song',artist:'Artist',album:'Album',duration:60,status:'found',plain:'Fixture',lines:[{time:0,text:'Fixture'}]});store.set('lyric-offset:'+progressKey(item.target),2);const extra=exportExtra(store);expect(extra.lyrics[0].hash).toHaveLength(64);const {values,stats}=restoreExtra(extra,{servers:new Map(),folders:new Map([['old','new']])},q=>({...q,target:q.target.kind==='local-file'?{...q.target,rootId:'new'}:q.target}));restored.restorePersonal(values,stats);const target={...item.target,rootId:'new'};expect(restored.get('local-favorites:new')).toEqual(['song.wav']);expect(new LyricsClient(restored).saved(progressKey(target))?.id).toBe(42);expect(restored.get('lyric-offset:'+progressKey(target))).toBe(2);expect(restored.listeningStats().totalSeconds).toBe(30);expect(restored.history()[0].item.target).toEqual(target);expect(()=>restoreExtra(extra,{servers:new Map(),folders:new Map()},q=>q)).toThrow()}finally{store.close();restored.close()}})
 it('keeps secrets and originals separate from cache/personal cleanup, fully clears application records on reset',()=>{const store=new Store(':memory:');try{store.set('secret:discord-lastfm','protected');store.set('localRoots',[{id:'r',path:'C:/Music'}]);store.set('preferences',{theme:'glass'});store.set('history',[1]);store.set('local-favorites:r',['song']);store.set('metadata-v2:abc',{});store.cacheSet('lyrics:test',{});store.resetData('cache');expect(store.cache('lyrics:test')).toBeUndefined();expect(store.get('history')).toEqual([1]);expect(store.get('metadata-v2:abc')).toBeUndefined();store.resetData('personal');expect(store.get('history')).toBeUndefined();expect(store.get('local-favorites:r')).toBeUndefined();expect(store.get('secret:discord-lastfm')).toBe('protected');expect(store.get('localRoots')).toBeDefined();store.resetData('all');expect(store.entries('')).toEqual([]);expect(store.connections()).toEqual([])}finally{store.close()}})
 it('rejects invalid shortcut and backup structures',()=>{expect(experienceSchema.safeParse({shortcuts:{search:'Alt+F4'}}).success).toBe(false);expect(experienceSchema.safeParse({homeOrder:['hero','hero']}).success).toBe(false);expect(personalExtraSchema.safeParse({secret:'leak'}).success).toBe(false)})
})
