import { contextBridge, ipcRenderer } from 'electron'
import type { DesktopAPI, PlaybackState, UpdateState } from '../shared/types'

const api: DesktopAPI = {
  lyrics: input=>ipcRenderer.invoke('lyrics:get',input),
  searchLyrics: input=>ipcRenderer.invoke('lyrics:search',input),
  bindLyrics: input=>ipcRenderer.invoke('lyrics:bind',input),
  clearLyrics: input=>ipcRenderer.invoke('lyrics:clear',input),
  seekLyric: input=>ipcRenderer.invoke('lyrics:seek',input),
  correctDiscordArtwork: input => ipcRenderer.invoke('discord:artwork',input),
  offlineProgressPreview: id => ipcRenderer.invoke('offline:preview',id),
  offlineProgressSync: token => ipcRenderer.invoke('offline:sync',token),
  dailySettings: () => ipcRenderer.invoke('daily:get'),
  saveDailySettings: input => ipcRenderer.invoke('daily:save', input),
  home: input => ipcRenderer.invoke('home:get', input),
  podcastInbox: input => ipcRenderer.invoke('inbox:list', input),
  inboxStatus: input => ipcRenderer.invoke('inbox:status', input),
  downloadList: () => ipcRenderer.invoke('downloads:list'),
  downloadAdd: input => ipcRenderer.invoke('downloads:add', input),
  downloadAction: input => ipcRenderer.invoke('downloads:action', input),
  downloadBatch: input => ipcRenderer.invoke('downloads:batch', input),
  savedQueues: () => ipcRenderer.invoke('saved-queues:list'),
  saveQueue: input => ipcRenderer.invoke('saved-queues:save', input),
  loadQueue: input => ipcRenderer.invoke('saved-queues:load', input),
  deleteQueue: input => ipcRenderer.invoke('saved-queues:delete', input),
  notes: () => ipcRenderer.invoke('notes:list'),
  saveNote: input => ipcRenderer.invoke('notes:save', input),
  deleteNote: input => ipcRenderer.invoke('notes:delete', input),
  smartPlaylists: () => ipcRenderer.invoke('rules:list'),
  saveSmartPlaylist: input => ipcRenderer.invoke('rules:save', input),
  runSmartPlaylist: input => ipcRenderer.invoke('rules:run', input),
  deleteSmartPlaylist: input => ipcRenderer.invoke('rules:delete', input),
  exportPlaylist: input => ipcRenderer.invoke('playlist:export', input),
  importPlaylist: input => ipcRenderer.invoke('playlist:import', input),
  listeningRecap: range => ipcRenderer.invoke('recap:get',range),
  exportRecap: input => ipcRenderer.invoke('recap:export',input),
  miniState: () => ipcRenderer.invoke('mini:get'),
  onMiniState: listener => {const cb=(_e:unknown,state:{pinned:boolean})=>listener(state);ipcRenderer.on('mini:state',cb);return()=>ipcRenderer.removeListener('mini:state',cb)},
  onTheme: listener => {const cb=(_e:unknown,theme:import('../shared/types').Preferences)=>listener(theme);ipcRenderer.on('theme:state',cb);return()=>ipcRenderer.removeListener('theme:state',cb)},
  listeningStats: () => ipcRenderer.invoke('stats:get'),
  exportBackup: () => ipcRenderer.invoke('backup:export'),
  previewBackup: () => ipcRenderer.invoke('backup:preview'),
  restoreBackup: input => ipcRenderer.invoke('backup:restore', input),
  miniPlayer: input => ipcRenderer.invoke('mini:command', input),
  discordSettings: () => ipcRenderer.invoke('discord:get'),
  saveDiscordSettings: input => ipcRenderer.invoke('discord:save', input),
  retryDiscordArtwork: () => ipcRenderer.invoke('discord:retry-artwork'),
  discordStatus: () => ipcRenderer.invoke('discord:status'),
  onDownloads: listener => { const callback = (_event: unknown, state: import('../shared/daily').DownloadState) => listener(state); ipcRenderer.on('downloads:state', callback); return () => ipcRenderer.removeListener('downloads:state', callback) },
  updateState: () => ipcRenderer.invoke('updates:get'),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  downloadUpdate: () => ipcRenderer.invoke('updates:download'),
  installUpdate: () => ipcRenderer.invoke('updates:install'),
  onUpdate: listener => { const callback = (_event: unknown, state: UpdateState) => listener(state); ipcRenderer.on('updates:state', callback); return () => ipcRenderer.removeListener('updates:state', callback) },
  musicBrowse: input => ipcRenderer.invoke('music:browse', input),
  musicDetail: input => ipcRenderer.invoke('music:detail', input),
  musicFavorite: input => ipcRenderer.invoke('music:favorite', input),
  musicRate: input => ipcRenderer.invoke('music:rate', input),
  playlistSave: input => ipcRenderer.invoke('playlist:save', input),
  playlistDelete: input => ipcRenderer.invoke('playlist:delete', input),
  spokenBrowse: input => ipcRenderer.invoke('spoken:browse', input),
  spokenProgress: input => ipcRenderer.invoke('spoken:progress', input),
  spokenContinue: input => ipcRenderer.invoke('spoken:continue', input),
  spokenBookmarks: input => ipcRenderer.invoke('spoken:bookmarks', input),
  spokenBookmarkSave: input => ipcRenderer.invoke('spoken:bookmark-save', input),
  spokenBookmarkDelete: input => ipcRenderer.invoke('spoken:bookmark-delete', input),
  queueEdit: input => ipcRenderer.invoke('queue:edit', input),
  localRoots: () => ipcRenderer.invoke('local:roots'),
  localAdd: () => ipcRenderer.invoke('local:add'),
  localRemove: input => ipcRenderer.invoke('local:remove', input),
  localBrowse: input => ipcRenderer.invoke('local:browse', input),
  localCover: input => ipcRenderer.invoke('local:cover', input),
  laterList: () => ipcRenderer.invoke('later:list'),
  laterSave: input => ipcRenderer.invoke('later:save', input),
  laterDelete: input => ipcRenderer.invoke('later:delete', input),
  history: () => ipcRenderer.invoke('history:list'),
  preferences: () => ipcRenderer.invoke('preferences:get'),
  savePreferences: input => ipcRenderer.invoke('preferences:save', input),
  settings: () => ipcRenderer.invoke('settings:get'),
  saveConnection: input => ipcRenderer.invoke('connections:save', input),
  removeConnection: id => ipcRenderer.invoke('connections:remove', id),
  chooseMpv: () => ipcRenderer.invoke('settings:mpv'),
  setAudio: input => ipcRenderer.invoke('settings:audio', input),
  audioDevices: () => ipcRenderer.invoke('audio:devices'),
  libraries: () => ipcRenderer.invoke('libraries:list'),
  browse: input => ipcRenderer.invoke('library:browse', input),
  detail: input => ipcRenderer.invoke('item:detail', input),
  cover: input => ipcRenderer.invoke('item:cover', input),
  play: input => ipcRenderer.invoke('player:play', input),
  command: command => ipcRenderer.invoke('player:command', command),
  seekPlayback: (input) => ipcRenderer.invoke('player:seek', input),
  playingScreenPreferences: () => ipcRenderer.invoke('playing-screen:get'),
  savePlayingScreenPreferences: (input) => ipcRenderer.invoke('playing-screen:save', input),
  playback: () => ipcRenderer.invoke('player:get'),
  onPlayback: listener => { const callback = (_event: unknown, state: PlaybackState) => listener(state); ipcRenderer.on('player:state', callback); return () => ipcRenderer.removeListener('player:state', callback) }
}
contextBridge.exposeInMainWorld('mediaCenter', api)
