import { contextBridge, ipcRenderer } from 'electron'
import type { DesktopAPI, PlaybackState, UpdateState } from '../shared/types'

const api: DesktopAPI = {
  updateState: () => ipcRenderer.invoke('updates:get'),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  downloadUpdate: () => ipcRenderer.invoke('updates:download'),
  installUpdate: () => ipcRenderer.invoke('updates:install'),
  onUpdate: listener => { const callback = (_event: unknown, state: UpdateState) => listener(state); ipcRenderer.on('updates:state', callback); return () => ipcRenderer.removeListener('updates:state', callback) },
  musicBrowse: input => ipcRenderer.invoke('music:browse', input),
  musicDetail: input => ipcRenderer.invoke('music:detail', input),
  musicFavorite: input => ipcRenderer.invoke('music:favorite', input),
  musicRate: input => ipcRenderer.invoke('music:rate', input),
  playlistSave: input => ipcRenderer.invoke('playlist:save', input),
  playlistDelete: input => ipcRenderer.invoke('playlist:delete', input),
  spokenBrowse: input => ipcRenderer.invoke('spoken:browse', input),
  spokenProgress: input => ipcRenderer.invoke('spoken:progress', input),
  spokenContinue: input => ipcRenderer.invoke('spoken:continue', input),
  spokenBookmarks: input => ipcRenderer.invoke('spoken:bookmarks', input),
  spokenBookmarkSave: input => ipcRenderer.invoke('spoken:bookmark-save', input),
  spokenBookmarkDelete: input => ipcRenderer.invoke('spoken:bookmark-delete', input),
  queueEdit: input => ipcRenderer.invoke('queue:edit', input),
  localRoots: () => ipcRenderer.invoke('local:roots'),
  localAdd: () => ipcRenderer.invoke('local:add'),
  localRemove: input => ipcRenderer.invoke('local:remove', input),
  localBrowse: input => ipcRenderer.invoke('local:browse', input),
  localCover: input => ipcRenderer.invoke('local:cover', input),
  laterList: () => ipcRenderer.invoke('later:list'),
  laterSave: input => ipcRenderer.invoke('later:save', input),
  laterDelete: input => ipcRenderer.invoke('later:delete', input),
  history: () => ipcRenderer.invoke('history:list'),
  preferences: () => ipcRenderer.invoke('preferences:get'),
  savePreferences: input => ipcRenderer.invoke('preferences:save', input),
  settings: () => ipcRenderer.invoke('settings:get'),
  saveConnection: input => ipcRenderer.invoke('connections:save', input),
  removeConnection: id => ipcRenderer.invoke('connections:remove', id),
  chooseMpv: () => ipcRenderer.invoke('settings:mpv'),
  setAudio: input => ipcRenderer.invoke('settings:audio', input),
  audioDevices: () => ipcRenderer.invoke('audio:devices'),
  libraries: () => ipcRenderer.invoke('libraries:list'),
  browse: input => ipcRenderer.invoke('library:browse', input),
  detail: input => ipcRenderer.invoke('item:detail', input),
  cover: input => ipcRenderer.invoke('item:cover', input),
  play: input => ipcRenderer.invoke('player:play', input),
  command: command => ipcRenderer.invoke('player:command', command),
  playback: () => ipcRenderer.invoke('player:get'),
  onPlayback: listener => { const callback = (_event: unknown, state: PlaybackState) => listener(state); ipcRenderer.on('player:state', callback); return () => ipcRenderer.removeListener('player:state', callback) }
}
contextBridge.exposeInMainWorld('mediaCenter', api)
