import type { PodcastEpisode, Progress } from './types'
export const bookSorts = [['media.metadata.title', 'Title'], ['media.metadata.authorName', 'Author: first, last'], ['media.metadata.authorNameLF', 'Author: last, first'], ['media.metadata.publishedYear', 'Publication year'], ['addedAt', 'Date added'], ['size', 'File size'], ['media.duration', 'Duration'], ['birthtimeMs', 'File created'], ['mtimeMs', 'File modified'], ['progress', 'Listening progress'], ['progress.createdAt', 'Started listening'], ['progress.finishedAt', 'Finished listening'], ['random', 'Random']] as const
export const podcastSorts = [['media.metadata.title', 'Title'], ['media.metadata.author', 'Author'], ['addedAt', 'Date added'], ['size', 'File size'], ['media.numTracks', 'Episode count'], ['birthtimeMs', 'File created'], ['mtimeMs', 'File modified'], ['random', 'Random']] as const
export const episodeSorts = [['publishedAt', 'Publication date'], ['title', 'Title'], ['season', 'Season'], ['episode', 'Episode number'], ['filename', 'Filename'], ['duration', 'Duration'], ['progress', 'Listening progress']] as const
export const statuses = [['all', 'All statuses'], ['unplayed', 'Not started'], ['in-progress', 'In progress'], ['unfinished', 'Unfinished'], ['finished', 'Finished']] as const
export function statusMatches(progress: Progress | undefined, status: string) { const state = progress?.status ?? 'unplayed'; return status === 'all' || status === state || (status === 'unfinished' && state !== 'finished') }
export function filterEpisodes(episodes: PodcastEpisode[], search: string, status: string, sort: string, descending: boolean, downloaded: boolean): PodcastEpisode[] {
  const query = search.trim().toLocaleLowerCase()
  const value = (e: PodcastEpisode): string | number => sort === 'progress' ? e.progress?.fraction ?? 0 : sort === 'duration' ? e.duration : sort === 'publishedAt' ? e.publishedAt ?? 0 : sort === 'season' ? e.season ?? '' : sort === 'episode' ? e.episode ?? '' : sort === 'filename' ? e.filename ?? '' : e.title
  const compare = (a: string | number, b: string | number) => typeof a === 'number' && typeof b === 'number' ? a - b : String(a).localeCompare(String(b), undefined, { numeric: true, sensitivity: 'base' })
  return episodes.filter(e => statusMatches(e.progress, status) && (!downloaded || e.downloaded) && (!query || `${e.title} ${e.subtitle ?? ''} ${e.description} ${e.filename ?? ''}`.toLocaleLowerCase().includes(query))).sort((a, b) => ((compare(value(a), value(b)) || (sort === 'season' ? compare(a.episode ?? '', b.episode ?? '') : 0) || (a.publishedAt ?? 0) - (b.publishedAt ?? 0) || a.id.localeCompare(b.id)) * (descending ? -1 : 1)))
}
