import {dialog,type BrowserWindow} from 'electron'
import {readFile,writeFile,stat} from 'node:fs/promises'
import {extname,join} from 'node:path'
import {z} from 'zod'
import {personalStateSchema,personalCommandSchema,mediaRefSchema,personalItemSchema,mediaKey,targetKey,showKey,showPreferenceSchema,type MediaRef,type PersonalState,type OfflineCheck,type PersonResult} from '../shared/personal-library'
import {changePersonal} from '../shared/personal-state'
import type {QueueItem} from '../shared/types'
import type {Handle} from './features'
import type {Store} from './store'
import type {Player} from './player'
import type {LocalFiles} from './local'
import {Downloads,downloadSource} from './downloads'
import {Navidrome} from './providers/navidrome'
import {Audiobookshelf} from './providers/audiobookshelf'
import {CoverSearch,artworkData} from './cover-search'
export function getPersonal(store:Store):PersonalState{return personalStateSchema.parse(store.get('personal-library')??{})}
export function registerPersonal(handle:Handle,store:Store,player:Player,local:LocalFiles,downloads:Downloads,provider:(id:string)=>Navidrome|Audiobookshelf,window:()=>BrowserWindow,changed:()=>void){
 const key=z.string().min(1).max(10000),keyInput=z.object({key}).strict(),search=new CoverSearch()
 const saveCover=(key:string,image:string)=>{const used=store.entries('personal-cover:').filter(r=>r.key!=='personal-cover:'+key&&typeof r.value==='string').reduce((n,r)=>n+(r.value as string).length,0);if(used+image.length>18*1024*1024)throw Error('Custom artwork storage is full (18 MB). Remove an unused cover first.');if(store.entries('personal-cover:').filter(r=>r.value).length>=250&&!store.get('personal-cover:'+key))throw Error('Remove unused covers first (250 custom covers maximum).');store.set('personal-cover:'+key,image);store.set('personal-cover-source:'+key,null);changed()}
 async function resolve(refs:MediaRef[]):Promise<QueueItem[]>{const result:QueueItem[]=[];for(const r of refs){if(r.kind==='playable')result.push(r.item);else{const p=provider(r.serverId);if(r.kind==='podcast-show'){if(!(p instanceof Audiobookshelf))throw Error('This show requires Audiobookshelf.');const detail=await p.detail(r.id);if(detail.kind!=='podcast-show')throw Error('This item is not a podcast show.');const prefs=showPreferenceSchema.parse(getPersonal(store).shows[showKey(r.serverId,r.id)]??{});const episodes=[...detail.episodes].filter(e=>e.downloaded&&e.progress?.status!=='finished').sort((a,b)=>(prefs.order==='newest'?-1:1)*((a.publishedAt??0)-(b.publishedAt??0)));result.push(...episodes.map(e=>({target:{kind:'podcast-episode' as const,serverId:r.serverId,showId:r.id,episodeId:e.id},title:e.title,subtitle:detail.title,cover:detail.cover??detail.id,duration:e.duration})))}else{if(!(p instanceof Navidrome))throw Error('This collection requires Navidrome.');const detail=await p.collection(r.kind,r.id);let tracks=detail.tracks;if(r.kind==='artist'){tracks=[];if(detail.albums.length>50)throw Error('Choose individual albums for artists with more than 50 albums.');for(const a of detail.albums)tracks.push(...(await p.collection('album',a.id)).tracks)}result.push(...tracks.map(t=>({target:{kind:'music-track' as const,serverId:r.serverId,trackId:t.id},title:t.title,subtitle:t.artist,cover:t.cover,duration:t.duration,context:r.title})))}}if(result.length>1000)throw Error('Choose a smaller selection (1,000 tracks or episodes maximum).')}return result.filter((q,i,a)=>a.findIndex(x=>targetKey(x.target)===targetKey(q.target))===i)}
 handle('personal:default-cover-export',z.undefined(),async()=>{const result=await dialog.showSaveDialog(window(),{title:'Export default Discord artwork',defaultPath:'media_center_default.png',filters:[{name:'PNG image',extensions:['png']}]});if(result.canceled||!result.filePath)return false;await writeFile(result.filePath,await readFile(join(__dirname,'../renderer/assets/default-cover.png')));return true})
 handle('personal:metadata',mediaRefSchema,async ref=>{
  if(ref.kind==='playable'){const t=ref.item.target;if(t.kind==='local-file'){const f=await local.metadata(t.rootId,t.fileId);return {title:f.title,artist:f.artist,album:f.album,genre:f.genre,year:f.year}}const p=provider(t.serverId);if(t.kind==='music-track'&&p instanceof Navidrome){const f=await p.track(t.trackId);return {title:f.title,artist:f.artist,album:f.album,genre:f.genre,year:f.year}}if(t.kind==='audiobook'&&p instanceof Audiobookshelf){const b=await p.detail(t.bookId);if(b.kind!=='audiobook')throw Error('This item is not an audiobook.');return {title:b.title,author:b.authors.join(', '),narrator:b.narrators.join(', '),description:b.description}}return {title:ref.item.title,author:ref.item.subtitle}}
  const p=provider(ref.serverId);if(ref.kind==='podcast-show'&&p instanceof Audiobookshelf){const show=await p.detail(ref.id);if(show.kind!=='podcast-show')throw Error('This item is not a podcast show.');return {title:show.title,author:show.author,description:show.description}}if(ref.kind!=='podcast-show'&&p instanceof Navidrome){const d=await p.collection(ref.kind,ref.id);return {title:d.title,artist:d.album?.subtitle,genre:d.album?.genre,year:d.album?.year,description:d.artist?.description??d.playlist?.comment??d.album?.description}}return {title:ref.title}
 })
 handle('personal:get',z.undefined(),()=>getPersonal(store))
 handle('personal:change',personalCommandSchema,i=>{store.set('personal-library',changePersonal(getPersonal(store),i));player.refreshPersonal();changed()})
 handle('personal:resolve',z.array(mediaRefSchema).max(100),resolve)
 handle('personal:cover',keyInput,i=>store.get<string>('personal-cover:'+i.key)??null)
 handle('personal:cover-remove',keyInput,i=>{store.set('personal-cover:'+i.key,null);store.set('personal-cover-source:'+i.key,null);changed()})
 handle('personal:cover-import',keyInput,async i=>{const result=await dialog.showOpenDialog(window(),{title:'Choose cover art',filters:[{name:'Artwork',extensions:['png','jpg','jpeg']}],properties:['openFile']});if(result.canceled)return false;const path=result.filePaths[0];if(!['.png','.jpg','.jpeg'].includes(extname(path).toLowerCase())||(await stat(path)).size>5*1024*1024)throw Error('Choose a PNG or JPEG up to 5 MB.');saveCover(i.key,artworkData(await readFile(path)));return true})
 handle('personal:cover-search',z.string().trim().min(2).max(250),q=>search.search(q))
 handle('personal:cover-preview',z.string().uuid(),id=>search.preview(id))
 handle('personal:cover-select',z.object({key,id:z.string().uuid()}).strict(),async i=>{saveCover(i.key,(await search.preview(i.id)).image!);store.set('personal-cover-source:'+i.key,`https://coverartarchive.org/release/${i.id}/front-500`);changed()})
 handle('personal:private',z.boolean(),enabled=>player.setPrivateListening(enabled))
 handle('personal:offline',z.array(personalItemSchema).min(1).max(1000),async items=>{const snapshot=downloads.snapshot(),result:OfflineCheck={items:[],knownBytes:0,unknownSizes:0,ready:0,total:items.length,freeBudget:Math.max(0,snapshot.limitBytes-snapshot.usedBytes)};for(const item of items){let status='Missing',bytes=0,unknown=false,error:string|undefined;try{if(item.target.kind==='local-file'){bytes=(await stat(await local.path(item.target.rootId,item.target.fileId))).size;status='Ready'}else if(item.target.kind==='radio'){status='Live only';error='Radio streams cannot be prepared offline.'}else{const existing=snapshot.entries.find(e=>targetKey(e.item.target)===targetKey(item.target));if(existing?.status==='ready'){const ready=await downloads.ready(item.target);if(ready){status='Ready';bytes=existing.total||existing.bytes}}else if(existing){status=existing.status;bytes=existing.total;error=existing.error}else{const source=await downloadSource(item,provider(item.target.serverId));bytes=source.files.reduce((n,f)=>n+f.size,0);unknown=source.files.some(f=>f.size<=0)}}}catch(e){error=e instanceof Error?e.message:'Could not verify media';status='Needs attention'}if(status==='Ready')result.ready++;if(bytes)result.knownBytes+=bytes;if(!bytes||unknown)result.unknownSizes++;result.items.push({item,status,bytes,error})}return result})
 handle('personal:people',z.object({query:z.string().trim().min(2).max(200),role:z.enum(['artist','author','narrator'])}).strict(),async input=>{const items:PersonResult[]=[],warnings:string[]=[];for(const connection of store.connections()){try{const p=provider(connection.id);const libraries=await p.libraries();for(const library of libraries){if(input.role==='artist'&&p instanceof Navidrome&&library.kind==='music'){const page=await p.catalog({serverId:connection.id,libraryId:library.id,view:'artists',page:0,search:input.query});for(const a of page.items)if(a.kind==='artist')items.push({role:'artist',name:a.title,ref:{kind:'artist',serverId:connection.id,id:a.id,title:a.title,subtitle:`${a.albumCount} albums`,cover:a.cover}});if(page.hasMore)warnings.push(`${library.name}: refine your search to see more artists.`)}else if(input.role!=='artist'&&p instanceof Audiobookshelf&&library.kind==='audiobooks'){for(let page=0;page<10;page++){const result=await p.catalog({library,page,search:'',sort:'media.metadata.title',descending:false,status:'all'});for(const book of result.items){if(book.kind!=='audiobook')continue;const names=input.role==='author'?book.authors:book.narrators;for(const name of names)if(name.toLocaleLowerCase().includes(input.query.toLocaleLowerCase()))items.push({role:input.role,name,ref:{kind:'playable',item:{target:{kind:'audiobook',serverId:book.serverId,bookId:book.id},title:book.title,subtitle:book.subtitle,cover:book.cover??book.id,duration:book.duration}}})}if(!result.hasMore)break;if(page===9)warnings.push(`${library.name}: showing matches from the first 10 pages.`)}}}}catch{warnings.push(`${connection.name}: could not search this server.`)}}return {items,warnings}})
}
