const assert=require('node:assert/strict');const {resolve}=require('node:path');const {writeFileSync}=require('node:fs')
module.exports=async({desktop,page,artifacts})=>{
 console.log('Checking consolidated collection actions, top-layer menus, saved queues and independent scrolling')
 await page.setViewportSize({width:1440,height:940})
 const fixture=await page.evaluate(async()=>{const a=window.mediaCenter,nav=(await a.libraries()).libraries.find(l=>l.kind==='music');await a.playlistSave({serverId:nav.serverId,name:'Consistency fixture',comment:'',public:false,songIds:['song']});return {nav}})
 await page.getByRole('button',{name:'Music',exact:true}).click();await page.getByRole('button',{name:'Playlists',exact:true}).last().click();await page.getByRole('button',{name:/Consistency fixture/}).click()
 const header=page.locator('.detail-heading');assert.equal(await page.locator('.collection-extra-tools').count(),0);assert.equal(await page.locator('.library-view-actions .personal-actions').count(),0)
 await header.getByRole('button',{name:'More options',exact:true}).click();const menu=page.locator('.more-options-panel:popover-open');await menu.waitFor();assert.equal(await menu.getByRole('button',{name:'Add to shelf',exact:true}).count(),1)
 assert.ok(await menu.evaluate(el=>{const r=el.getBoundingClientRect(),hit=document.elementFromPoint(r.x+12,r.bottom-12);return el.contains(hit)}),'Menu covers all underlying controls')
 assert.equal(await menu.evaluate(el=>getComputedStyle(el).backdropFilter),'none');await page.evaluate(()=>{window.__menuTheme=document.documentElement.dataset.theme;delete document.documentElement.dataset.theme;document.documentElement.dataset.translucency='false'});assert.ok(await menu.evaluate(el=>{const c=getComputedStyle(el);return c.backgroundImage!=='none'&&c.backgroundColor==='rgb(17, 17, 17)'}),'Menu paints a solid fallback even when theme background variables are missing');await page.evaluate(()=>document.documentElement.dataset.theme='monochrome');assert.ok(await menu.evaluate(el=>getComputedStyle(el).backgroundImage!=='none'));await page.screenshot({path:resolve(artifacts,'opaque-more-menu-page.png')});await menu.screenshot({path:resolve(artifacts,'opaque-more-menu.png')});await page.evaluate(()=>{document.documentElement.dataset.theme=window.__menuTheme})
 await menu.getByRole('button',{name:'Customize details & cover',exact:true}).click();const custom=page.getByRole('dialog',{name:'Make it yours',exact:true});await custom.waitFor();assert.equal(await page.locator(':popover-open').count(),0)
 await custom.getByRole('tab',{name:'Generate cover',exact:true}).click();await custom.getByRole('button',{name:'Generate collage',exact:true}).click();await custom.locator('.cover-preview img').waitFor();assert.ok(await custom.locator('.cover-preview img').evaluate(el=>Math.abs(el.getBoundingClientRect().width-el.getBoundingClientRect().height)<2),'Generated preview stays square');await custom.getByRole('button',{name:'Save playlist cover',exact:true}).click();await custom.getByText('Playlist cover saved.',{exact:true}).waitFor();assert.equal(await page.getByRole('dialog').count(),1);await custom.screenshot({path:resolve(artifacts,'playlist-customization-integrated.png')});await custom.getByRole('button',{name:'Close dialog',exact:true}).click()
 for(const section of ['Audiobooks','Podcasts']){
  await page.getByRole('button',{name:section,exact:true}).click();await page.locator('.spoken-browser .media-card').first().click();assert.equal(await page.locator('.collection-extra-tools').count(),0)
  await page.locator('.detail-heading').getByRole('button',{name:'More options',exact:true}).click();await page.locator(':popover-open').getByRole('button',{name:'Customize details & cover',exact:true}).waitFor();await page.keyboard.press('Escape')
  if(section==='Podcasts'){
   const card=page.locator('.episode-card').first();assert.equal(await card.locator('.listen-actions').count(),1);assert.equal(await card.getByRole('button',{name:'Mark finished',exact:true}).count(),0)
   for(const width of [1008,1440]){await page.setViewportSize({width,height:940});await card.scrollIntoViewIfNeeded();const buttons=await card.locator('.episode-bottom>.listen-actions>button,.episode-bottom>.listen-actions>.more-options').evaluateAll(els=>els.map(el=>el.getBoundingClientRect().y));assert.ok(Math.max(...buttons)-Math.min(...buttons)<2,'Episode actions stay in one row');await card.getByRole('button',{name:'More options',exact:true}).click();await page.locator(':popover-open').getByRole('button',{name:'Reset progress',exact:true}).click();const confirm=page.getByRole('dialog',{name:'Reset listening progress?',exact:true});await confirm.waitFor();await confirm.getByRole('button',{name:'Close dialog',exact:true}).click();if(await page.getByRole('button',{name:'Dismiss undo notification',exact:true}).isVisible())await page.getByRole('button',{name:'Dismiss undo notification',exact:true}).click();await card.screenshot({path:resolve(artifacts,`episode-actions-consistent-${width}.png`)})}
  }
  await page.locator('.workspace').evaluate(el=>el.scrollTop=0);await page.screenshot({path:resolve(artifacts,`collection-consistent-${section}.png`)})
 }
 await page.evaluate(async()=>{const a=window.mediaCenter,root=(await a.localRoots())[0],tracks=(await a.localLibrary({rootId:root.id,view:'songs',page:0,search:''})).tracks;await a.play({queue:Array.from({length:80},(_,i)=>({target:{kind:'local-file',serverId:'local',rootId:root.id,fileId:tracks[0].id},title:'Scroll fixture '+i,subtitle:'Fixture artist'})),index:0});await a.command({action:'toggle'})})
 await page.getByRole('button',{name:'Open now playing',exact:true}).click();await page.locator('.expanded-player').waitFor()
 for(const width of [1008,1440]){await page.setViewportSize({width,height:940});const before=await page.locator('.expanded-art').boundingBox();await page.locator('.now-content').evaluate(el=>el.scrollTop=600);const after=await page.locator('.expanded-art').boundingBox();assert.ok(Math.abs(before.y-after.y)<1,'Artwork stays fixed');assert.ok(await page.locator('.now-content').evaluate(el=>el.scrollTop>0),'Queue scrolls independently');await page.locator('.now-content').evaluate(el=>el.scrollTop=0)}
 const saved=page.locator('.saved-queues');await saved.locator('summary').click();await saved.getByLabel('Saved queue name',{exact:true}).fill('Queue layout fixture');await saved.getByRole('button',{name:'Save current queue',exact:true}).click();const row=saved.locator('.saved-queue-row').filter({hasText:'Queue layout fixture'});await row.waitFor();if(await page.getByRole('button',{name:'Dismiss undo notification',exact:true}).isVisible())await page.getByRole('button',{name:'Dismiss undo notification',exact:true}).click();await page.screenshot({path:resolve(artifacts,'saved-queues-consistent.png')});await row.getByRole('button',{name:'More options',exact:true}).click();await row.getByRole('button',{name:'Load queue',exact:true}).click();await row.getByRole('button',{name:'More options',exact:true}).click();await row.getByRole('button',{name:'Delete saved queue Queue layout fixture',exact:true}).click();await row.waitFor({state:'hidden'})
 await page.getByRole('button',{name:'Close now playing',exact:true}).click()
 writeFileSync(resolve(artifacts,'consistency-smoke.json'),JSON.stringify({passed:true,checks:['top-layer menu hit testing','single customization dialog with generated cover','book/show header actions','episode action row and reset dialog','fixed artwork with independent queue scrolling','save/load/delete queues']},null,2))
 console.log('Collection consistency checks passed')
}

