const assert=require('node:assert/strict')
const {resolve}=require('node:path')
module.exports=async({desktop,page,artifacts})=>{
 await page.getByRole('button',{name:'Settings',exact:true}).click()
 const color=page.getByLabel('Accent color',{exact:true})
 await color.evaluate(el=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'#5588cc');el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))})
 await page.getByLabel('Interface font',{exact:true}).selectOption('verdana')
 await page.getByLabel('Heading font',{exact:true}).selectOption('trebuchet')
 await page.getByLabel('Lyrics font',{exact:true}).selectOption('georgia')
 await page.getByRole('button',{name:'Preview in app',exact:true}).click()
 await page.waitForFunction(()=>document.documentElement.style.getPropertyValue('--accent')==='#5588cc')
 await page.locator('.appearance-editor').screenshot({path:resolve(artifacts,'custom-appearance.png')})
 await page.getByRole('button',{name:'Save audio preferences',exact:true}).click()
 await page.waitForFunction(async()=>(await window.mediaCenter.preferences()).appearance?.bodyFont==='verdana')
 await page.evaluate(()=>window.mediaCenter.miniPlayer({action:'open'}))
 const mini=desktop.windows().find(w=>w!==page)||await desktop.waitForEvent('window')
 await mini.waitForFunction(()=>document.documentElement.style.getPropertyValue('--accent')==='#5588cc')
 assert.ok((await mini.evaluate(()=>getComputedStyle(document.body).fontFamily)).includes('Verdana'))
 await page.getByRole('button',{name:'Reset customization',exact:true}).click()
 await page.getByRole('button',{name:'Save audio preferences',exact:true}).click()
 await mini.waitForFunction(()=>document.documentElement.style.getPropertyValue('--accent')==='')
 await page.getByLabel('Interface font',{exact:true}).selectOption('verdana')
 await page.getByLabel('Lyrics font',{exact:true}).selectOption('georgia')
 await page.getByRole('button',{name:'Save audio preferences',exact:true}).click()
 await mini.waitForFunction(()=>getComputedStyle(document.body).fontFamily.includes('Verdana'))
 await mini.getByRole('button',{name:'Close mini player',exact:true}).click()
 const state=await page.evaluate(()=>window.mediaCenter.playback()),target=state.queue[0].target,key=JSON.stringify(['local',target.rootId,target.fileId])
 await desktop.evaluate(()=>{globalThis.__customFetch=globalThis.fetch;globalThis.fetch=async(input,options)=>{const url=new URL(String(input));if(url.hostname!=='lrclib.net')return globalThis.__customFetch(input,options);const data={id:Number(url.pathname.split('/').at(-1)),trackName:'Saved local lyrics',artistName:'Fixture',albumName:'',duration:3,instrumental:false,plainLyrics:'Locally bound fixture lyrics',syncedLyrics:'[00:00.00]Locally bound fixture lyrics'};if(data.id===43)return new Promise(resolve=>{globalThis.__finishLyrics=()=>resolve(new Response(JSON.stringify(data)))});return new Response(JSON.stringify(data))}})
 try{
  await page.evaluate(key=>window.mediaCenter.bindLyrics({key,id:42}),key)
  assert.equal((await page.evaluate(()=>window.mediaCenter.lyrics({}))).recordId,42,'Local bindings work without artist tags')
  await page.evaluate(key=>{window.__pendingBind=window.mediaCenter.bindLyrics({key,id:43}).then(()=>false,()=>true)},key)
  for(let i=0;i<100;i++){if(await desktop.evaluate(()=>!!globalThis.__finishLyrics))break;await new Promise(r=>setTimeout(r,50))}
  assert.equal(await desktop.evaluate(()=>!!globalThis.__finishLyrics),true)
  await page.evaluate(()=>window.mediaCenter.queueEdit({action:'clear'}))
  await desktop.evaluate(()=>globalThis.__finishLyrics())
  assert.equal(await page.evaluate(()=>window.__pendingBind),true,'A pending bind cannot attach after playback is cleared')
  await page.evaluate(async queue=>{await window.mediaCenter.play({queue,index:0});await window.mediaCenter.command({action:'stop'})},state.queue)
  assert.equal((await page.evaluate(()=>window.mediaCenter.lyrics({}))).recordId,42,'Rejected bind preserves earlier choice')
 }finally{await desktop.evaluate(()=>{globalThis.fetch=globalThis.__customFetch;delete globalThis.__customFetch;delete globalThis.__finishLyrics})}
 console.log('Customization: colors, fonts, reset, mini sync, local lyric binding and stale binding guard passed.')
}
