const assert = require('node:assert/strict')
const {resolve} = require('node:path')
const {readFileSync,writeFileSync} = require('node:fs')
module.exports = async function dailySmoke({desktop,page,waitPlayback,artifacts}) {
  const settings=await page.evaluate(()=>window.mediaCenter.settings()),abs=settings.connections.find(c=>c.provider==='audiobookshelf')
  const original=await page.evaluate(()=>window.mediaCenter.playback()),local=original.queue[0]
  await page.evaluate(async()=>{const s=await window.mediaCenter.dailySettings();await window.mediaCenter.saveDailySettings({...s,gapless:true})})
  await page.evaluate(q=>window.mediaCenter.play({queue:[q,{...q,title:'Gapless second'}, {...q,title:'Gapless third'}],index:0}),local)
  await waitPlayback(p=>p.queueIndex===1 && p.status==='playing')
  await page.evaluate(()=>window.mediaCenter.command({action:'toggle'}))
  console.log('Daily checks: native MPV gapless transition passed.')
  await page.evaluate(()=>window.mediaCenter.saveQueue({name:'Daily QA queue'}))
  const saved=await page.evaluate(()=>window.mediaCenter.savedQueues());assert.equal(saved[0].items.length,3)
  await page.evaluate(async id=>{await window.mediaCenter.queueEdit({action:'clear'});await window.mediaCenter.loadQueue({id,play:false})},saved[0].id)
  assert.equal((await page.evaluate(()=>window.mediaCenter.playback())).status,'idle')
  await page.getByRole('button',{name:'Open mini player',exact:true}).click()
  const mini=desktop.windows().find(w=>w!==page)||await desktop.waitForEvent('window')
  await mini.getByRole('button',{name:'Play',exact:true}).waitFor()
  await mini.getByRole('button',{name:'Play',exact:true}).click()
  await waitPlayback(p=>p.status==='playing')
  await mini.getByRole('button',{name:'Pause',exact:true}).click()
  await waitPlayback(p=>p.status==='paused')
  const miniSeek=mini.getByRole('slider',{name:'Playback position',exact:true}),seekBox=await miniSeek.boundingBox()
  const miniDuration=(await page.evaluate(()=>window.mediaCenter.playback())).duration
  await mini.mouse.click(seekBox.x+seekBox.width/2,seekBox.y+seekBox.height/2)
  await waitPlayback(p=>p.status==='paused'&&Math.abs(p.position-miniDuration/2)<.2)
  assert.equal(await desktop.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('mini=1')).isAlwaysOnTop()),true)
  assert.equal(await mini.evaluate(()=>window.mediaCenter.settings().then(()=>false,()=>true)),true)
  await mini.getByRole('button',{name:'Unpin mini player',exact:true}).click()
  assert.equal(await desktop.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('mini=1')).isAlwaysOnTop()),false)
  await mini.getByRole('button',{name:'Keep mini player on top',exact:true}).click()
  assert.equal(await desktop.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('mini=1')).isAlwaysOnTop()),true)
  await page.evaluate(()=>window.mediaCenter.miniPlayer({action:'main'}))
  assert.equal(await desktop.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('mini=1')).isAlwaysOnTop()),true,'Pin survives focusing the main window')
  assert.equal(await mini.getByRole('button',{name:'Unpin mini player',exact:true}).getAttribute('aria-pressed'),'true')
  await mini.getByRole('button',{name:'Unpin mini player',exact:true}).click()
  await mini.getByRole('button',{name:'Close mini player',exact:true}).click()
  await page.evaluate(()=>window.mediaCenter.miniPlayer({action:'open'}))
  const reopened=desktop.windows().find(w=>w!==page)||await desktop.waitForEvent('window')
  await reopened.getByRole('button',{name:'Keep mini player on top',exact:true}).waitFor()
  assert.equal((await reopened.evaluate(()=>window.mediaCenter.miniState())).pinned,false,'Reopening preserves unpinned choice')
  await reopened.getByRole('button',{name:'Keep mini player on top',exact:true}).click()
  await reopened.screenshot({path:resolve(artifacts,'mini-player-v03.png')})
  await reopened.getByRole('button',{name:'Close mini player',exact:true}).click()
  const targets=[{target:{kind:'audiobook',serverId:abs.id,bookId:'offline-book'},title:'Offline book',subtitle:'Two physical files'},{target:{kind:'podcast-episode',serverId:abs.id,showId:'offline-show',episodeId:'offline-episode'},title:'Offline episode',subtitle:'One independent episode'}]
  await page.evaluate(items=>window.mediaCenter.downloadAdd(items),targets)
  let downloads
  for(let i=0;i<200;i++){downloads=await page.evaluate(()=>window.mediaCenter.downloadList());if(downloads.entries.every(e=>e.status==='ready'))break;if(downloads.entries.some(e=>e.status==='error'))throw new Error(JSON.stringify(downloads));await new Promise(r=>setTimeout(r,100))}
  assert.equal(downloads.entries.filter(e=>e.status==='ready').length,2)
  assert.ok(!JSON.stringify(downloads).includes('test-token'));assert.ok(!JSON.stringify(downloads).includes('/file/'))
  await page.evaluate(item=>window.mediaCenter.play({queue:[item],index:0,position:5}),targets[0])
  await waitPlayback(p=>p.status==='playing'&&p.kind==='audiobook'&&p.position>=5&&p.sampleRate===96000)
  await page.evaluate(async()=>{await window.mediaCenter.command({action:'toggle'});await window.mediaCenter.command({action:'seek',value:2})})
  assert.ok(Math.abs((await page.evaluate(()=>window.mediaCenter.playback())).position-2)<.05)
  await page.evaluate(async()=>{const p=await window.mediaCenter.playback();await window.mediaCenter.saveNote({item:p.queue[0],position:p.position,title:'Cross-file note',text:'A private listening note'})})
  const preview=await page.evaluate(id=>window.mediaCenter.offlineProgressPreview(id),downloads.entries.find(e=>e.item.target.kind==='audiobook').id)
  assert.ok(Math.abs(preview.localPosition-2)<.05);assert.equal(preview.serverPosition,0)
  await page.evaluate(token=>window.mediaCenter.offlineProgressSync(token),preview.token)
  await page.evaluate(item=>window.mediaCenter.play({queue:[item],index:0,position:1}),targets[1])
  await waitPlayback(p=>p.status==='playing'&&p.kind==='podcast-episode'&&p.position>=1)
  assert.equal((await page.evaluate(()=>window.mediaCenter.playback())).chapters.length,0)
  await page.evaluate(()=>window.mediaCenter.command({action:'stop'}))
  const inbox=await page.evaluate(()=>window.mediaCenter.podcastInbox({page:0,search:'',status:'all',sort:'newest',refresh:true}));assert.equal(inbox.items.length,2);assert.ok(inbox.items.every(e=>e.item.target.kind==='podcast-episode'))
  const home=await page.evaluate(()=>window.mediaCenter.home());assert.ok(home.continuing.length>=1)
  const backupPath=resolve(artifacts,'daily-backup.json')
  await desktop.evaluate(({dialog},path)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:path});dialog.showOpenDialog=async()=>({canceled:false,filePaths:[path]})},backupPath)
  await page.evaluate(()=>window.mediaCenter.exportBackup())
  const backupText=readFileSync(backupPath,'utf8'),backup=JSON.parse(backupText);assert.ok(!backupText.includes('test-token'));assert.ok(!backupText.includes('test-password'));assert.equal(backup.notes.length,1)
  const bp=await page.evaluate(()=>window.mediaCenter.previewBackup());assert.equal(bp.unmatchedServers,0);assert.equal(bp.unmatchedFolders,0)
  await page.evaluate(token=>window.mediaCenter.restoreBackup(token),bp.token)
  assert.equal((await page.evaluate(()=>window.mediaCenter.notes()))[0].title,'Cross-file note')
  writeFileSync(backupPath,JSON.stringify({...backup,secret:'must-not-import'}))
  assert.equal(await page.evaluate(()=>window.mediaCenter.previewBackup().then(()=>false,()=>true)),true)
  const stats=await page.evaluate(()=>window.mediaCenter.listeningStats());assert.ok(stats.totalSeconds>0)
  await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('heading',{name:'Welcome home.'}).waitFor();await page.screenshot({path:resolve(artifacts,'home-v03.png')})
  await page.getByRole('button',{name:'Downloads',exact:true}).click();await page.getByRole('heading',{name:'Offline collection.'}).waitFor();await page.screenshot({path:resolve(artifacts,'downloads-v03.png')})
  await page.getByRole('button',{name:'Listening stats',exact:true}).click()
  await page.getByRole('img',{name:'Listening time over the last 30 days'}).waitFor()
  await page.waitForFunction(()=>[...document.querySelectorAll('.listening-bar')].some(b=>Number(b.getAttribute('height'))>0))
  const bars=await page.locator('.listening-bar').evaluateAll(bs=>bs.filter(b=>Number(b.getAttribute('height'))>0).map(b=>b.getBoundingClientRect().width))
  assert.equal(bars.length,1);assert.ok(bars[0]<40,'One listening day must remain a narrow bar')
  await page.locator('.listening-breakdown>summary').click()
  await page.getByRole('table').waitFor()
  assert.equal(await page.locator('.breakdown-scroll tbody tr').count(),1,'Only active days appear by default')
  assert.ok(!(await page.locator('.breakdown-total').innerText()).includes('—'),'Short sessions still show listening time')
  await page.locator('.listening-breakdown').evaluate(el=>el.scrollIntoView({block:'center'}))
  await page.screenshot({path:resolve(artifacts,'stats-populated.png')})
  await page.getByRole('button',{name:'Create my recap',exact:true}).click()
  await page.locator('.recap-preview img').waitFor()
  const recapPath=resolve(artifacts,'listening-recap.png')
  await desktop.evaluate(({dialog},path)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:path})},recapPath)
  await page.getByRole('button',{name:'Save PNG image',exact:true}).click()
  await page.getByText('Your recap image was saved.',{exact:true}).waitFor()
  const png=readFileSync(recapPath);assert.equal(png.subarray(0,8).toString('hex'),'89504e470d0a1a0a');assert.equal(png.readUInt32BE(16),1080);assert.equal(png.readUInt32BE(20),1440)
  for(const style of ['sunset','ink']){
    await page.locator('.recap-controls select').selectOption(style)
    await desktop.evaluate(({dialog},path)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:path})},resolve(artifacts,'listening-recap-'+style+'.png'))
    await page.getByRole('button',{name:'Save PNG image',exact:true}).click()
    await page.getByText('Your recap image was saved.',{exact:true}).waitFor()
  }
  await desktop.evaluate(({dialog})=>{dialog.showSaveDialog=async()=>({canceled:true})})
  await page.getByRole('button',{name:'Save PNG image',exact:true}).click()
  await page.getByText('Save cancelled.',{exact:true}).waitFor()
  await page.getByLabel('Recap start date',{exact:true}).fill('2000-01-01')
  await page.getByLabel('Recap end date',{exact:true}).fill('2000-01-02')
  assert.equal(await page.getByRole('button',{name:'Save PNG image',exact:true}).isDisabled(),true,'Date edits invalidate old image')
  await page.getByRole('button',{name:'Create my recap',exact:true}).click()
  await page.getByText('No listening was recorded on this device in this date range. Try a different range.',{exact:true}).waitFor()
  await page.getByRole('button',{name:'Listening history',exact:true}).click()
  await page.locator('.history-card').first().waitFor()
  assert.ok((await page.locator('.history-card').first().boundingBox()).height<110)
  await page.screenshot({path:resolve(artifacts,'history-compact.png')})
  await page.getByRole('button',{name:'Downloads',exact:true}).click()
  await page.getByRole('checkbox',{name:'Select download Offline book',exact:true}).check()
  assert.equal(await page.getByRole('checkbox',{name:'Select all downloads'}).evaluate(el=>el.indeterminate),true)
  await page.getByRole('checkbox',{name:'Select all downloads'}).check()
  await page.screenshot({path:resolve(artifacts,'downloads-selected.png')})
  await page.getByRole('button',{name:'Remove selected',exact:true}).click()
  await page.getByRole('button',{name:'Cancel',exact:true}).click()
  assert.equal((await page.evaluate(()=>window.mediaCenter.downloadList())).entries.length,2)
  await page.getByRole('button',{name:'Remove selected',exact:true}).click()
  await page.getByRole('button',{name:'Remove downloads',exact:true}).click()
  await page.getByText('Selected downloads removed.',{exact:true}).waitFor()
  assert.equal((await page.evaluate(()=>window.mediaCenter.downloadList())).entries.length,0)
  await page.getByRole('button',{name:'Listening notes',exact:true}).click();await page.getByRole('heading',{name:'Cross-file note'}).waitFor()
  await page.getByRole('complementary').getByRole('button',{name:/^Play queue/}).click();await page.screenshot({path:resolve(artifacts,'queue-v03.png')})
  await page.evaluate(async q=>{await window.mediaCenter.play({queue:[q],index:0});await window.mediaCenter.command({action:'stop'})},local)
  console.log('Daily checks: mini window, offline book/episode, safe progress sync, inbox, Home, notes, saved queues, stats and backup passed.')
}
