const assert=require('node:assert/strict');const {resolve}=require('node:path');const {readFileSync,writeFileSync,existsSync}=require('node:fs');const {execFile}=require('node:child_process');const {promisify}=require('node:util');
module.exports=async({desktop,page,artifacts})=>{
 console.log('Daily-use 0.8: checking new controls')
 const original=await page.evaluate(async()=>({experience:await window.mediaCenter.experience(),prefs:await window.mediaCenter.preferences(),playback:await window.mediaCenter.playback()}));
 await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:'Customize Home',exact:true}).click();const editor=page.getByRole('dialog',{name:'Customize Home'});await editor.getByLabel('Fresh episodes',{exact:true}).uncheck();await editor.getByRole('button',{name:'Move mixes up',exact:true}).click();await editor.getByRole('button',{name:'Save Home layout',exact:true}).click();await page.waitForFunction(async()=>(await window.mediaCenter.experience()).hiddenSections.includes('episodes'));assert.equal(await page.locator('.home-shelf-track[aria-label="Fresh episodes"]').isVisible(),false)
 await page.getByRole('button',{name:'Preview & edit',exact:true}).first().click();const preview=page.getByRole('dialog',{name:'Make this mix yours'});await preview.getByRole('button',{name:'Regenerate order',exact:true}).click();assert.ok(await preview.locator('.unified-result').count());await preview.screenshot({path:resolve(artifacts,'mix-preview-0.8.png')});await preview.getByRole('button',{name:'Close dialog',exact:true}).click()
 await page.keyboard.press('Control+k');await page.getByRole('dialog',{name:'Search all collections'}).waitFor();await page.getByPlaceholder('Search across your sources…').fill('Original');await page.waitForFunction(()=>document.querySelectorAll('.unified-result').length>0);await page.getByRole('dialog',{name:'Search all collections'}).screenshot({path:resolve(artifacts,'unified-search-0.8.png')});await page.locator('.unified-result').first().click({button:'right'});await page.getByRole('dialog').getByText('Track details',{exact:true}).waitFor();assert.equal(await page.getByRole('dialog',{name:'Search all collections'}).count(),0);await page.getByRole('button',{name:'Close dialog',exact:true}).click()
 await page.getByRole('button',{name:'Local music',exact:true}).click();await page.getByRole('tab',{name:'Songs',exact:true}).click();await page.locator('.local-library-track').first().waitFor();await page.locator('.local-library-track').first().click({button:'right'});const menu=page.getByRole('dialog');await menu.getByText('Track details',{exact:true}).click();await menu.locator('.track-details').waitFor();assert.ok(await menu.locator('.track-details dt').count());await menu.screenshot({path:resolve(artifacts,'track-menu-0.8.png')});await menu.getByRole('button',{name:'Close dialog'}).click()
 const root=(await page.evaluate(()=>window.mediaCenter.localRoots()))[0];const lists=await page.evaluate(rootId=>window.mediaCenter.localLibrary({rootId,view:'playlists',page:0,search:''}),root.id);const list=await page.evaluate(input=>window.mediaCenter.localPlaylistContents(input),{rootId:root.id,id:lists.groups[0].id});const path=resolve(artifacts,'local-roundtrip.m3u8');await desktop.evaluate(({dialog},path)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:path});dialog.showOpenDialog=async()=>({canceled:false,filePaths:[path]})},path);await page.evaluate(input=>window.mediaCenter.localPlaylistFile(input),{rootId:root.id,id:list.id,action:'export'});assert.ok(readFileSync(path,'utf8').startsWith('#EXTM3U'));await page.evaluate(input=>window.mediaCenter.localPlaylistFile(input),{rootId:root.id,action:'import'});const after=await page.evaluate(rootId=>window.mediaCenter.localLibrary({rootId,view:'playlists',page:0,search:''}),root.id);const imported=after.groups.find(g=>g.id!==list.id);assert.ok(imported);await page.evaluate(input=>window.mediaCenter.localPlaylist(input),{action:'delete',rootId:root.id,id:imported.id})
 await page.getByRole('tab',{name:'Playlists',exact:true}).click();await page.getByRole('button',{name:'Open Local test playlist',exact:true}).click();await page.locator('.detail-heading').getByRole('button',{name:'More options',exact:true}).click();await page.getByRole('button',{name:'Customize playlist',exact:true}).click();await page.getByRole('dialog',{name:'Customize local playlist'}).getByLabel('Name',{exact:true}).fill('Temporarily renamed');await page.getByRole('button',{name:'Save playlist',exact:true}).click();await page.waitForFunction(async input=>(await window.mediaCenter.localPlaylistContents(input)).name==='Temporarily renamed',{rootId:root.id,id:list.id});await page.evaluate(input=>window.mediaCenter.localPlaylist(input),{action:'update',rootId:root.id,...list})
 const item=original.playback.queue[0];await page.evaluate(q=>window.mediaCenter.play({queue:[q],index:0}),item);await page.waitForFunction(async()=>(await window.mediaCenter.playback()).status==='playing');await page.evaluate(()=>window.mediaCenter.command({action:'toggle'}));await page.keyboard.press('Control+l');await page.getByLabel('Lyric timing offset',{exact:true}).waitFor();await page.getByLabel('Lyric timing offset',{exact:true}).fill('1.25');await page.waitForFunction(async()=>{const p=await window.mediaCenter.playback(),t=p.queue[p.queueIndex].target;return (await window.mediaCenter.lyricOffset({key:JSON.stringify(['local',t.rootId,t.fileId])}))===1.25});
 const helper=process.env.MEDIA_CENTER_EXECUTABLE?resolve('release/win-unpacked/resources/smtc/MediaCenter.MediaControls.exe'):resolve('artifacts/smtc/MediaCenter.MediaControls.exe');const currentTitle=(await page.evaluate(()=>window.mediaCenter.playback())).title;let media=[];for(let i=0;i<10;i++){media=JSON.parse((await promisify(execFile)(helper,['--inspect'],{windowsHide:true,timeout:15000})).stdout);if(media.some(s=>s.title===currentTitle))break;await new Promise(r=>setTimeout(r,500))}assert.ok(media.some(s=>s.title===currentTitle),'Windows exposes the MPV track through SMTC');writeFileSync(resolve(artifacts,'windows-media-0.8.json'),JSON.stringify(media.filter(s=>s.title===currentTitle),null,2));
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByLabel('search shortcut',{exact:true}).press('Control+Shift+f');await page.getByRole('button',{name:'Load podcast shows',exact:true}).click();await page.getByLabel('Show',{exact:true}).selectOption('0');await page.getByRole('button',{name:'Add show rule',exact:true}).click();assert.equal(await page.locator('.podcast-rule').count(),1);await page.getByRole('button',{name:'Save podcast rules',exact:true}).click();await page.getByText('Podcast rules saved.',{exact:true}).waitFor();assert.equal((await page.evaluate(()=>window.mediaCenter.experience())).shortcuts.search,'Ctrl+Shift+F','Either daily-use save preserves the shared preferences draft');
 await page.getByLabel('search shortcut',{exact:true}).press('Control+Shift+f');await page.getByRole('button',{name:'Save daily-use preferences',exact:true}).click();await page.waitForFunction(async()=>(await window.mediaCenter.experience()).shortcuts.search==='Ctrl+Shift+F');await page.getByRole('button',{name:'Home',exact:true}).click();await page.keyboard.press('Control+Shift+f');await page.getByRole('dialog',{name:'Search all collections'}).waitFor();await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByLabel('Layout density',{exact:true}).selectOption('compact');await page.getByRole('button',{name:'Save theme',exact:true}).click();await page.waitForFunction(()=>document.documentElement.dataset.density==='compact');await page.locator('#settings-listening').screenshot({path:resolve(artifacts,'daily-settings-0.8.png')});
 for(const width of [1008,1440,1920]){
  await page.setViewportSize({width,height:940})
  const panels=await page.locator('.settings-listening-stack>.settings-panel').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,bottom:r.bottom,overflow:el.scrollWidth>el.clientWidth}}))
  assert.equal(panels.length,5)
  for(let i=0;i<panels.length;i++){assert.equal(panels[i].overflow,false,'Settings controls fit their panel');assert.ok(Math.abs(panels[i].width-panels[0].width)<2,'Listening panels share a consistent width');if(i)assert.ok(panels[i].y-panels[i-1].bottom>=14&&panels[i].y-panels[i-1].bottom<=20,'No orphaned Settings panels or large grid gaps')}
  const add=await page.getByRole('button',{name:'Add show rule',exact:true}).boundingBox(),save=await page.getByRole('button',{name:'Save podcast rules',exact:true}).boundingBox();assert.ok(save.y>add.y+add.height+12,'Podcast save action is separate from the add rule controls')
  await page.locator('.listening-preferences').screenshot({path:resolve(artifacts,`settings-preferences-${width}.png`)})
  await page.locator('.listening-reset').screenshot({path:resolve(artifacts,`settings-data-${width}.png`)})
 }
 await page.setViewportSize({width:1440,height:940})
 await page.locator('.listening-podcasts').screenshot({path:resolve(artifacts,'settings-podcasts-polished.png')})
 await desktop.evaluate(({dialog})=>{dialog.showMessageBox=async(_window,options)=>{globalThis.resetConfirmation=options;return{response:0}}});for(const scope of ['cache','personal','all'])assert.equal(await page.evaluate(scope=>window.mediaCenter.resetData(scope),scope),false);assert.equal(await desktop.evaluate(()=>globalThis.resetConfirmation.defaultId),0);
 await page.evaluate(async original=>{await window.mediaCenter.command({action:'stop'});await window.mediaCenter.saveExperience(original.experience);await window.mediaCenter.savePreferences(original.prefs)},original)
 console.log('Daily-use 0.8: Home, mix preview, unified search, track menus, playlist edit/M3U, offsets, SMTC, rules, density and cancelled resets passed')
}
