const assert=require('node:assert/strict')
const {resolve}=require('node:path')
module.exports=async function lyricsSmoke({desktop,page,waitPlayback,artifacts}){
 await desktop.evaluate(()=>{globalThis.__lyricsFetch=globalThis.fetch;globalThis.__lyricsMode='synced';globalThis.__lyricsRequests=[];globalThis.fetch=async(input,options)=>{const url=new URL(String(input));if(url.hostname!=='lrclib.net')return globalThis.__lyricsFetch(input,options);globalThis.__lyricsRequests.push({url:String(url),headers:options.headers});if(url.pathname==='/api/search'||/^\/api\/get\/\d+$/.test(url.pathname)){const record={id:42,trackName:'Manual fixture match',artistName:'Fixture artist',albumName:'Fixture album',duration:600,instrumental:false,plainLyrics:'Selected fixture lyrics.',syncedLyrics:'[00:01]Selected first line\n[00:03]Selected second line'};return new Response(JSON.stringify(url.pathname==='/api/search'?[record]:record))};return new Response(JSON.stringify({duration:600,instrumental:globalThis.__lyricsMode==='instrumental',plainLyrics:'Original fixture text for this test.',syncedLyrics:globalThis.__lyricsMode==='synced'?'[00:00.00]First test line\n[00:02.00]<00:02.00>Second <00:03.00>test line\n[00:04.00]Third test line':null}))}})
 try{
  await page.getByRole('button',{name:'Lyrics',exact:true}).click()
  await page.getByRole('button',{name:'Second test line',exact:true}).waitFor()
  await page.evaluate(async()=>{const p=await window.mediaCenter.playback();if(p.status==='playing')await window.mediaCenter.command({action:'toggle'})})
  await page.getByRole('button',{name:'Second test line',exact:true}).click()
  await waitPlayback(p=>p.status==='paused'&&Math.abs(p.position-2)<.1)
  await page.locator('.lyric-line[aria-current=true]').filter({hasText:'Second test line'}).waitFor()
  assert.equal(await page.getByRole('button',{name:'Second test line',exact:true}).getAttribute('aria-current'),'true')
  assert.equal(await page.locator('.lyric-line.current [data-karaoke]').count(),2)
  await page.evaluate(()=>window.mediaCenter.command({action:'seek',value:2.5}))
  await waitPlayback(p=>p.status==='paused'&&Math.abs(p.position-2.5)<.1)
  await page.waitForFunction(()=>parseFloat(document.querySelector('.lyric-line.current [data-karaoke]')?.style.getPropertyValue('--lyric-fill'))>=49)
  await page.screenshot({path:resolve(artifacts,'lyrics-synced.png')})
  const requests=await desktop.evaluate(()=>globalThis.__lyricsRequests);assert.equal(requests.length,1);assert.ok(!JSON.stringify(requests).includes('test-token'));assert.ok(!JSON.stringify(requests).includes('test-password'))
  await page.evaluate(()=>window.mediaCenter.lyrics({}));assert.equal(await desktop.evaluate(()=>globalThis.__lyricsRequests.length),1)
  await require('./playing-screen-smoke.cjs')({page,waitPlayback,artifacts})
  await page.getByRole('button',{name:'Find lyrics',exact:true}).click()
  await page.getByLabel('Song, artist, or album',{exact:true}).fill('Manual fixture')
  await page.getByRole('button',{name:'Search lyrics',exact:true}).click()
  await page.getByRole('button',{name:/Manual fixture match Fixture artist/}).click()
  await page.screenshot({path:resolve(artifacts,'manual-lyrics-search.png')})
  await page.getByRole('button',{name:'Use these lyrics',exact:true}).click()
  await page.getByRole('button',{name:'Selected first line',exact:true}).waitFor()
  const count=await desktop.evaluate(()=>globalThis.__lyricsRequests.length)
  assert.equal((await page.evaluate(()=>window.mediaCenter.lyrics({refresh:true}))).saved,true)
  assert.equal(await desktop.evaluate(()=>globalThis.__lyricsRequests.length),count,'Saved bindings bypass network even on refresh')
  await page.getByRole('button',{name:'Clear saved match',exact:true}).click()
  await page.getByRole('button',{name:'Second test line',exact:true}).waitFor()
  assert.equal(await page.evaluate(()=>window.mediaCenter.bindLyrics({key:'old-track',id:42}).then(()=>false,()=>true)),true)
  await desktop.evaluate(()=>{globalThis.__lyricsMode='plain'})
  await page.getByRole('button',{name:'Refresh lyrics',exact:true}).click()
  await page.getByText('Plain lyrics · timing unavailable',{exact:true}).waitFor()
  await desktop.evaluate(()=>{globalThis.__lyricsMode='instrumental'})
  await page.getByRole('button',{name:'Refresh lyrics',exact:true}).click()
  await page.getByText('Instrumental — no lyrics for this track.',{exact:true}).waitFor()
  await page.getByRole('button',{name:'Queue',exact:true}).click()
 }finally{await desktop.evaluate(()=>{globalThis.fetch=globalThis.__lyricsFetch;delete globalThis.__lyricsFetch;delete globalThis.__lyricsMode;delete globalThis.__lyricsRequests})}
}
