const assert=require('node:assert/strict')
const {resolve}=require('node:path')
module.exports=async function({desktop,page,artifacts}){
 const home=await page.evaluate(()=>window.mediaCenter.home())
 assert.ok(home.albums.length>8,'Home must retain more than eight recent albums')
 const nav=await page.evaluate(async()=>(await window.mediaCenter.settings()).connections.find(c=>c.provider==='navidrome').id)
 const extra=await page.evaluate(serverId=>window.mediaCenter.homeAlbums({serverId,page:1}),nav)
 assert.equal(extra.page,1);assert.ok(Array.isArray(extra.albums))
 await page.getByRole('button',{name:'Home',exact:true}).click()
 await page.getByRole('button',{name:'Load more albums',exact:true}).click()
 await page.waitForFunction(()=>document.querySelectorAll('.home-album-card').length===65)
 assert.equal(await page.getByRole('button',{name:'Load more albums',exact:true}).count(),0)
 await page.getByRole('button',{name:'Create mix',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Create your mix',exact:true})
 await dialog.getByLabel('Mix name',{exact:true}).fill('Evening test mix')
 await dialog.getByLabel('Description',{exact:true}).fill('Artist, genre and year rules from my collection.')
 await dialog.getByRole('button',{name:'Preview mix',exact:true}).click()
 await dialog.locator('.mix-preview-track').first().waitFor()
 await dialog.getByRole('button',{name:'Add rule group',exact:true}).click()
 await dialog.getByLabel('Rule 1.1 field',{exact:true}).selectOption('artist')
 await dialog.getByLabel('Rule 1.1 operator',{exact:true}).selectOption('contains')
 await dialog.getByLabel('Rule 1.1 value',{exact:true}).fill('Test Artist')
 await dialog.getByRole('button',{name:'Preview mix',exact:true}).click()
 await dialog.locator('.mix-preview-track').first().waitFor()
 assert.equal(await dialog.locator('.mix-preview-track').count(),1)
 await dialog.getByRole('button',{name:'Play selection',exact:true}).click()
 await page.waitForFunction(async()=>{const p=await window.mediaCenter.playback();return p.status==='playing'&&p.queue[p.queueIndex]?.target.kind==='music-track'})
 await page.evaluate(()=>window.mediaCenter.command({action:'stop'}))
 await dialog.getByRole('button',{name:'Save mix',exact:true}).click()
 await dialog.getByText(/Mix saved/).waitFor()
 await page.screenshot({path:resolve(artifacts,'custom-mix-builder-1.2.png')})
 await dialog.getByRole('button',{name:'Close dialog',exact:true}).click()
 // Saved mixes play directly without requiring the editor or an earlier preview.
 await page.getByRole('button',{name:'Home',exact:true}).click()
 const card=page.locator('.home-mix.custom-mix-card').filter({hasText:'Evening test mix'})
 await card.getByRole('button',{name:'Play mix Evening test mix',exact:true}).click()
 await page.waitForFunction(async()=>{const p=await window.mediaCenter.playback();return p.status==='playing'&&p.queue[p.queueIndex]?.target.kind==='music-track'})
 assert.equal(await page.getByRole('dialog').count(),0)
 for(const width of [1008,1440]){
  await page.setViewportSize({width,height:940})
  assert.ok(await card.evaluate(el=>{const r=el.getBoundingClientRect();return [...el.querySelectorAll('button')].every(b=>{const x=b.getBoundingClientRect();return x.top>=r.top&&x.bottom<=r.bottom})}),'Saved mix actions fit inside the Home card')
 }
 await page.waitForFunction(()=>document.querySelector('.home-mix.custom-mix-card .mix-play')?.getAttribute('aria-busy')==='false')
 await card.screenshot({path:resolve(artifacts,'custom-mix-direct-play.png')})
 const empty=await page.evaluate(async()=>{const a=window.mediaCenter,m=(await a.personalState()).mixes.find(m=>m.name==='Evening test mix'),mix={...m,id:crypto.randomUUID(),name:'No matching songs fixture',groups:[{match:'all',conditions:[{type:'text',field:'artist',operator:'equals',value:'No artist with this fixture name'}]}]};await a.personalChange({action:'mix-save',mix});return mix.id})
 const beforeEmpty=await page.evaluate(()=>window.mediaCenter.playback())
 await page.getByRole('button',{name:'Play mix No matching songs fixture',exact:true}).click()
 await page.getByText('No songs match this mix. Open the mix to adjust its rules or sources.',{exact:true}).waitFor()
 const afterEmpty=await page.evaluate(()=>window.mediaCenter.playback());assert.deepEqual(afterEmpty.queue.map(q=>q.target),beforeEmpty.queue.map(q=>q.target));assert.equal(afterEmpty.queueIndex,beforeEmpty.queueIndex);assert.equal(afterEmpty.status,'playing')
 await page.evaluate(id=>window.mediaCenter.personalChange({action:'mix-delete',id}),empty)
 await page.getByRole('button',{name:'Dismiss error',exact:true}).click()

 await page.evaluate(()=>window.mediaCenter.command({action:'stop'}))
 await page.getByRole('button',{name:'Library tools',exact:true}).click()
 await page.getByRole('tab',{name:'Custom mixes',exact:true}).click()
 await page.getByRole('button',{name:'Play mix Evening test mix',exact:true}).click()
 await page.waitForFunction(async()=>{const p=await window.mediaCenter.playback();return p.status==='playing'&&p.queue[p.queueIndex]?.target.kind==='music-track'})
 await page.evaluate(()=>window.mediaCenter.command({action:'stop'}))

 await page.getByRole('button',{name:'Open mix',exact:true}).click()
 assert.equal(await dialog.getByLabel('Rule 1.1 value',{exact:true}).inputValue(),'Test Artist')
 await dialog.getByRole('button',{name:'Close dialog',exact:true}).click()
 // All collection headers use the same layout, including customized collection names.
 for(const name of ['Music','Local music','Audiobooks','Podcasts']){
  await page.getByRole('button',{name,exact:true}).click()
  await page.locator('.library-heading h1').waitFor()
  assert.equal(await page.locator('.library-heading h1').innerText(),name)
  for(const width of [1024,1440]){
   await desktop.evaluate(({BrowserWindow},width)=>BrowserWindow.getAllWindows().find(w=>!w.isDestroyed()&&w.getTitle().includes('Media Center')).setSize(width,900),width)
   await page.waitForTimeout(100)
   const fit=await page.locator('.library-heading').evaluate(el=>({width:el.clientWidth,scroll:el.scrollWidth}))
   assert.ok(fit.scroll<=fit.width+1,`${name} header overflows at ${width}`)
  }
  await page.screenshot({path:resolve(artifacts,`collection-${name.replaceAll(' ','-').toLowerCase()}-1.2.png`)})
 }
 await page.getByRole('button',{name:'Home',exact:true}).click()
 await page.locator('.home-album-card').nth(8).waitFor({state:'attached'})
 await page.screenshot({path:resolve(artifacts,'home-mixes-1.2.png')})
 await page.reload()
 assert.ok((await page.evaluate(()=>window.mediaCenter.personalState())).mixes.some(m=>m.name==='Evening test mix'))
 console.log('Custom mixes 1.2 passed: saved artist rules, preview, native playback, restart persistence, recent-album pagination and four responsive collection headers.')
}
