const assert=require('node:assert/strict')
const {resolve}=require('node:path')
module.exports=async({page,artifacts})=>{
 const original=await page.evaluate(()=>window.mediaCenter.experience())
 const expandedWidth=await page.locator('.workspace').evaluate(el=>el.getBoundingClientRect().width)
 await page.getByRole('button',{name:'Collapse sidebar',exact:true}).click()
 await page.locator('.app-shell.sidebar-collapsed').waitFor()
 assert.ok(await page.locator('.workspace').evaluate(el=>el.getBoundingClientRect().width)>expandedWidth+100,'Collapsing gives space back to the page')
 assert.equal(await page.locator('.sidebar .nav-item').first().locator('span').isVisible(),false)
 for(const button of await page.locator('.sidebar .nav-item').all())assert.ok(await button.getAttribute('title'),'Icon-only navigation has a tooltip')
 await page.getByRole('button',{name:'Downloads',exact:true}).click()
 assert.ok(await page.getByRole('button',{name:'Downloads',exact:true}).evaluate(el=>el.classList.contains('selected')))
 await page.getByRole('button',{name:'Listening Space',exact:true}).click()
 assert.equal((await page.evaluate(()=>window.mediaCenter.experience())).navigation.sidebarCollapsed,true)
 await page.reload()
 await page.getByRole('button',{name:'Expand sidebar',exact:true}).waitFor()
 assert.equal(await page.getByRole('button',{name:'Listening Space',exact:true}).getAttribute('aria-expanded'),'false')
 await page.getByRole('button',{name:'Listening Space',exact:true}).click()
 await page.getByRole('button',{name:'Music',exact:true}).click()
 await page.screenshot({path:resolve(artifacts,'sidebar-icons.png')})
 const expand=page.getByRole('button',{name:'Expand sidebar',exact:true})
 await expand.focus();await page.keyboard.press('Enter')
 await page.getByRole('button',{name:'Collapse sidebar',exact:true}).waitFor()
 assert.equal(await page.locator('.sidebar .nav-item').first().locator('span').isVisible(),true)

 const sidebar=page.locator('.sidebar')
 assert.equal(await sidebar.locator('.engine-card').count(),0)
 await sidebar.getByRole('button',{name:'Customize collections',exact:true}).click()
 const controls=page.getByRole('region',{name:'Collection controls',exact:true})
 await controls.getByLabel('Music name',{exact:true}).fill('My records')
 await controls.getByLabel('Music icon',{exact:true}).selectOption('disc')
 await controls.getByLabel('Audiobooks name',{exact:true}).fill('My books')
 await controls.getByLabel('Podcasts name',{exact:true}).fill('My shows')
 await controls.getByLabel('Local music name',{exact:true}).fill('On this PC')
 await controls.getByLabel('Library tools name',{exact:true}).fill('My library tools')
 await controls.getByRole('button',{name:'Save collection controls',exact:true}).click()
 await sidebar.getByRole('button',{name:'My records',exact:true}).waitFor()
 assert.equal(await sidebar.getByRole('button',{name:'My records',exact:true}).locator('.lucide-disc3').count(),1)
 const draft=page.getByRole('checkbox',{name:/Continue with more music when the queue ends/})
 await draft.check()
 const toggle=sidebar.getByRole('button',{name:'Listening Space',exact:true})
 await toggle.click();await page.locator('#listening-navigation').waitFor({state:'hidden'})
 assert.equal(await draft.isChecked(),true,'Collapsing navigation preserves an unsaved settings draft')
 assert.equal(await toggle.getAttribute('aria-expanded'),'false')
 await toggle.focus();await page.keyboard.press('Enter')
 await sidebar.getByRole('button',{name:'Play queue',exact:true}).waitFor()
 await toggle.click();await page.locator('#listening-navigation').waitFor({state:'hidden'})
 // A stale full preferences save must not overwrite newer navigation edits.
 await page.evaluate(p=>window.mediaCenter.saveExperience(p),original)
 assert.equal((await page.evaluate(()=>window.mediaCenter.experience())).navigation.listeningCollapsed,true)
 await page.getByRole('button',{name:'Collapse sidebar',exact:true}).click()
 await page.evaluate(p=>window.mediaCenter.saveExperience(p),original)
 assert.equal((await page.evaluate(()=>window.mediaCenter.experience())).navigation.sidebarCollapsed,true)
 await page.getByRole('button',{name:'Expand sidebar',exact:true}).click()
 await page.reload();await sidebar.getByRole('button',{name:'My records',exact:true}).waitFor()
 assert.equal(await toggle.getAttribute('aria-expanded'),'false')
 await sidebar.getByRole('button',{name:'My books',exact:true}).click()
 assert.equal(await page.locator('.breadcrumb strong').innerText(),'My books')
 await sidebar.getByRole('button',{name:'Settings',exact:true}).click()
 await page.getByRole('heading',{name:'MPV audio engine',exact:true}).waitFor()
 assert.match(await page.locator('.mpv-settings-status').innerText(),/Player setup needed\s+Choose mpv.exe below to start listening\./)
 await sidebar.getByRole('button',{name:'Customize collections',exact:true}).click()
 await page.waitForFunction(()=>{const r=document.getElementById('collection-controls').getBoundingClientRect();return r.top<220&&r.bottom>250})
 await page.screenshot({path:resolve(artifacts,'collection-controls.png')})
 for(const width of [1008,1440]){
  await page.setViewportSize({width,height:940})
  assert.equal(await controls.evaluate(el=>el.scrollWidth<=el.clientWidth+1),true)
 }
 await controls.getByRole('button',{name:'Reset collection defaults',exact:true}).click()
 await controls.getByRole('button',{name:'Save collection controls',exact:true}).click()
 await sidebar.getByRole('button',{name:'Music',exact:true}).waitFor()
 await toggle.click();await page.locator('#listening-navigation').waitFor({state:'visible'})
 assert.equal(await page.evaluate(()=>window.mediaCenter.saveNavigation({action:'listening',collapsed:'bad'}).then(()=>false,()=>true)),true)
 await sidebar.getByRole('button',{name:'Music',exact:true}).click()
 console.log('Navigation: icon-only sidebar, tooltips, keyboard expansion and independent saved collapse states; collection names/icons, reset, sidebar collapse/keyboard/reload persistence, stale-save protection, responsive controls and Settings MPV status passed.')
}
