const assert=require('node:assert/strict');const {resolve,sep}=require('node:path');const {writeFileSync,readFileSync}=require('node:fs');
module.exports=async({desktop,page,artifacts,mutations})=>{
 console.log('Studio 0.9: checking library tools, editing, native transitions and recap layouts')
 await page.setViewportSize({width:1440,height:960});await desktop.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows().forEach(w=>{w.webContents.setBackgroundThrottling(false);w.showInactive()})});
 const before=await page.evaluate(async()=>({settings:await window.mediaCenter.settings(),prefs:await window.mediaCenter.preferences(),lyrics:await window.mediaCenter.playingScreenPreferences(),player:await window.mediaCenter.playback(),roots:await window.mediaCenter.localRoots()}));const root=before.roots[0];
 await page.keyboard.press('Control+Shift+p');const palette=page.getByRole('dialog',{name:'Command palette'});await palette.getByLabel('Find an action',{exact:true}).fill('listening profiles');await page.keyboard.press('Enter');await page.getByLabel('Profile name',{exact:true}).fill('Test listening setup');await page.getByRole('button',{name:'Save current setup',exact:true}).click();await page.getByText('Profile saved.',{exact:true}).waitFor();const profile=(await page.evaluate(()=>window.mediaCenter.profiles()))[0];assert.ok(profile);
 await page.evaluate(async()=>{const a=window.mediaCenter,p=await a.preferences();await a.savePreferences({...p,theme:'ocean'});await a.command({action:'volume',value:0})});await page.getByRole('button',{name:'Apply Test listening setup',exact:true}).click();await page.getByText('Profile applied.',{exact:true}).waitFor();assert.equal((await page.evaluate(()=>window.mediaCenter.preferences())).theme,before.prefs.theme);await page.screenshot({path:resolve(artifacts,'profiles-0.9.png')});await page.evaluate(()=>window.mediaCenter.command({action:'volume',value:0}));
 // Output memory restores a real device's saved settings without loading unavailable outputs.
 await page.evaluate(async()=>{const a=window.mediaCenter;await a.outputProfile('save');const s=await a.settings();await a.setAudio({audioDevice:'fixture-unavailable',exclusive:false});await a.command({action:'volume',value:0});await a.setAudio({audioDevice:s.audioDevice,exclusive:s.exclusive})});assert.equal((await page.evaluate(()=>window.mediaCenter.outputProfile('get'))).saved,true);
 await page.getByRole('tab',{name:'Library health',exact:true}).click();await page.getByRole('button',{name:'Check library health',exact:true}).click();await page.locator('.health-row').first().waitFor();await page.screenshot({path:resolve(artifacts,'library-health-0.9.png')});const health=await page.evaluate(id=>window.mediaCenter.libraryHealth(id),root.id);assert.ok(health.scanned>0);assert.ok(health.issues.some(i=>i.issues.includes('Missing artwork')));
 await page.getByRole('tab',{name:'Book series',exact:true}).click();await page.getByRole('heading',{name:'Test Series',exact:true}).waitFor();await page.screenshot({path:resolve(artifacts,'book-series-0.9.png')});const series=await page.evaluate(()=>window.mediaCenter.seriesShelves());assert.equal(series.shelves[0].books[0].sequence,'2');assert.equal(series.shelves[0].books[0].item.target.kind,'audiobook');
 await page.getByRole('tab',{name:'Podcast subscriptions',exact:true}).click();await page.getByLabel('Show name or RSS URL',{exact:true}).fill('Fixture');await page.getByRole('button',{name:'Find podcasts',exact:true}).click();await page.getByRole('checkbox',{name:/Fixture podcast discovery/}).check();await page.getByRole('button',{name:'Subscribe to 1 selected',exact:true}).click();await page.getByText(/Subscriptions requested/).waitFor();assert.deepEqual(mutations.find(m=>m.path==='/api/podcasts/opml/create').payload,{libraryId:'podcasts',folderId:'pod-folder',feeds:['https://example.test/new.xml'],autoDownloadEpisodes:false});const destination=(await page.evaluate(()=>window.mediaCenter.podcastDestinations()))[0];const rss=await page.evaluate(serverId=>window.mediaCenter.podcastDiscover({serverId,query:'https://example.test/feed.xml'}),destination.serverId);assert.equal(rss[0].title,'Fixture RSS show');
 const opml=resolve(artifacts,'studio-import.opml');writeFileSync(opml,'<opml version="2.0"><body><outline type="rss" text="Imported fixture show" xmlUrl="https://example.test/imported.xml"/></body></opml>');await desktop.evaluate(({dialog},path)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[path]})},opml);await page.getByRole('button',{name:'Import OPML',exact:true}).click();await page.getByRole('checkbox',{name:/Imported fixture show/}).waitFor();await page.screenshot({path:resolve(artifacts,'podcast-subscriptions-0.9.png')});const exportPath=resolve(artifacts,'studio-subscriptions.opml');await desktop.evaluate(({dialog},path)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:path})},exportPath);await page.getByRole('button',{name:'Export OPML',exact:true}).click();await page.getByText('Subscriptions exported.',{exact:true}).waitFor();assert.ok(readFileSync(exportPath,'utf8').includes('https://example.test/podcast.xml'));
 await page.getByRole('tab',{name:'Connections',exact:true}).click();await page.getByRole('button',{name:'Retry connections',exact:true}).waitFor();const reportPath=resolve(artifacts,'studio-diagnostics.json');await desktop.evaluate(({dialog},path)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:path})},reportPath);await page.getByRole('button',{name:'Export diagnostics report',exact:true}).click();await page.getByText('Diagnostics report saved.',{exact:true}).waitFor();const report=readFileSync(reportPath,'utf8');assert.ok(!/test-token|test-password|127\.0\.0\.1|Original Audio|Test Books/.test(report));await page.screenshot({path:resolve(artifacts,'connections-0.9.png')});
 // Undo changes is guarded by a snapshot, and never starts playback for the active item.
 const local=before.player.queue[0];await page.evaluate(async q=>{const a=window.mediaCenter;await a.play({queue:[q,q,q],index:0});await a.command({action:'toggle'});await a.queueEdit({action:'remove',index:2});await a.undo()},local);let state=await page.evaluate(()=>window.mediaCenter.playback());assert.equal(state.queue.length,3);assert.equal(state.status,'paused');const lists=await page.evaluate(rootId=>window.mediaCenter.localLibrary({rootId,view:'playlists',page:0,search:''}),root.id);const list=await page.evaluate(i=>window.mediaCenter.localPlaylistContents(i),{rootId:root.id,id:lists.groups[0].id});await page.evaluate(async i=>{await window.mediaCenter.localPlaylist(i);await window.mediaCenter.undo()},{action:'update',rootId:root.id,id:list.id,name:'Temporary change',files:[]});assert.equal((await page.evaluate(i=>window.mediaCenter.localPlaylistContents(i),{rootId:root.id,id:list.id})).name,list.name);
 // Embedded USLT lyrics in an isolated WAV fixture, using the same native picker boundary.
 assert.ok(resolve(root.path).startsWith(resolve(artifacts)+sep));const embeddedPath=resolve(root.path,'embedded-studio-test.wav'),wav=Buffer.alloc(44+16000*30);wav.write('RIFF');wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);const payload=Buffer.concat([Buffer.from([0]),Buffer.from('eng'),Buffer.from([0]),Buffer.from('Embedded fixture verse')]),frame=Buffer.alloc(10);frame.write('USLT');frame.writeUInt32BE(payload.length,4);const tag=Buffer.alloc(10);tag.write('ID3');tag[3]=3;const size=frame.length+payload.length;for(let n=0;n<4;n++)tag[6+n]=(size>>((3-n)*7))&127;const id3=Buffer.concat([tag,frame,payload]),chunk=Buffer.alloc(8);chunk.write('id3 ');chunk.writeUInt32LE(id3.length,4);const file=Buffer.concat([wav,chunk,id3,...(id3.length%2?[Buffer.from([0])]:[])]);file.writeUInt32LE(file.length-8,4);writeFileSync(embeddedPath,file);const embeddedItem={target:{kind:'local-file',serverId:'local',rootId:root.id,fileId:'embedded-studio-test.wav'},title:'Embedded fixture',subtitle:'Fixture artist'},embeddedKey=JSON.stringify(['local',root.id,'embedded-studio-test.wav']);await page.evaluate(q=>window.mediaCenter.play({queue:[q],index:0}),embeddedItem);assert.equal(await page.evaluate(key=>window.mediaCenter.lyricImport({key,source:'embedded'}),embeddedKey),true);assert.equal((await page.evaluate(()=>window.mediaCenter.lyrics({}))).plain,'Embedded fixture verse');await page.evaluate(q=>window.mediaCenter.play({queue:[q],index:0}),local);await page.evaluate(()=>window.mediaCenter.command({action:'toggle'}));
 // Native lyric import and individual timing editing; bind survives closing the panel.
 const key=JSON.stringify(['local',local.target.rootId,local.target.fileId]),lyricPath=resolve(artifacts,'studio-fixture.lrc');writeFileSync(lyricPath,'[00:01.000]<00:01.000>Fixture <00:02.000>words<00:03.000>\n[00:04.000]Second fixture line');await desktop.evaluate(({dialog},path)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[path]})},lyricPath);assert.equal(await page.evaluate(key=>window.mediaCenter.lyricImport({key,source:'file'}),key),true);await page.getByRole('button',{name:'Open now playing',exact:true}).click();await page.getByRole('button',{name:'Lyrics',exact:true}).click();await page.getByRole('button',{name:'Edit lyrics & timing',exact:true}).click();const editor=page.getByRole('dialog',{name:'Edit song lyrics'});await editor.getByLabel('Lyric text',{exact:true}).fill('[00:02.000]Edited fixture line\n[00:04.000]Second fixture line');await editor.getByRole('button',{name:'Save song lyrics',exact:true}).click();await page.getByRole('button',{name:'Edited fixture line',exact:true}).waitFor();assert.equal((await page.evaluate(()=>window.mediaCenter.lyrics({}))).saved,true);
 await page.getByRole('button',{name:'Local music',exact:true}).click();await page.getByRole('tab',{name:'Playlists',exact:true}).click();await page.getByRole('button',{name:'Open '+list.name,exact:true}).click();await page.getByRole('button',{name:'Design playlist cover',exact:true}).click();const designer=page.getByRole('dialog',{name:'Design playlist cover'});await designer.getByRole('button',{name:'Generate collage',exact:true}).click();await designer.locator('.cover-preview img').waitFor();await designer.getByRole('button',{name:'Save playlist cover',exact:true}).click();await designer.getByText('Playlist cover saved.',{exact:true}).waitFor();await designer.screenshot({path:resolve(artifacts,'playlist-designer-0.9.png')});await designer.getByRole('button',{name:'Close dialog',exact:true}).click();assert.ok((await page.evaluate(i=>window.mediaCenter.playlistArtwork(i),{source:root.id,id:list.id,action:'get'})).startsWith('data:image/png;base64,'));
 await page.getByRole('button',{name:'Listening stats',exact:true}).click();await page.getByRole('button',{name:'Create my recap',exact:true}).click();await page.locator('.recap-preview img').waitFor();const styles=await page.getByLabel('Picture style',{exact:true}).locator('option').evaluateAll(os=>os.map(o=>o.value));assert.equal(styles.length,12);const pictures=new Set();for(const style of styles){await page.getByLabel('Picture style',{exact:true}).selectOption(style);pictures.add(await page.locator('.recap-preview img').getAttribute('src'))}assert.equal(pictures.size,12);assert.equal(await page.getByLabel('Recap color palette',{exact:true}).locator('option').count(),12);await page.getByLabel('Picture style',{exact:true}).selectOption('mixtape');await page.getByLabel('Recap color palette',{exact:true}).selectOption('coral');await page.locator('.recap-section').scrollIntoViewIfNeeded();await page.screenshot({path:resolve(artifacts,'recap-controls-0.9.png')});
 // Real MPV overlap at the end of a song, including pause and stop while fading.
 const nav=before.settings.connections.find(c=>c.provider==='navidrome'),q={target:{kind:'music-track',serverId:nav.id,trackId:'song'},title:'Original Audio',subtitle:'Test Artist'};
 await page.evaluate(async q=>{const a=window.mediaCenter;await a.command({action:'stop'});await a.command({action:'volume',value:0});await a.setAudio({audioDevice:'auto',exclusive:false});await a.transitions({seconds:6,preserveAlbums:false});await a.play({queue:[q,{...q,target:{...q.target,trackId:'second-song'}},{...q,target:{...q.target,trackId:'third-song'}}],index:0});await a.command({action:'seek',value:595})},q);
 await page.waitForFunction(async()=>{const p=await window.mediaCenter.playback();return p.queueIndex===1&&p.status==='playing'&&p.crossfading},{},{timeout:20000});await page.evaluate(()=>window.mediaCenter.command({action:'toggle'}));state=await page.evaluate(()=>window.mediaCenter.playback());assert.equal(state.status,'paused');assert.equal(state.crossfading,true);await page.evaluate(()=>window.mediaCenter.command({action:'toggle'}));await page.waitForFunction(async()=>{const p=await window.mediaCenter.playback();return p.queueIndex===1&&!p.crossfading&&p.status==='playing'},{},{timeout:15000});state=await page.evaluate(()=>window.mediaCenter.playback());assert.ok(state.position<20,'Crossfade starts the incoming song at its own position');await page.evaluate(()=>window.mediaCenter.command({action:'seek',value:595}));await page.waitForFunction(async()=>{const p=await window.mediaCenter.playback();return p.queueIndex===2&&p.crossfading},{},{timeout:20000});await page.evaluate(()=>window.mediaCenter.command({action:'stop'}));assert.equal((await page.evaluate(()=>window.mediaCenter.playback())).crossfading,false);await page.evaluate(()=>window.mediaCenter.transitions({seconds:0,preserveAlbums:true}));
 await page.setViewportSize({width:1008,height:680});await page.getByRole('button',{name:'Library tools',exact:true}).click();await page.getByRole('tab',{name:'Listening profiles',exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:resolve(artifacts,'studio-narrow-0.9.png')});
 console.log('Studio 0.9 passed: command palette, profiles, output memory, health, series, RSS/OPML, diagnostics, undo, lyric editing, covers, 12 recaps and real MPV crossfade.')
}
