const assert=require('node:assert/strict')
const {resolve}=require('node:path')
module.exports=async function themeSmoke(page,artifacts){
 const original=await page.evaluate(()=>window.mediaCenter.preferences())
 await page.getByRole('button',{name:'Settings',exact:true}).click()
 await page.locator('.theme-grid').waitFor()
 await page.locator('.discord-diagnostics').waitFor()
 assert.match(await page.locator('.discord-diagnostics').innerText(),/Connection[\s\S]*Artwork/)
 assert.equal(await page.getByRole('button',{name:'Retry artwork',exact:true}).isDisabled(),true)
 assert.equal((await page.evaluate(()=>window.mediaCenter.discordStatus())).connected,false)
 assert.match(await page.locator('.settings-panel').filter({has:page.locator('.discord-diagnostics')}).innerText(),/Leave the custom ID empty/)
 const discordId=page.getByLabel('Custom Discord Application ID (optional)',{exact:true});assert.match(await discordId.getAttribute('placeholder'),/1546622716554121296/)
 await page.getByLabel('Enable Discord Rich Presence',{exact:true}).check();assert.equal(await page.getByRole('button',{name:'Save Discord preferences',exact:true}).isEnabled(),true);await discordId.fill('invalid');assert.equal(await page.getByRole('button',{name:'Save Discord preferences',exact:true}).isDisabled(),true);await discordId.fill('');await page.getByLabel('Enable Discord Rich Presence',{exact:true}).uncheck()
 await page.locator('.discord-diagnostics').scrollIntoViewIfNeeded()
 await page.screenshot({path:resolve(artifacts,'discord-settings.png')})
 assert.equal(await page.locator('.theme-swatch').count(),13)
 for(const name of ['Glass','Midnight','Ocean','Rose','Lavender','Ember','Coffee','Nord','Monochrome','Aubergine','Black Glass']){
  await page.getByRole('button',{name,exact:true}).click()
  await page.getByRole('button',{name:'Save audio preferences',exact:true}).click()
  await page.waitForFunction(id=>document.documentElement.dataset.theme===id,name.toLowerCase().replace(' ','-'))
  assert.equal((await page.evaluate(()=>window.mediaCenter.preferences())).theme,name.toLowerCase().replace(' ','-'))
 }
 await page.getByRole('button',{name:'Glass',exact:true}).click()
 await page.getByRole('button',{name:'Save audio preferences',exact:true}).click()
 await page.getByRole('button',{name:'Home',exact:true}).click()
 await page.locator('.home-shelf-track[aria-label="Continue listening"]').waitFor()
 assert.equal(await page.locator('.workspace').evaluate(el=>el.scrollWidth>el.clientWidth),false)
 assert.ok(await page.locator('.sidebar').evaluate(el=>getComputedStyle(el).backdropFilter.includes('blur')))
 await page.screenshot({path:resolve(artifacts,'theme-glass.png')})
 await page.getByRole('button',{name:'Settings',exact:true}).click()
 await page.getByRole('button',{name:'Black Glass',exact:true}).click()
 await page.getByRole('button',{name:'Save audio preferences',exact:true}).click()
 await page.getByRole('button',{name:'Home',exact:true}).click()
 await page.screenshot({path:resolve(artifacts,'theme-black-glass.png')})
 await page.evaluate(p=>window.mediaCenter.savePreferences(p),original)
}
